<?php
/**
 * Locale data for 'aa_ET'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * @copyright 2008-2013 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '4123',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'ETB' => 'Br',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Qunxa Garablu',
      2 => 'Kudo',
      3 => 'Ciggilta Kudo',
      4 => 'Agda Baxis',
      5 => 'Caxah Alsa',
      6 => 'Qasa Dirri',
      7 => 'Qado Dirri',
      8 => 'Liiqen',
      9 => 'Waysu',
      10 => 'Diteli',
      11 => 'Ximoli',
      12 => 'Kaxxa Garablu',
    ),
    'abbreviated' => 
    array (
      1 => 'Qun',
      2 => 'Nah',
      3 => 'Cig',
      4 => 'Agd',
      5 => 'Cax',
      6 => 'Qas',
      7 => 'Qad',
      8 => 'Leq',
      9 => 'Way',
      10 => 'Dit',
      11 => 'Xim',
      12 => 'Kax',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => 'Q',
      2 => 'N',
      3 => 'C',
      4 => 'A',
      5 => 'C',
      6 => 'Q',
      7 => 'Q',
      8 => 'L',
      9 => 'W',
      10 => 'D',
      11 => 'X',
      12 => 'K',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Acaada',
      1 => 'Etleeni',
      2 => 'Talaata',
      3 => 'Arbaqa',
      4 => 'Kamiisi',
      5 => 'Gumqata',
      6 => 'Sabti',
    ),
    'abbreviated' => 
    array (
      0 => 'Aca',
      1 => 'Etl',
      2 => 'Tal',
      3 => 'Arb',
      4 => 'Kam',
      5 => 'Gum',
      6 => 'Sab',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'A',
      1 => 'E',
      2 => 'T',
      3 => 'A',
      4 => 'K',
      5 => 'G',
      6 => 'S',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'Yaasuusuk Duma',
      1 => 'Yaasuusuk Wadir',
    ),
    'wide' => 
    array (
      0 => 'Yaasuusuk Duma',
      1 => 'Yaasuusuk Wadir',
    ),
    'narrow' => 
    array (
      0 => 'Yaasuusuk Duma',
      1 => 'Yaasuusuk Wadir',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, MMMM dd, y',
    'long' => 'dd MMMM y',
    'medium' => 'dd-MMM-y',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'saaku',
  'pmName' => 'carra',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'aa' => 'Qafar',
    'ar' => 'Arabic',
    'de' => 'German',
    'en' => 'English',
    'es' => 'Spanish',
    'fr' => 'French',
    'hi' => 'Hindi',
    'it' => 'Italian',
    'ja' => 'Japanese',
    'pt' => 'Portuguese',
    'ru' => 'Russian',
    'zh' => 'Chinese',
  ),
  'scripts' => 
  array (
    'latn' => 'Latin',
  ),
  'territories' => 
  array (
    'br' => 'Brazil',
    'cn' => 'China',
    'de' => 'Germany',
    'dj' => 'Yabuuti',
    'er' => 'Eretria',
    'et' => 'Otobbia',
    'fr' => 'France',
    'gb' => 'United Kingdom',
    'in' => 'India',
    'it' => 'Italy',
    'jp' => 'Japan',
    'ru' => 'Russia',
    'us' => 'United States',
  ),
);
