<?php
/**
 * Locale data for 'haw_US'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2011 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '4123',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00;(¤#,##0.00)',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => 'Ianuali',
      2 => 'Pepeluali',
      3 => 'Malaki',
      4 => 'ʻApelila',
      5 => 'Mei',
      6 => 'Iune',
      7 => 'Iulai',
      8 => 'ʻAukake',
      9 => 'Kepakemapa',
      10 => 'ʻOkakopa',
      11 => 'Nowemapa',
      12 => 'Kekemapa',
    ),
    'abbreviated' => 
    array (
      1 => 'Ian.',
      2 => 'Pep.',
      3 => 'Mal.',
      4 => 'ʻAp.',
      5 => 'Mei',
      6 => 'Iun.',
      7 => 'Iul.',
      8 => 'ʻAu.',
      9 => 'Kep.',
      10 => 'ʻOk.',
      11 => 'Now.',
      12 => 'Kek.',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Lāpule',
      1 => 'Poʻakahi',
      2 => 'Poʻalua',
      3 => 'Poʻakolu',
      4 => 'Poʻahā',
      5 => 'Poʻalima',
      6 => 'Poʻaono',
    ),
    'abbreviated' => 
    array (
      0 => 'LP',
      1 => 'P1',
      2 => 'P2',
      3 => 'P3',
      4 => 'P4',
      5 => 'P5',
      6 => 'P6',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => '1',
      1 => '2',
      2 => '3',
      3 => '4',
      4 => '5',
      5 => '6',
      6 => '7',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'wide' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
    'narrow' => 
    array (
      0 => 'BCE',
      1 => 'CE',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, d MMMM y',
    'long' => 'd MMMM y',
    'medium' => 'd MMM y',
    'short' => 'd/M/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'AM',
  'pmName' => 'PM',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'ar' => 'ʻAlapia',
    'cy' => 'Wale',
    'da' => 'Kenemaka',
    'de' => 'Kelemānia',
    'el' => 'Helene',
    'en' => 'Pelekānia',
    'en_au' => 'Pelekāne Nū Hōlani',
    'en_ca' => 'Pelekāne Kanakā',
    'en_gb' => 'Pelekānia Pekekāne',
    'en_us' => 'Pelekānia ʻAmelika',
    'es' => 'Paniolo',
    'fj' => 'Pīkī',
    'fr' => 'Palani',
    'fr_ca' => 'Palani Kanakā',
    'fr_ch' => 'Kuikilani',
    'ga' => 'ʻAiliki',
    'gsw' => 'Kuikilani Kelemānia',
    'haw' => 'ʻŌlelo Hawaiʻi',
    'he' => 'Hebera',
    'it' => 'ʻĪkālia',
    'ja' => 'Kepanī',
    'ko' => 'Kōlea',
    'la' => 'Lākina',
    'mi' => 'Māori',
    'nl' => 'Hōlani',
    'pt' => 'Pukikī',
    'pt_br' => 'Pukikī Palakila',
    'ru' => 'Lūkia',
    'sm' => 'Kāmoa',
    'sv' => 'Kuekene',
    'to' => 'Tonga',
    'ty' => 'Polapola',
    'und' => 'ʻIke ʻole ‘ia a kūpono ʻole paha ka ʻōlelo',
    'vi' => 'Wiekanama',
    'zh' => 'Pākē',
    'zh_hans' => 'Pākē Hoʻomaʻalahi ʻia',
    'zh_hant' => 'Pākē Kuʻuna',
  ),
  'territories' => 
  array (
    'au' => 'Nūhōlani',
    'ca' => 'Kanakā',
    'cn' => 'Kina',
    'de' => 'Kelemānia',
    'dk' => 'Kenemaka',
    'es' => 'Kepania',
    'fr' => 'Palani',
    'gb' => 'Aupuni Mōʻī Hui Pū ʻIa',
    'gr' => 'Helene',
    'ie' => 'ʻIlelani',
    'il' => 'ʻIseraʻela',
    'in' => 'ʻĪnia',
    'it' => 'ʻĪkālia',
    'jp' => 'Iāpana',
    'mx' => 'Mekiko',
    'nl' => 'Hōlani',
    'nz' => 'Aotearoa',
    'ph' => 'ʻĀina Pilipino',
    'ru' => 'Lūkia',
    'us' => 'ʻAmelika Hui Pū ʻIa',
  ),
  'pluralRules' => 
  array (
    0 => 'n==1',
    1 => 'true',
  ),
);
