<?php
/**
 * Locale data for 'sid_ET'.
 *
 * This file is automatically generated by yiic cldr command.
 *
 * Copyright © 1991-2007 Unicode, Inc. All rights reserved.
 * Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
 *
 * Copyright © 2008-2011 Yii Software LLC (http://www.yiiframework.com/license/)
 */
return array (
  'version' => '4123',
  'numberSymbols' => 
  array (
    'alias' => '',
    'decimal' => '.',
    'group' => ',',
    'list' => ';',
    'percentSign' => '%',
    'plusSign' => '+',
    'minusSign' => '-',
    'exponential' => 'E',
    'perMille' => '‰',
    'infinity' => '∞',
    'nan' => 'NaN',
  ),
  'decimalFormat' => '#,##0.###',
  'scientificFormat' => '#E0',
  'percentFormat' => '#,##0%',
  'currencyFormat' => '¤#,##0.00',
  'currencySymbols' => 
  array (
    'AUD' => 'AU$',
    'BRL' => 'R$',
    'CAD' => 'CA$',
    'CNY' => 'CN¥',
    'EUR' => '€',
    'GBP' => '£',
    'HKD' => 'HK$',
    'ILS' => '₪',
    'INR' => '₹',
    'JPY' => 'JP¥',
    'KRW' => '₩',
    'MXN' => 'MX$',
    'NZD' => 'NZ$',
    'THB' => '฿',
    'TWD' => 'NT$',
    'USD' => 'US$',
    'VND' => '₫',
    'XAF' => 'FCFA',
    'XCD' => 'EC$',
    'XOF' => 'CFA',
    'XPF' => 'CFPF',
    'ETB' => 'Br',
  ),
  'monthNames' => 
  array (
    'wide' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
    'abbreviated' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'monthNamesSA' => 
  array (
    'narrow' => 
    array (
      1 => '1',
      2 => '2',
      3 => '3',
      4 => '4',
      5 => '5',
      6 => '6',
      7 => '7',
      8 => '8',
      9 => '9',
      10 => '10',
      11 => '11',
      12 => '12',
    ),
  ),
  'weekDayNames' => 
  array (
    'wide' => 
    array (
      0 => 'Sambata',
      1 => 'Sanyo',
      2 => 'Maakisanyo',
      3 => 'Roowe',
      4 => 'Hamuse',
      5 => 'Arbe',
      6 => 'Qidaame',
    ),
    'abbreviated' => 
    array (
      0 => 'Sam',
      1 => 'San',
      2 => 'Mak',
      3 => 'Row',
      4 => 'Ham',
      5 => 'Arb',
      6 => 'Qid',
    ),
  ),
  'weekDayNamesSA' => 
  array (
    'narrow' => 
    array (
      0 => 'S',
      1 => 'S',
      2 => 'M',
      3 => 'R',
      4 => 'H',
      5 => 'A',
      6 => 'Q',
    ),
  ),
  'eraNames' => 
  array (
    'abbreviated' => 
    array (
      0 => 'YIA',
      1 => 'YIG',
    ),
    'wide' => 
    array (
      0 => 'YIA',
      1 => 'YIG',
    ),
    'narrow' => 
    array (
      0 => 'YIA',
      1 => 'YIG',
    ),
  ),
  'dateFormats' => 
  array (
    'full' => 'EEEE, MMMM dd, y',
    'long' => 'dd MMMM y',
    'medium' => 'dd-MMM-y',
    'short' => 'dd/MM/yy',
  ),
  'timeFormats' => 
  array (
    'full' => 'h:mm:ss a zzzz',
    'long' => 'h:mm:ss a z',
    'medium' => 'h:mm:ss a',
    'short' => 'h:mm a',
  ),
  'dateTimeFormat' => '{1} {0}',
  'amName' => 'soodo',
  'pmName' => 'hawwaro',
  'orientation' => 'ltr',
  'languages' => 
  array (
    'sid' => 'Sidaamu Afo',
  ),
  'scripts' => 
  array (
    'latn' => 'Latin',
  ),
  'territories' => 
  array (
    'et' => 'Itiyoophiya',
  ),
);
