<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Include archived content' => '',
    'Only private content' => '',
    'Only public content' => '',
    'Where I\'m involved' => '',
    'With file attachments' => '',
    'Back to stream' => 'Torna a l\'activitat',
    'Created by me' => 'Creat per mi',
    'Creation time' => 'Data de creació',
    'Filter' => 'Filtra',
    'Last update' => 'Data d\'actualització',
    'Load more' => 'Carregar més',
    'No matches with your selected filters!' => 'No hi ha coincidències amb els filtres seleccionats!',
    'Nothing here yet!' => 'No hi ha res aquí encara!',
    'The content has been archived.' => 'El contingut s\'ha arxivat.',
    'The content has been deleted.' => 'El contingut s\'ha eliminat.',
    'The content has been unarchived.' => 'El contingut s\'ha desarxivat.',
    'Your last edit state has been saved!' => 'La seua última  edició de l\'estat s\'ha gravat!',
];
