<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Weekly' => '',
    'Your weekly summary' => '',
    '<strong>E-Mail</strong> Summaries' => '<strong>E-posta</strong> Özetleri',
    'Activities' => 'Aktiviteler',
    'Daily' => 'Günlük',
    'E-Mail Summaries' => 'E-posta Özetleri',
    'E-Mail summaries are sent to inform you about recent activities in the network.' => 'E-posta özetleri sosyal ağınızdaki son aktiviteleri bilgilendirmek amacıyla size gönderilir.',
    'E-Mail summaries are sent to users to inform them about recent activities in your network.' => 'E-posta özetleri sosyal ağınızdaki son aktiviteleri kullanıcıları bilgilendirmek amacıyla kendilerine gönderilir.',
    'Exclude spaces below from the mail summary' => 'E-posta özetinden aşağıdaki sayfaları çıkar',
    'Hourly' => 'Saat başı',
    'Interval' => 'Süre',
    'Latest news' => 'Güncel haberler',
    'Never' => 'Asla',
    'On this page you can configure the contents and the interval of these e-mail updates.' => 'Bu sayfada, alacağınız e-posta güncellemeleri ile ilgili süreyi ayarlayabilirsiniz.',
    'On this page you can define the default behavior for your users. These settings can be overwritten by users in their account settings page.' => 'Bu sayfada kullanıcılarınızın varsayılan ayarlarını belirleyebilirsiniz. Bu ayarlar, kullanıcılarınızın hesap ayarları bölümünde bundan sonra geçerli olacaktır.',
    'Only include spaces below to the mail summary' => 'E-posta özeti yalnızca aşağıdaki sayfaları içersin',
    'Reset to defaults' => 'Varsayılan ayarlara geri dön',
    'Spaces' => 'Sayfalar',
    'You will only receive an e-mail if there is something new.' => 'Yalnızca yeni bir işlem olduğunda e-posta ile bilgilendirileceksiniz.',
    'Your daily summary' => 'Günlük özetiniz',
];
