<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Hide my year of birth' => 'Dölj min födelsedag',
    'Save and close' => 'Spara och stäng',
    'Your firstname' => 'Ditt förnamn',
    'Your lastname' => 'Ditt efternamn',
    'Your mobile phone number' => 'Ditt mobilnummer',
    'Drag a photo here or click to browse your files' => '',
    'Howdy <strong>%firstname%</strong>, thank you for using %community%.' => '',
    'You are the first user here... Yehaaa! Be a shining example and complete your profile,<br>so that future users know who is the top dog here and to whom they can turn to if they have questions.' => '',
    'Your phone number at work' => '',
    'Your skills, knowledge and experience (comma seperated)' => '',
    'Your title or position' => '',
];
