<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Upload</strong> error' => 'خطلای <strong>بارگذاری</strong>',
    'Close' => 'بستن',
    'Could not find requested file!' => 'فایل درخواست‌شده یافت نشد!',
    'Could not upload File:' => 'فایل بارگذاری نشد:',
    'Created by:' => 'ساخته‌شده توسط:',
    'Download' => 'بارگيري',
    'Insufficient permissions!' => 'غیر مجاز!',
    'Invalid Mime-Type' => 'Mime-Type نامعتبر',
    'Upload files' => 'بارگذاری فایل‌ها',
    '<strong>Open</strong> file' => '',
    'Could not find requested file variant!' => '',
    'Double file extensions are not allowed!' => '',
    'File {fileName} could not be uploaded!' => '',
    'Invalid file name detected!' => '',
    'Last update by:' => '',
    'Size:' => '',
    'Sorry, you can only upload up to {n,plural,=1{# file} other{# files}} at once.' => '',
    'The uploaded image is not a squared.' => '',
    'This upload field only allows a maximum of {n,plural,=1{# file} other{# files}}.' => '',
];
