<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> post deletion' => '<strong>تأكيد</strong> رغبتك في الحذف',
    '<strong>Permalink</strong> to this post' => 'الوصلة الدائمة لهذه المحتويات',
    'Add a member to notify' => 'إضافة عضو للتنبيه',
    'Archived' => 'أرشيف',
    'Back to stream' => 'العودة للمحتويات',
    'Cancel' => 'إلغاء',
    'Could not find requested content!' => 'لم يتم إيجاد المحتويات المطلوبة!',
    'Could not load requested object!' => 'لم نتمكن من عرض الشيء المطلوب!',
    'Created by me' => 'التي كتبتها أنا',
    'Creation time' => 'حسب وقت النشر',
    'Delete' => 'حذف',
    'Do you really want to delete this post? All likes and comments will be lost!' => 'هل انت متأكد من رغبتك في حذف هذه المحتويات؟ جميع الردود و نقاط الإعجاب ستختفي!',
    'Edit' => 'تحرير',
    'Filter' => 'تصفية',
    'Last update' => 'حسب آخر تعديل',
    'Make private' => 'إجعله خاص',
    'Make public' => 'إجعله عام',
    'Move to archive' => 'نقل للأرشيف',
    'No matches with your selected filters!' => 'لم يتم إيجاد نتائج مطابقة للبحث',
    'Nothing here yet!' => 'لا يوجد شيء هنا بعد!',
    'Notify members' => 'إرسال تنبيه للأعضاء',
    'Permalink' => 'وصلة دائمة',
    'Pinned' => 'مثبت',
    'Public' => 'عام',
    'Submit' => 'أرسل',
    'Turn off notifications' => 'إلغاء التنبيهات',
    'Turn on notifications' => 'تفعيل التنبيهات',
    'Unarchive' => 'إلغاء وضع الأرشيف',
    'in' => 'في',
    '<strong>Move</strong> content' => '',
    'Cancel Edit' => '',
    'Content' => '',
    'Content Tag with invalid contentcontainer_id assigned.' => '',
    'Content has been moved to {spacename}' => '',
    'Content visibility' => '',
    'Could not delete content!' => '',
    'Could not delete content: Access denied!' => '',
    'Include archived content' => '',
    'Invalid content id given!' => '',
    'Invalid request method!' => '',
    'Invalid space selection.' => '',
    'Load more' => '',
    'Maximum number of pinned items reached!

You can pin to top only two items at once.
To however pin this item, unpin another before!' => '',
    'Move content' => '',
    'None' => '',
    'Only private content' => '',
    'Only public content' => '',
    'Pin to top' => '',
    'Tag' => '',
    'Target Space' => '',
    'The author of this content is not allowed to create private content within the selected space.' => '',
    'The author of this content is not allowed to create public content within the selected space.' => '',
    'The content can\'t be moved to its current space.' => '',
    'The content has been archived.' => '',
    'The content has been deleted.' => '',
    'The content has been unarchived.' => '',
    'The given name is already in use.' => '',
    'The module {moduleName} is not enabled on the selected target space.' => '',
    'This action is disabled!' => '',
    'This content type can\'t be moved due to a missing module-id setting.' => '',
    'This content type can\'t be moved.' => '',
    'This space is archived.' => '',
    'This space is not visible!' => '',
    'Topics' => '',
    'Unpin' => '',
    'Updated' => '',
    'Where I\'m involved' => '',
    'With file attachments' => '',
    'You do not have the permission to move this content to the given space.' => '',
    'You do not have the permission to move this content.' => '',
    'Your last edit state has been saved!' => '',
];
