<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Administration</strong> menu' => '<strong>Administrations</strong> meny',
    'About' => 'Om',
    'Administration' => 'Administration',
    'Advanced' => 'Avancerat',
    'Appearance' => 'Utseende',
    'Approval' => 'Godkännande',
    'Authentication' => 'Autentisering',
    'Back to overview' => 'Tillbaka till översikt',
    'Back to user overview' => 'Tillbaka till användaröversikten',
    'Basic' => 'Grund',
    'Caching' => 'Caching',
    'Files' => 'Filer',
    'General' => 'Allmänt',
    'Groups' => 'Grupper',
    'Information' => 'Information',
    'Invite' => 'Inbjudan',
    'Invited by' => 'Inbjuden av',
    'Logs' => 'Loggar',
    'Modules' => 'Moduler',
    'Notifications' => 'Notiser',
    'OEmbed' => 'OEmbed',
    'Proxy' => 'Proxy',
    'Security' => 'Säkerhet',
    'Settings' => 'Inställningar',
    'Spaces' => 'Nätverk',
    'Statistics' => 'Statistik',
    'User posts' => 'Användarinlägg',
    'Userprofiles' => 'Användarprofiler',
    'Users' => 'Användare',
    '<strong>Module </strong> administration' => '',
    '<strong>Warning</strong> incomplete setup!' => '',
    'Admin' => '',
    'Administrative group' => '',
    'Base URL needs to begin with http:// or https://' => '',
    'Cronjobs' => '',
    'Design' => '',
    'Groups (Note: The Administrator group of this user can\'t be managed with your permissions)' => '',
    'Logging' => '',
    'Mailing' => '',
    'OEmbed providers' => '',
    'Open documentation' => '',
    'Pending user registrations' => '',
    'Permissions' => '',
    'Self test' => '',
    'Sign up' => '',
    'The cron job for the background jobs (queue) does not seem to work properly.' => '',
    'The cron job for the regular tasks (cron) does not seem to work properly.' => '',
];
