<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Name' => '',
    'Basic Settings' => 'Configurações básicas',
    'Change Email' => 'Mudar e-mail',
    'Change Password' => 'Mudar senha',
    'Confirm new password' => 'Confirmar nova senha',
    'Connect account' => 'Conectar conta',
    'Connected Accounts' => 'Contas Conectadas',
    'Connected accounts' => 'Contas conectadas',
    'Crop profile background' => 'Cortar o fundo do perfil',
    'Crop profile image' => 'Cortar imagem do perfil',
    'Current Password' => 'Senha Atual',
    'Currently in use' => 'Atualmente em uso',
    'Delete' => 'Apagar',
    'Delete Account' => 'Apagar Conta',
    'Delete profile image' => 'Apagar imagem do perfil',
    'Disconnect account' => 'Desconectar conta',
    'E-Mail is already in use! - Try forgot password.' => 'E-mail já cadastrado! - Tente \'Esqueceu a senha\'.',
    'Email' => 'E-mail',
    'General' => 'Geral',
    'Here you can connect to external service provider for using external services like a single sign on authentication.' => 'Aqui você pode se conectar ao provedor de serviço externo para usar serviços externos como uma autenticação única.',
    'Missing E-Mail Attribute from AuthClient.' => 'Faltando atributo de e-mail do AuthClient.',
    'Missing ID AuthClient Attribute from AuthClient.' => 'Faltando atributo ID do AuthClient.',
    'Modules' => 'Módulos',
    'My Account' => 'Minha conta',
    'New password' => 'Nova senha',
    'No users found.' => 'Nenhum usuário encontrado.',
    'Notifications' => 'Notificações',
    'Password' => 'Senha',
    'Profile' => 'Perfil',
    'Security' => 'Segurança',
    'Settings' => 'Configurações',
    'Sign in' => 'Entrar',
    'Sign in / up' => 'Entrar / Cadastrar',
    'Unknown user status!' => 'Status de usuário desconhecido!',
    'Upload profile banner' => 'Transferir banner de perfil',
    'Upload profile image' => 'Transferir imagem de perfil',
    'User' => 'Usuário',
    'User with the same email already exists but isn\'t linked to you. Login using your email first to link it.' => 'Um usuário com o mesmo e-mail já existe, mas não está vinculado a você. Faça login usando seu e-mail primeiro para vinculá-lo.',
    'You\'re not registered.' => 'Você não está registrado.',
    'Your account is disabled!' => 'Sua conta está desabilitada!',
    'Your account is not approved yet!' => 'Sua conta não foi aprovada ainda!',
    'Your new password must not be equal your current password!' => 'Sua nova senha não pode ser igual a senha atual',
    'or' => 'ou',
];
