<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Join</strong> the network' => '',
    'Please login with your username/email and password.' => '',
    '<strong>Please</strong> sign in' => '<strong>Por favor</strong> faça o login',
    '<strong>Sign</strong> up' => '<strong>Crie</strong> sua conta',
    'Create a new one.' => 'Criar uma nova',
    'Don\'t have an account? Join the network by entering your e-mail address.' => 'Não tem uma conta? Junte-se à rede, digitando o seu endereço de e-mail.',
    'Forgot your password?' => 'Esqueceu sua senha?',
    'If you\'re already a member, please login with your username/email and password.' => 'Se você já é membro, por favor, faça o login com seu nome de usuário ou e-mail e senha.',
    'Login' => 'Entrar',
    'Register' => 'Cadastrar',
    'Remember me' => 'Lembrar de mim',
    'Sign in' => 'Entrar',
    'email' => 'e-mail',
    'password' => 'senha',
    'username or email' => 'nome do usuário ou e-mail',
];
