<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '%moduleName% - Set as default module' => '%moduleName% - Задайте като модул по подразбиране',
    '<strong>Module</strong> details' => 'Детайли за <strong>Модул</strong>',
    'Activated' => 'Активиран',
    'Always activated' => 'Винаги активиран',
    'Are you sure? *ALL* module data will be lost!' => 'Сигурни ли сте? *ВСИЧКИ* данни от модула ще бъдат загубени!',
    'Are you sure? *ALL* module related data and files will be lost!' => 'Сигурни ли сте? *ВСИЧКИ* данни и файловете, свързани с модула, ще бъдат загубени!',
    'Close' => 'Затваряне',
    'Configure' => 'Настройване',
    'Could not find requested module!' => 'Заявеният модел не може да бъде намерен!',
    'Deactivated' => 'Деактивиран',
    'Disable' => 'Деактивиране',
    'Enable' => 'Активиране',
    'Enable module...' => 'Активиране на модул...',
    'Here you can choose whether or not a module should be automatically activated on a space or user profile. If the module should be activated, choose "always activated".' => 'Тук можете да изберете дали даден модул да се активира автоматично в раздела или потребителският профил. Ако модулът трябва да бъде активиран, изберете "Винаги активиран".',
    'Legacy' => 'Наследство',
    'Module path %path% is not writeable!' => 'Пътят на модула %path% не позволява записване!',
    'Modules extend the functionality of HumHub. Here you can install and manage modules from the HumHub Marketplace.' => 'Модулите разширяват функционалността на HumHub. Тук можете да инсталирате и управлявате модули от HumHub Marketplace.',
    'More info' => 'Повече информация',
    'No modules installed yet. Install some to enhance the functionality!' => 'Все още няма инсталирани модули. Инсталирайте модул, за да подобрите функционалността!',
    'Not maintained or maintenance is about to be discontinued.' => 'Не се поддържа или поддръжката е на път да бъде прекратена.',
    'Save' => 'Запази',
    'Set as default' => 'Сложи по подразбиране',
    'Spaces' => 'Раздели',
    'Uninstall' => 'Деинсталиране',
    'User Profiles' => 'Потребителски Профили',
    'Version:' => 'Версия:',
    'This module doesn\'t provide further information.' => '',
];
