<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Enter your password to continue' => '',
  '<strong>Delete</strong> account' => '<strong>Smazat</strong> účet',
  'Are you sure, that you want to delete your account?<br />All your published content will be removed! ' => 'Jste si opravdu jistí, že chcete smazat svůj účet?<br />Všechny vaše příspěvky budou tímto smazány!',
  'Delete account' => 'Smazat účet',
  'Sorry, as an owner of a workspace you are not able to delete your account!<br />Please assign another owner or delete them.' => 'Je nám líto, ale jelikož jste vlastníkem alespoň jednoho prostoru, nemůžete nyní smazat svůj účet.<br />Předejte nejprve vlastnictví prostoru jinému uživateli, nebo prostor smažte.',
);
