<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Database</strong> Configuration' => '<strong>Настройки</strong> базы данных',
    'Below you have to enter your database connection details. If you’re not sure about these, please contact your system administrator.' => 'Ниже вы должны ввести свои данные для подключения к базе данных. Если вы не уверены в них, пожалуйста, обратитесь к системному администратору.',
    'Hostname of your MySQL Database Server (e.g. localhost if MySQL is running on the same machine)' => 'Имя хоста для сервера базы данных MySQL (например, localhost, если MySQL работает на той же машине)',
    'Initializing database...' => 'Инициализация базы данных ...',
    'Next' => 'Далее',
    'Ohh, something went wrong!' => 'Ох, что-то пошло не так!',
    'The name of the database you want to run HumHub in.' => 'Имя базы данных.',
    'Your MySQL password.' => 'Пароль MySQL',
    'Your MySQL username' => 'Имя пользователя MySQL',
];
