<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administrace</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hurá!</strong> To je vše.',
  '<strong>Modules</strong>' => '<strong>Modululy</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Jako administrátor můžete celou platformu řídit odsud.<br><br>Kromě modulů, které zde nebudeme rozebírat do detailů, každý má krátký popis jinde.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Aktuálně se nacházíte v panelu nástrojů. Odsud můžete přistupovat k online obchodu HumHubu, ze kterého můžete průběžně instalovat stále narůstající počet nástrojů.<br><br>Jak jsme již zmínili, nástroje zvýší počet funkcí dostupných pro váš prostor.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Naučil(a) jste se všechno o nejdůležitějších vlastnostech a nastavení, které je již nastaveno tak, abyste mohl(a) platformu začít používat.<br><br>Doufáme, že si vy i všichni budoucí uživatelé vychutnáte používání této stránky. Těšíme se na jakékoli podněty a podporu nabídnutou našemu projektu. Nebojte se nás kontaktovat prostřednictvím www.humhub.org.<br><br>Zachovejte nám přízeň. :-)',
);
