<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Manage</strong> spaces' => 'Gestion des <strong>espaces</strong>',
    'Add new space' => 'Ajouter un espace',
    'Change owner' => 'Changer de propriétaire',
    'Default Content Visiblity' => 'Visibilité des contenus par défaut',
    'Default Join Policy' => 'Politique d\'adhésion par défaut',
    'Default Visibility' => 'Visibilité par défaut',
    'Default space' => 'Espace par défaut',
    'Here you can define your default settings for new spaces. These settings can be overwritten for each individual space.' => 'Ici vous pouvez définir vos paramètres par défaut pour les nouveaux espaces. Ces paramètres peuvent être remplacés pour chaque espace individuellement.',
    'Invalid space' => 'Espace invalide',
    'Manage members' => 'Gérer les membres',
    'Manage modules' => 'Gérer les modules',
    'Open space' => 'Ouvrir cet espace',
    'Overview' => 'Vue d\'ensemble',
    'Search by name, description, id or owner.' => 'Rechercher par nom, description, identifiant ou propriétaire.',
    'Settings' => 'Paramètres',
    'Space Settings' => 'Paramètres de l\'espace',
    'Spaces' => 'Espaces',
    'This overview contains a list of each space with actions to view, edit and delete spaces.' => 'Cette vue d\'ensemble contient une liste de chaque espace avec des actions pour afficher, modifier et supprimer des espaces.',
    'Default Permissions' => '',
    'Default Space Permissions' => '',
    'Default Space(s)' => '',
    'These options allow you to set the default permissions for all Spaces. Authorized users are able individualize these for each Space. Further entries are added with the installation of new modules.' => '',
    'By using user roles, you can create different permission groups within a Space. These can also be individualized by authorized users for each and every Space and are only relevant for that specific Space.' => '',
    'Update Space memberships also for existing members.' => '',
];
