<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' Invite and request' => ' Einladen und anfragen',
  '<strong>Create</strong> new space' => '<strong>Neuen Raum</strong> erstellen',
  'Also non-members can see this<br>space, but have no access' => 'Auch Nicht-Mitglieder können diesen<br />Raum sehen, haben aber keinen Zugang',
  'Create' => 'Erstellen',
  'Every user can enter your space<br>without your approval' => 'Jeder Benutzer kann Ihren Raum<br />ohne Ihre Genehmigung betreten',
  'Everyone can enter' => 'Jeder kann eintreten',
  'For everyone' => 'Für jeden',
  'How you want to name your space?' => 'Wir wollen Sie Ihren Raum benennen?',
  'Invite and request' => 'Einladen und anfragen',
  'Only by invite' => 'Nur durch Einladung',
  'Please write down a small description for other users.' => 'Bitte schreiben Sie eine kurze Beschreibung für andere Benutzer.',
  'Private (Invisible)' => 'Privat (unsichtbar)',
  'Public (Visible)' => 'Öffentlich (sichtbar)',
  'This space will be hidden<br>for all non-members' => 'Dieser Raum wird für<br />alle Nicht-Mitglieder versteckt sein',
  'Users can also apply for a<br>membership to this space' => 'Benutzer können sie Mitgliedschaft<br />für diesen Raum beantragen',
  'Users can be only added<br>by invitation' => 'Benutzer können nur durch<br />Einladung hinzugefügt werden',
  'space description' => 'Raum-Beschreibung',
  'space name' => 'Raum-Name',
);
