<?php
return [
  '<strong>Administration</strong>' => '<strong>Administration</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hurra!</strong> Det var alt for nu.',
  '<strong>Modules</strong>' => '<strong>Moduler</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Som administrator kan du administrere hele platformen herfra.<br><br> Bortset fra modulerne vil vi ikke gå i detaljer med hvert punkt her, da hvert punkt har sin egen korte beskrivelse andetsteds.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Du befinder dig i øjeblikket i værktøjsmenuen. Herfra kan du få adgang til HumHubs online markedsplads, hvor du kan installere et stadigt stigende antal værktøjer on-the-fly.<br><br>Som allerede nævnt øger værktøjerne de funktioner, der er tilgængelige for dit rum.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Du har nu lært om alle de vigtigste funktioner og indstillinger og er klar til at begynde at bruge platformen.<br><br>We hope you and all future users will enjoy using this site. Vi ser frem til alle forslag eller støtte, som du ønsker at tilbyde til vores projekt. Du er velkommen til at kontakte os via www.humhub.org.<br><br>Stay tuned. :-)',
];
