<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Most recent</strong> activities' => '<strong>Seneste</strong> aktiviteter',
    '<strong>Posts</strong>' => '<strong>Opslag</strong>',
    '<strong>Profile Guide</strong>' => '<strong>Profil Guide</strong>',
    '<strong>Space</strong>' => '<strong>Side</strong>',
    '<strong>Space</strong> members' => '<strong>Side</strong> medlemmer',
    '<strong>Space</strong> navigation menu' => '<strong>Side</strong> navigations menu',
    '<strong>Space</strong> preferences' => '<strong>Side</strong> præferencer',
    '<strong>Writing</strong> posts' => '<strong>Skrive</strong> opslag',
    '<strong>Yay! You\'re done.</strong>' => '<strong>Yay! Du er færdig.</strong>',
    'All users who are a member of this space will be displayed here.<br /><br />New members can be added by anyone who has been given access rights by the admin.' => 'Alle bruger som er medlem af denne side vil blive vist her.<br /><br />Nye medlemmer kan blive tilføjet af dem der har fået adgangstilladelse fra sidens admin.',
    'New posts can be written and posted here.' => 'Nye opslag kan blive skrevet og sendt her.',
    'Once you have joined or created a new space you can work on projects, discuss topics or just share information with other users.<br><br>There are various tools to personalize a space, thereby making the work process more productive.' => 'Når du først har tilsluttet dig eller tilføjet en ny side hvor du kan arbejde, diskuter hovedpunkter eller del information med andre brugere.<br><br>Der er forskellige værktøjer til at personliggøre en side, hvorefter du laver arbejdsprocessen mere produktiv.',
    'That\'s it for the space guide.<br><br>To carry on with the user profile guide, click here: ' => 'Det var det for denne gang med side guiden.<br><br>For at fortsætte til brugerprofil guiden, tryk her:',
    'This is where you can navigate the space – where you find which modules are active or available for the particular space you are currently in. These could be polls, tasks or notes for example.<br><br>Only the space admin can manage the space\'s modules.' => 'Dette er hvor du kan navigere siden - Hvor du kan finde hvilke moduler er aktive eller tilgængelige for en bestemt side du er i. Dette kan for eksempel være afstemninger, opgaver eller noter.<br><br>Kun sidens admin kan administrere sidens moduler.',
    'This menu is only visible for space admins. Here you can manage your space settings, add/block members and activate/deactivate tools for this space.' => 'Denne menu er kun synlig for sidens admins. Her kan du administrere din side, tilføje/blokere brugere og aktivere/deaktivere værtøjer for denne side.',
    'To keep you up to date, other users\' most recent activities in this space will be displayed here.' => 'For at du er opdateret, vil andre brugeres aktiviteter på denne side vil blive vist her.',
    'Yours, and other users\' posts will appear here.<br><br>These can then be liked or commented on.' => 'Din, og andre brugeres opslag vil blive vist her.<br><br>Disse kan også blive syntes godt om eller kommenteret på.',
];
