<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Space</strong> Modules' => '<strong>Espaço</strong> Módulos',
  'Activated' => 'Ativado',
  'Are you sure? *ALL* module data for this space will be deleted!' => 'Você tem certeza? *TODAS* as informações do módulo deste espaço serão deletadas!',
  'Configure' => 'Configurar',
  'Currently there are no modules available for this space!' => 'Não há módulos instalados neste espaço',
  'Disable' => 'Desabilitar',
  'Enable' => 'Habilitar',
  'Enhance this space with modules.' => 'Melhore este espaço com módulos.',
);
