<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Send invite' => '',
    'Actions' => 'اعمال',
    'Add new user' => 'اضافه کردن کاربر جدید',
    'Group Manager' => 'مدیریت گروه ها',
    'Last login' => 'آخرین ورود',
    'Overview' => 'بررسی اجمالی',
    'Settings' => 'تنطیمات',
    'This overview contains a list of each registered user with actions to view, edit and delete users.' => 'این لیست دیدی کلی درباره کاربر های عضو شده می دهد',
    'Users' => 'کاربران',
    'never' => 'هرگز',
];
