<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Database migration results:' => '',
    'Never' => '',
    'Queue successfully cleared.' => '',
    'Search index rebuild in progress.' => '',
    'The current main HumHub database name is ' => '',
    '<strong>CronJob</strong> Status' => '<strong>Cronジョブ</strong> ステータス',
    '<strong>Queue</strong> Status' => '<strong>キュー</strong> ステータス',
    'About HumHub' => 'HumHubについて',
    'Background Jobs' => 'バックグラウンドのジョブ',
    'Database' => 'データベース',
    'Delayed' => '遅延',
    'Done' => '実行済み',
    'Driver' => 'ドライバ',
    'Last run (daily):' => '日時Cronの最終実行',
    'Last run (hourly):' => '毎時Cronの最終実行',
    'Logging' => 'ログ',
    'Please refer to the documentation to setup the cronjobs and queue workers.' => 'Cronジョブとキューの設定については、マニュアルを参照してください。',
    'Prerequisites' => '前提条件',
    'Reserved' => '予約',
    'Waiting' => '待機',
];
