<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administrazioa</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Aupa!</strong> Hori da dena oraingoz.',
  '<strong>Modules</strong>' => '<strong>Moduluak</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Admin gisa, plataforma osoa kudeatu dezakezu hemendik.<br><br>Moduluak alde batera utzita, hemen ez dugu xehetasunez aztertuko puntu bakoitza, bakoitzak bere deskribapen laburra baitu beste nonbait.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Orain tresnen menuan zaude. Hemendik HumHub online merkatura sar zaitezke, eta gero eta tresna gehiago instalatu hegan egiteko. <br><br>Esan bezala, tresnek zure espazioaren ezaugarriak handitzen dituzte.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Orain ezagutu dituzue ezaugarri eta konfigurazio garrantzitsuenak eta prest zaudete plataforma erabiltzen hasteko. <br><br>Espero dugu zuk eta etorkizuneko erabiltzaile guztiek gozatzea gune hau erabiltzen. Gure proiekturako edozein iradokizun edo laguntza jasotzeko irrikan gaude. Jar zaitez gurekin harremanetan www.humhub.org. <br><br>Jarraitu afinatzen: -)',
);
