<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add purchased module by licence key' => 'Vložit koupený modul pomocí licenčního klíče',
    'All modules are up to date!' => 'Všechny moduly jsou aktuální!',
    'Available updates' => 'Dostupné aktualizace',
    'Browse online' => 'Procházet online',
    'Buy (%price%)' => 'Koupit (%price%)',
    'Could not extract module!' => 'Nebylo možné rozbalit modul!',
    'Download of module failed!' => 'Nebylo možné stáhnout modul!',
    'Install' => 'Nainstalovat',
    'Installed' => 'Nainstalováno',
    'Installed version:' => 'Nainstalovaná verze:',
    'Installing module...' => 'Instaluji modul...',
    'Latest compatible Version:' => 'Poslední kompatibilní verze:',
    'Latest compatible version:' => 'Poslední kompatibilní verze:',
    'Latest version:' => 'Poslední verze:',
    'Licence Key:' => 'Licenční klíč:',
    'Module directory %modulePath% is not writeable!' => 'Adresář pro ukládání modulů %modulePath% není zapisovatelný!',
    'Module download failed! (%error%)' => 'Nebylo možné stáhnout modul! (%error%)',
    'More info' => 'Více informací',
    'No compatible module version found!' => 'Nebyla nalezena žádná kompatibilní verze modulu!',
    'No modules found!' => 'Žádné moduly nenalezeny!',
    'No purchased modules found!' => 'Nebyly nalezeny žádné zakoupené moduly.',
    'Ok' => 'Ok',
    'Purchases' => 'Zakoupené',
    'Register' => 'Registrovat',
    'Search' => 'Hledat',
    'Third-party' => 'Třetích stran',
    'Third-party disclaimer' => 'Odmítnutí odpovědnosti třetích stran',
    'Update' => 'Aktualizovat',
    'Updating module...' => 'Aktualizuji modul...',
    'Version:' => 'Verze:',
    'search for available modules online' => 'vyhledat dostupné moduly online',
    '
Module successfully disabled!
' => '',
    '
Module successfully enabled!
' => '',
    '
No active Professional Edition license found!
' => '',
    '
PROFESSIONAL EDITION
' => '',
    '
The license could not be activated:
' => '',
    '
The license was successfully activated!

' => '',
    '
The license was successfully removed!

' => '',
    '--- Disable module: {moduleId} ---

' => '',
    '--- Enable module: {moduleId} ---

' => '',
    '<strong>Activate</strong> your Professional Edition' => '',
    'All {moduleId} module content will be deleted. Continue?' => '',
    'Buy' => '',
    'Could not connect to licence server!' => '',
    'Could not remove old module path!' => '',
    'Could not update licence. Error: ' => '',
    'Edit licence' => '',
    'If this Module is additionally marked as <strong>"Community"</strong> it is neither tested nor monitored by the HumHub project team.' => '',
    'Include Community Modules' => '',
    'Include beta updates' => '',
    'Licence key' => '',
    'Licenced for max. {number} users.' => '',
    'Licenced to:' => '',
    'Marketplace' => '',
    'Max. users:' => '',
    'Module not found or activated!
' => '',
    'Module not found!
' => '',
    'No license key? Find out more about the {pro} or contact us.' => '',
    'Professional Edition is activated!' => '',
    'Remove licence key' => '',
    'Save and update' => '',
    'The HumHub project does not guarantee the functionality, quality or the continuous development of this Module.' => '',
    'Third-party Modules are not covered by Professional Edition agreements.' => '',
    'This Module was developed by a third-party.' => '',
    'Upgrade to Professional Edition' => '',
    'View Changelog' => '',
];
