<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Administration</strong> menu' => '<strong>Administration</strong> menu',
    'About' => 'Om',
    'Admin' => 'Admin',
    'Administration' => 'Administration',
    'Authentication' => 'Godkendelse',
    'Back to overview' => 'Tilbage til oversigten',
    'Basic' => 'Basis',
    'Caching' => 'Caching',
    'Design' => 'Design',
    'Files' => 'Filer',
    'General' => 'Generelt',
    'Groups' => 'Grupper',
    'Invite' => 'Inviter',
    'Logging' => 'Logging',
    'Mailing' => 'Mailing',
    'Modules' => 'Moduler',
    'Notifications' => 'Notifikationer',
    'Proxy' => 'Proxy',
    'Security' => 'Sikkerhed',
    'Settings' => 'Indstillinger',
    'Sign up' => 'Opret',
    'Spaces' => 'Sider',
    'Statistics' => 'Statistik',
    'Users' => 'Brugere',
    '<strong>Module </strong> administration' => '',
    '<strong>Warning</strong> incomplete setup!' => '',
    'Administrative group' => '',
    'Advanced' => '',
    'Appearance' => '',
    'Approval' => '',
    'Back to user overview' => '',
    'Base URL needs to begin with http:// or https://' => '',
    'Cronjobs' => '',
    'Groups (Note: The Administrator group of this user can\'t be managed with your permissions)' => '',
    'Information' => '',
    'Invited by' => '',
    'Logs' => '',
    'OEmbed' => '',
    'OEmbed providers' => '',
    'Open documentation' => '',
    'Pending user registrations' => '',
    'Permissions' => '',
    'Self test' => '',
    'The cron job for the background jobs (queue) does not seem to work properly.' => '',
    'The cron job for the regular tasks (cron) does not seem to work properly.' => '',
    'User posts' => '',
    'Userprofiles' => '',
];
