<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Friendship' => '',
    'New users will automatically be added to these space(s).' => '',
    'Wall entry layout' => '',
    '<strong>Confirm</strong> image deleting' => '<strong>Bekræft</strong> billede sletning',
    'Cancel' => 'Afbryd',
    'Dashboard' => 'Dashboard',
    'Delete' => 'Slet',
    'E.g. http://example.com/humhub' => 'E.g. http://example.com/humhub',
    'Save' => 'Gem',
    'You\'re using no logo at the moment. Upload your logo now.' => 'Du bruger i øjeblikket ikke et logo. Upload dit logo nu.',
];
