<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Disclaimer' => '',
    '<strong>Modules</strong> directory' => '<strong>Modul</strong> bibliotek',
    'Buy (%price%)' => 'Køb (%price%)',
    'Install' => 'Installer',
    'Installing module...' => 'Installerer modul...',
    'Latest compatible version:' => 'Seneste kompatible version:',
    'Latest version:' => 'Seneste version:',
    'Licence Key:' => 'Licens Nøgle:',
    'More info' => 'Mere info',
    'No compatible module version found!' => 'Ingen kompatible modulversion er fundet!',
];
