<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>CronJob</strong> Status' => 'Stan <strong>CronJob</strong>',
    '<strong>Queue</strong> Status' => 'Stan <strong>Kolejki</strong>',
    'About HumHub' => 'O HumHub',
    'Background Jobs' => 'Zadania w tle',
    'Checking HumHub software prerequisites.' => 'Sprawdzanie wstępnych wymagań oprogramowania HumHub.',
    'Currently installed version: %currentVersion%' => 'Obecnie zainstalowana wersja: %currentVersion%',
    'Database' => 'Baza danych',
    'Database migration results:' => 'Wynik migracji bazy danych:',
    'Delayed' => 'Opóźnione',
    'Displaying {count} entries per page.' => 'Pokazano {count} wpisów na stronę.',
    'Done' => 'Zakończone',
    'Driver' => 'Sterownik',
    'Flush entries' => 'Wyczyść wpisy',
    'HumHub is currently in debug mode. Disable it when running on production!' => 'HumHub jest w trybie debugowania. Wyłącz go gdy udostępnisz stronę użytkownikom!',
    'Last run (daily):' => 'Ostatnie uruchomienie (dzienne):',
    'Last run (hourly):' => 'Ostatnie uruchomienie (godzinowe):',
    'Licences' => 'Licencje',
    'Logging' => 'Logowanie',
    'Never' => 'Nigdy',
    'Please refer to the documentation to setup the cronjobs and queue workers.' => 'Proszę odnieść się do dokumentacji w celu ustawienia zadań cron i kolejki działań.',
    'Prerequisites' => 'Wymagania',
    'Queue successfully cleared.' => 'Kolejka wyczyszczona prawidłowo',
    'Re-Run tests' => 'Uruchom ponownie testy ',
    'Reserved' => 'Zarezerwowane',
    'Search index rebuild in progress.' => 'Indeks szukania przebudowany prawidłowo.',
    'See installation manual for more details.' => 'Więcej informacji znajdziesz w instrukcji instalacji.',
    'The current main HumHub database name is ' => 'Obecna nazwa głównej bazy danych HumHub to:',
    'There is a new update available! (Latest version: %version%)' => 'Dostępna jest aktualizacja! (Najnowsza wersja: %version%)',
    'This HumHub installation is up to date!' => 'Ta instalacja HumHuba jest aktualna!',
    'Total {count} entries found.' => 'W sumie znaleziono {count} wpisów.',
    'Waiting' => 'Oczekiwanie',
];
