<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Comma separated list. Leave empty to allow all.' => 'Lista elementów oddzielonych przecinkiem (csv). Pozostaw pustą aby dopuścić wszystkie.',
    'Current Image Library: {currentImageLibrary}' => 'Obecna biblioteka graficzna: {currentImageLibrary}',
    'If not set, height will default to 200px.' => 'Jeśli puste to domyślna wysokość wyniesie 200px.',
    'If not set, width will default to 200px.' => 'Jeśli puste to domyślna szerokość wyniesie 200px.',
    'PHP reported a maximum of {maxUploadSize} MB' => 'PHP zgłasza maksimum {maxUploadSize} MB',
    'Save' => 'Zapisz ',
];
