<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'General' => '',
    'LDAP' => '',
    'Min value is 20 seconds. If not set, session will timeout after 1400 seconds (24 minutes) regardless of activity (default session timeout)' => '最小值为20秒。如果没有设置，会话将会在1400秒（24分钟）无活动后超时（默认会话超时）',
    'Only applicable when limited access for non-authenticated users is enabled. Only affects new users.' => '仅适用于非授权用户的有限访问启用时。只影响新用户。',
    'Save' => '保存',
    'Visible for members only' => '仅对成员可见',
    'Visible for members+guests' => '对成员或游客都可见',
];
