<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Comma separated list. Leave empty to allow all.' => '逗号分隔列表。留空允许所有。',
  'Comma separated list. Leave empty to show file list for all objects on wall.' => '逗号分隔列表。留空允许所有对象墙的文件列表。',
  'If not set, height will default to 200px.' => '如果没有设置，高度默认为200像素',
  'If not set, width will default to 200px.' => '如果没有设置，宽度默认为200像素',
  '<strong>File</strong> settings' => '<strong>文件</strong> 设置',
  'Current Image Libary: {currentImageLibary}' => '当前图片库：{currentImageLibary}',
  'PHP reported a maximum of {maxUploadSize} MB' => 'PHP最大上传大小 {maxUploadSize} MB',
  'Save' => '保 存',
);
