<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Account</strong> settings' => '<strong>Account</strong> instellingen',
    '<strong>Confirm</strong></strong> your new email address' => '<strong>Bevestig</strong> je nieuwe e-mailadres',
    '<strong>User</strong> modules' => '<strong>Gebruiker</strong> modules',
    '<strong>User</strong> settings' => '<strong>Gebruiker</strong> instellingen',
    '<strong>Your</strong> profile' => '<strong>Mijn</strong> profiel',
    'All your personal data will be irrevocably deleted.' => 'Al uw persoonlijke gegevens worden permanent verwijderd.',
    'Are you really sure? *ALL* module data for your profile will be deleted!' => 'Weet u het echt zeker? *ALLE* modulegegevens voor uw profiel worden verwijderd!',
    'Are you sure that you want to delete your account?' => 'Weet u zeker dat u uw account wilt verwijderen?',
    'Changing the username can make some links unusable, for example old links to the profile.' => 'Het wijzigen van de gebruikersnaam kan sommige links onbruikbaar maken, bijvoorbeeld oude links naar het profiel.',
    'Configure' => 'Configureer',
    'Confirm' => 'Bevestig',
    'Current password' => 'Huidig wachtwoord',
    'Delete account' => 'Account verwijderen',
    'Disable' => 'Uitschakelen',
    'Do you really want to delete your icon image?' => 'Wilt u uw pictogramafbeelding echt verwijderen?',
    'Do you really want to delete your logo image?' => 'Bent u zeker dat u uw logo wilt verwijderen?',
    'E-Mail' => 'E-mail',
    'E-Mail change' => 'E-mail aanpassen',
    'Enable' => 'Inschakelen',
    'Enhance your profile with modules.' => 'Breid uw profiel uit met modules.',
    'Enter your password to continue' => 'Voer uw wachtwoord in om door te gaan',
    'Hello' => 'Hallo',
    'Here you can edit your general profile data, which is visible in the about page of your profile.' => 'Hier kunt u uw algemene accountgegevens aanpassen, die zichtbaar zijn op de \'over mij\' pagina op uw profiel.',
    'Hide introduction tour panel on dashboard' => 'Introductie verbergen op uw dashboard',
    'Invalid link! Please make sure that you entered the entire url.' => 'Ongeldige link! Zorg dat u de volledige URL invoert.',
    'Language' => 'Taal',
    'Modules' => 'Modules',
    'New E-Mail address' => 'Nieuw e-mailadres',
    'New User name' => 'Nieuwe gebruikersnaam',
    'Not registered users' => 'Niet-geregistreerde gebruikers',
    'Notifications' => 'Notificaties',
    'Other users' => 'Andere gebruikers',
    'Password Recovery' => 'Wachtwoord herstellen',
    'Profile' => 'Profiel',
    'Profile visibility' => 'Profiel zichtbaarheid',
    'Registered users only' => 'Alleen geregistreerde gebruikers',
    'Save' => 'Bewaar',
    'Save profile' => 'Bewaar profiel',
    'Settings' => 'Instellingen',
    'Tags' => 'Labels',
    'The entered e-mail address is already in use by another user.' => 'Dit e-mailadres is al in gebruik.',
    'TimeZone' => 'Tijdzone',
    'Username has been changed' => 'Gebruikersnaam is gewijzigd',
    'Users' => 'Gebruikers',
    'Visible for all (also unregistered users)' => 'Zichtbaar voor iedereen (ook niet-geregistreerde gebruikers)',
    'We´ve just sent an confirmation e-mail to your new address. <br /> Please follow the instructions inside.' => 'Er is een bevestiging verstuurd naar uw e-mailadres.',
    'You are currently the owner of following spaces:' => 'U bent momenteel de eigenaar van de volgende ruimtes:',
    'You have requested to change your e-mail address.<br>Your new e-mail address is {newemail}.<br><br>To confirm your new e-mail address please click on the button below.' => 'Je hebt gevraagd om je e-mailadres te wijzigen.<br />Je nieuwe e-mailadres is {newemail}.<br /><br />Om je nieuwe e-mailadres te bevestigen, klik je op onderstaande knop.',
    'You have successfully changed your username.<br>Your new username is {newUsername}.' => 'U hebt uw gebruikersnaam gewijzigd.<br />Uw nieuwe gebruikersnaam is {newUsername}.',
    'You must transfer ownership or delete these spaces before you can delete your account.' => 'U moet het eigendom overdragen of deze ruimtes verwijderen voordat u uw account kunt verwijderen.',
    'Your account cannot be deleted!' => 'Uw account kan niet worden verwijderd!',
    'Your current E-mail address is <b>{email}</b>. You can change your current E-mail address here.' => 'Uw huidige e-mailadres is <b> {email} </b>. Hier kunt u uw huidige e-mailadres wijzigen.',
    'Your current password can be changed here.' => 'Uw wachtwoord kunt u hieronder veranderen.',
    'Your current username is <b>{username}</b>. You can change your current username here.' => 'Uw huidige gebruikersnaam is <b>{username}</b>. Hier kunt u uw huidige gebruikersnaam wijzigen.',
    'Your e-mail address has been successfully changed to {email}.' => 'Uw e-mailadres is succesvol aangepast naar {email}.',
    'Your friends' => 'Mijn vrienden',
    'Your password has been successfully changed!' => 'Uw paswoord is succesvol aangepast!',
    'Your username has been changed' => 'Uw gebruikersnaam is gewijzigd.',
    'Your username has been successfully changed. <br> We´ve just sent an e-mail to you with new information.' => 'Uw gebruikersnaam is succesvol gewijzigd.<br />We hebben u zojuist een e-mail gestuurd met nieuwe informatie.',
    '{attribute} "{value}" was not found!' => '{attribute} "{value}" niet gevonden!',
    '<strong>Permissions</strong>' => '',
    'Permissions' => '',
    'These settings allow you to determine which permissions you want to grant visitors of your own individual profile. Each user can freely adjust the settings for his or her own profile.' => '',
];
