<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All your personal data will be irrevocably deleted.' => '',
    'Are you sure that you want to delete your account?' => '',
    'Delete account' => '',
    'Enter your password to continue' => '',
    'You are currently the owner of following spaces:' => '',
    'You must transfer ownership or delete these spaces before you can delete your account.' => '',
    'Your account cannot be deleted!' => '',
    '<strong>Modify</strong> your profile image' => '<strong>Cambiar</strong> imachen de perfil',
    '<strong>Modify</strong> your title image' => '<strong>Cambiar</strong> imachen de portalada',
    '<strong>Security</strong> settings' => '<strong>Achustes</strong> de seguranza',
    '<strong>User</strong> settings' => '<strong>Achustes</strong> de usuario',
    '<strong>Your</strong> profile' => '<strong>O tuyo</strong> perfil',
    'E-Mail Summaries' => 'Resumens de correu',
    'Not registered users' => 'Usuarios no rechistraus',
    'Notifications' => 'Notificacions',
    'Other users' => 'Atros usuarios',
    'Users' => 'Usuarios',
    'Your friends' => 'Os tuyos amigos',
];
