version: '2'
plugins:
    duplication:
        enabled: true
        config:
            languages: [php]
    phpcodesniffer:
        enabled: true
        config:
            standard: phpcs.xml.dist
exclude_patterns:
    - '**/messages/'
    - 'config/'
    - '**/node_modules/'
    - '**/test/'
    - '**/tests/'
    - '**/vendor/'
    - '**/*_test.go'
    - '**/*.d.ts'
    - 'static/assets/'
    - 'assets/'
