engines:
 duplication:
   enabled: true
   config:
     languages:
     - php
 phpcodesniffer:
   enabled: true

ratings:
 paths:
 - "**.php"

exclude_paths:
- "**/messages/"
- "**/codeception/_support/_generated/"
- "static/assets/"
