[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.gd",
  "php82Extensions.intl",
  "php82Extensions.pdo_mysql",
  "php82Extensions.zip",
  "php82Extensions.curl",
  "php82Extensions.mbstring",
  "php82Extensions.xml",
  "php82Extensions.imagick",
  "composer"
]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "chmod -R 777 assets uploads protected/runtime protected/config && php-fpm"
