<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> comment deleting' => '<strong>Potvrďte</strong> smazání komentáře',
    'Cancel' => 'Zrušit',
    'Cancel Edit' => 'Zrušit úpravy',
    'Comment' => 'Komentovat',
    'Comment has been deleted' => 'Komentář odstraněn',
    'Comments' => 'Komentáře',
    'Delete' => 'Smazat',
    'Do you really want to delete this comment?' => 'Opravdu chcete smazat tento komentář?',
    'Edit' => 'Upravit',
    'Edit your comment...' => 'Upravit komentář...',
    'Read full comment...' => 'Přečíst celý komentář',
    'Send' => 'Odeslat',
    'Show all {total} comments' => 'Zobrazit všech {total} komentářů',
    'Show {count} more comments' => 'Zobrazit dalších {count} komentářů',
    'Whenever a new comment was written.' => 'Kdykoli byl napsán nový komentář.',
    'Write a new comment...' => 'Napište komentář...',
    'comment' => 'Komentář',
    '{displayName} wrote a new comment ' => '{displayName} napsal(a) nový komentář',
    'Comment could not be saved!' => '',
    'Reply' => '',
    'The comment must not be empty!' => '',
    'Write a new reply...' => '',
];
