<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Administration</strong> menu' => '<strong>Панель Управления</strong>',
    '<strong>Module </strong> administration' => '<strong>Управление модулями</strong>',
    '<strong>Warning</strong> incomplete setup!' => '<strong>Предупреждение</ strong>: настройка не завершена!',
    'About' => 'Информация',
    'Admin' => 'Администратор',
    'Administration' => 'Панель Управления',
    'Administrative group' => 'Административная группа',
    'Advanced' => 'Дополнительные',
    'Appearance' => 'Внешний вид',
    'Approval' => 'Подтверждение',
    'Authentication' => 'Авторизация',
    'Back to overview' => 'Вернуться',
    'Back to user overview' => 'Вернуться к списку пользователей',
    'Base URL needs to begin with http:// or https://' => 'Базовый URL должен начинаться с http:// или https://',
    'Basic' => 'Основные',
    'Caching' => 'Кеширование',
    'Cronjobs' => 'Задания Cron',
    'Design' => 'Дизайн',
    'Files' => 'Файлы',
    'General' => 'Общие',
    'Groups' => 'Группы',
    'Groups (Note: The Administrator group of this user can\'t be managed with your permissions)' => 'Группы (Примечание: Группа администраторов этого пользователя не может быть изменена с Вашим уровнем доступа)',
    'Information' => 'Информация',
    'Invite' => 'Пригласить',
    'Invited by' => 'Приглашен(ы)',
    'Logging' => 'Логгирование',
    'Logs' => 'Логи',
    'Mailing' => 'Почта',
    'Modules' => 'Модули',
    'Notifications' => 'Уведомления',
    'OEmbed' => 'OEmbed',
    'OEmbed providers' => 'Провайдеры OEmbed',
    'Open documentation' => 'Открыть документацию',
    'Pending user registrations' => 'Пользователи ожидающие подтверждения',
    'Permissions' => 'Доступ',
    'Proxy' => 'Прокси',
    'Self test' => 'Самопроверка',
    'Settings' => 'Настройки',
    'Sign up' => 'Зарегистрироваться',
    'Spaces' => 'Сообщества',
    'Statistics' => 'Статистика',
    'The cron job for the background jobs (queue) does not seem to work properly.' => 'Расписание cron для фоновых задач (queue) не работает должным образом.',
    'The cron job for the regular tasks (cron) does not seem to work properly.' => 'Расписание cron для обычных задач (cron) не работает должным образом.',
    'User posts' => 'Сообщения пользователей',
    'Userprofiles' => 'Профили пользователей',
    'Users' => 'Пользователи',
    '<strong>Maintenance</strong> Mode' => '',
    'Default' => '',
    'Delete all' => '',
    'Delete selected rows' => '',
];
