<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'LDAP' => '',
    'Advanced Settings' => 'Расширенные настройки',
    'Appearance Settings' => 'Настройки внешнего вида',
    'E-Mail Settings' => 'Настройки E-Mail',
    'General' => 'Общее',
    'General Settings' => 'Общие настройки',
    'Here you can configurate the e-mail behaviour and mail-server settings of your social network.' => 'Здесь вы можете настроить почтовый сервер вашей социальной сети.',
    'Here you can configurate the registration behaviour and additinal user settings of your social network.' => 'Здесь вы можете настроить поведение и способы регистрации пользователей.',
    'Here you can configure basic settings of your social network.' => 'Здесь вы можете настроить базовую конфигурацию вашей социальной сети.',
    'These settings refer to advanced topics of your social network.' => 'Эти настройки относятся к расширенным разделам вашей социальной сети.',
    'These settings refer to the appearance of your social network.' => 'Эти настройки относятся к внешнему виду вашей социальной сети.',
    'User Settings' => 'Пользовательские настройки',
];
