<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Information</strong>' => '<strong>Информация</strong>',
    '<strong>Settings</strong> and Configuration' => '<strong>Настройки и конфигурация</strong>',
    '<strong>User</strong> administration' => '<strong>Управление пользователями</strong>',
    'Accept user: <strong>{displayName}</strong> ' => 'Активировать пользователя: <strong>{displayName}</strong> ',
    'Account Request for \'{displayName}\' has been approved.' => 'Учётная запись для \'{displayName}\' была утверждена.',
    'Account Request for \'{displayName}\' has been declined.' => 'Учётная запись для \'{displayName}\' была отклонена.',
    'Actions' => 'Действия',
    'Add new category' => 'Добавить новую категорию',
    'Add new field' => 'Добавить новое поле',
    'Add new group' => 'Создать новую группу',
    'Add new members...' => 'Добавить участников...',
    'Add new user' => 'Добавить нового пользователя',
    'Allow limited access for non-authenticated users (guests)' => 'Разрешить ограниченный доступ для незарегистрированных пользователей (гостей)',
    'Anonymous users can register' => 'Любой пользователь может зарегистрироваться',
    'Cancel' => 'Отменить',
    'Click here to review' => 'Нажмите здесь, чтобы просмотреть',
    'Could not load category.' => 'Невозможно загрузить категорию.',
    'Create new group' => 'Создать новую группу',
    'Create new profile category' => 'Создать новую категорию профиля',
    'Create new profile field' => 'Добавить новое поле профиля',
    'Decline & delete user: <strong>{displayName}</strong>' => 'Отклонить и удалить пользователя: <strong>{displayName}</strong>',
    'Default user group for new users' => 'Группа по умолчанию для новых пользователей',
    'Default user idle timeout, auto-logout (in seconds, optional)' => 'Время бездействия пользователя до авто-выхода по умолчанию (в секундах, опционально)',
    'Default user profile visibility' => 'Кому виден профиль пользователя по умолчанию',
    'Delete' => 'Удалить',
    'Disable' => 'Выключить',
    'Disabled' => 'Отключён',
    'Edit profile category' => 'Изменить категорию профиля',
    'Edit profile field' => 'Изменить поле профиля',
    'Edit user: {name}' => 'Редактировать пользователя: {name}',
    'Enable' => 'Включить',
    'Enabled' => 'Включён',
    'General' => 'Основная информация',
    'Group Manager' => 'Менеджер группы',
    'Group not found!' => 'Группа не найдена!',
    'Group user not found!' => 'Участник группы не найден!',
    'Groups' => 'Группы',
    'Here you can create or edit profile categories and fields.' => 'Здесь вы можете создавать или редактировать категории и поля профилей пользователей.',
    'LDAP' => 'LDAP',
    'Last login' => 'Последний визит',
    'Manage group: {groupName}' => 'Управление группой: {groupName}',
    'Manage groups' => 'Управление группами',
    'Manage profile attributes' => 'Управление атрибутами профиля',
    'Members' => 'Участники',
    'Members can invite external users by email' => 'Участники могут приглашать новых пользователей по электронной почте',
    'Message' => 'Сообщение',
    'Min value is 20 seconds. If not set, session will timeout after 1400 seconds (24 minutes) regardless of activity (default session timeout)' => 'Минимальное значение - 20 секунд. Если не установлено - сессия завершится через 1400 секунд (24 минуты) независимо от активности (таймаут сессии по умолчанию)',
    'New approval requests' => 'Новые запросы на подтверждение',
    'No' => 'Нет',
    'No value found!' => 'Значение не найдено!',
    'One or more user needs your approval as group admin.' => 'Один или несколько пользователей нуждаются в вашем подтверждении в качестве администратора группы.',
    'Only applicable when limited access for non-authenticated users is enabled. Only affects new users.' => 'Применяется только в том случае, если включен ограниченный доступ для незарегистрированных пользователей. Влияет только на новых пользователей.',
    'Overview' => 'Список пользователей',
    'Pending approvals' => 'В ожидании подтверждения',
    'Pending user approvals' => 'Ожидает подтверждения пользователей',
    'Permissions' => 'Доступ',
    'Profiles' => 'Профили',
    'Remove from group' => 'Удалить из группы',
    'Require group admin approval after registration' => 'После регистрации требуется одобрение администратора',
    'Save' => 'Сохранить',
    'Send & save' => 'Отправить и сохранить',
    'Send invite' => 'Отправить приглашеине',
    'Settings' => 'Настройки',
    'Subject' => 'Тема',
    'The following list contains all registered users awaiting an approval.' => 'Список содержит всех зарегистрированных пользователей, ожидающих подверждения.',
    'This overview contains a list of each registered user with actions to view, edit and delete users.' => 'Ниже приведён список зарегистрированных пользователей  с возможностью для просмотра, редактирования и удаления пользователей.',
    'Unapproved' => 'Не подтверждён',
    'User not found!' => 'Пользователь не найден!',
    'Users' => 'Пользователи',
    'Users can be assigned to different groups (e.g. teams, departments etc.) with specific standard spaces, group managers and permissions.' => 'Пользователи могут быть назначены в различные группы (например, команды, отделы и так далее), с определенными стандартными сообществами для той или иной группы, а также менеджерами групп и сопутствующими правами.',
    'Visibility' => 'Видимость',
    'Visible for members only' => 'Только зарегистрированным пользователям',
    'Visible for members+guests' => 'Зарегистрированным пользователям и гостям',
    'Yes' => 'Да',
    'You can only delete empty categories!' => 'Вы можете удалять только пустые категории!',
    'You cannot delete yourself!' => 'Вы не можете удалить себя!',
    'never' => 'никогда',
    'Active users' => '',
    'Add Groups...' => '',
    'All the personal data of this user will be irrevocably deleted.' => '',
    'Are you really sure that you want to disable this user?' => '',
    'Are you really sure that you want to enable this user?' => '',
    'Are you really sure that you want to impersonate this user?' => '',
    'Are you sure that you want to delete following user?' => '',
    'Confirm user deletion' => '',
    'Default content of the registration approval email' => '',
    'Default content of the registration denial email' => '',
    'Delete all contributions of this user' => '',
    'Delete invitation' => '',
    'Delete invitation?' => '',
    'Delete spaces which are owned by this user' => '',
    'Deleted invitation' => '',
    'Deleted users' => '',
    'Disabled users' => '',
    'Do not change placeholders like {displayName} if you want them to be automatically filled by the system. To reset the email content fields with the system default, leave them empty.' => '',
    'Edit category' => '',
    'Hello {displayName},<br><br>
Your account has been activated.<br><br>
Click here to login:<br>
{loginLink}<br><br>

Kind Regards<br>
{AdminName}<br><br>' => '',
    'Hello {displayName},<br><br>
Your account request has been declined.<br><br>

Kind Regards<br>
{AdminName} <br><br> ' => '',
    'If this option is not selected, the ownership of the spaces will be transferred to your account.' => '',
    'Impersonate' => '',
    'Include captcha in registration form' => '',
    'Invite not found!' => '',
    'List pending registrations' => '',
    'Member since' => '',
    'Permanently delete' => '',
    'Resend invitation email' => '',
    'Search by name, email or id.' => '',
    'Select Groups' => '',
    'Send invitation email' => '',
    'Send invitation email again?' => '',
    'The following list contains all pending sign-ups and invites.' => '',
    'The user is the owner of these spaces:' => '',
    'This user owns no spaces.' => '',
    'User deletion process queued.' => '',
    'User is already a member of this group.' => '',
    'Using this option any contributions (e.g. contents, comments or likes) of this user will be irrevocably deleted.' => '',
    'View profile' => '',
];
