<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Here you can define your default settings for new spaces. These settings can be overwritten for each individual space.' => 'Здесь вы можете задать настройки по умолчанию для новых пространств. Эти параметры могут быть перезаписаны для каждого отдельного пространства.',
    'This overview contains a list of each space with actions to view, edit and delete spaces.' => 'Содержит список пространств с возможностью просмотра, редактирования и удаления.',
    '<strong>Manage</strong> spaces' => '<strong>Управление</strong> пространствами',
    'Actions' => 'Действия',
    'Overview' => 'Обзор',
    'Settings' => 'Настройки',
    'Spaces' => 'Пространства'
];
