<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel Membership' => 'Mitgliedschaft beenden',
    'Don\'t receive notifications for new content' => 'Keine Benachrichtigungen über neue Inhalte mehr empfangen',
    'Hide posts on dashboard' => 'Beiträge in der Übersicht ausblenden',
    'Members' => 'Mitglieder',
    'Modules' => 'Module',
    'Receive Notifications for new content' => 'Benachrichtigungen über neue Inhalte empfangen',
    'Security' => 'Sicherheit',
    'Show posts on dashboard' => 'Beiträge in der Übersicht anzeigen',
    'This option will hide new content from this space at your dashboard' => 'Diese Option blendet neue Inhalte aus diesem Space in Deiner Übersicht aus.',
    'This option will show new content from this space at your dashboard' => 'Diese Option zeigt neue Inhalte aus diesem Space in Deiner Übersicht an.',
];
