<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to stream' => 'Terug naar berichten',
    'Content with attached files' => 'Berichten met bestanden',
    'Created by me' => 'Aangemaakt door mij',
    'Creation time' => 'Aanmaak datum',
    'Filter' => 'Filter',
    'Include archived posts' => 'Inclusief gearchiveerde berichten',
    'Last update' => 'Laatste update',
    'No matches with your selected filters!' => 'Geen resultaten met de geselecteerde filters!',
    'Nothing here yet!' => 'Nog niets om weer te geven!',
    'Only private posts' => 'Alleen privé berichten',
    'Only public posts' => 'Alleen publieke berichten',
    'Posts only' => 'Alleen berichten',
    'Posts with links' => 'Berichten met links',
    'Sorting' => 'Sortering',
    'Where I´m involved' => 'Waar ik bij betrokken ben',
];
