<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Warning</strong> incomplete setup!' => '',
    'Groups (Note: The Administrator group of this user can\'t be managed with your permissions)' => '',
    'Open documentation' => '',
    'The cron job for the background jobs (queue) does not seem to work properly.' => '',
    'The cron job for the regular tasks (cron) does not seem to work properly.' => '',
    'About' => 'Acerca de',
    'Add purchased module by licence key' => 'Agregar licencia de módulo comprado',
    'Admin' => 'Administrador',
    'Administration' => 'Administración',
    'Approval' => 'Aprobación',
    'Authentication' => 'Autenticación',
    'Back to overview' => 'Regresar a la vista previa',
    'Back to user overview' => 'Volver a resumen de usuario',
    'Base URL needs to begin with http:// or https://' => 'La URL base necesita comenzar con http:// o https://',
    'Basic' => 'Básica',
    'Caching' => 'Caché',
    'Cronjobs' => 'Tareas programadas',
    'Design' => 'Diseño',
    'Files' => 'Archivos',
    'Groups' => 'Grupos',
    'Invite' => 'Invitar',
    'Invited by' => 'Invitado por',
    'Logging' => 'Registro',
    'Mailing' => 'Correos',
    'Modules' => 'Módulos',
    'OEmbed providers' => 'Proveedores OEmbed',
    'Pending user registrations' => 'Registros de usuario pendientes',
    'Proxy' => 'Proxy',
    'Security' => 'Seguridad',
    'Self test' => 'Auto prueba',
    'Sign up' => 'Registrarse',
    'Spaces' => 'Espacios',
    'Statistics' => 'Estadísticas',
    'User posts' => 'Publicaciones de usuario',
    'Userprofiles' => 'Perfiles de usuario',
    'Users' => 'Usuarios',
];
