<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Default content of the registration approval email' => '',
    'Default content of the registration denial email' => '',
    'Allow limited access for non-authenticated users (guests)' => 'Permitir acceso limitado para usuarios no autentificados (invitados)',
    'Anonymous users can register' => 'Los usuarios anónimos pueden registrarse',
    'Default user group for new users' => 'Grupo por defecto para nuevos usuarios',
    'Default user idle timeout, auto-logout (in seconds, optional)' => 'Tiempo de inactividad antes de cerrar sesión (en segundos, opcional)',
    'Default user profile visibility' => 'Visibilidad del perfil de usuario por defecto',
    'Members can invite external users by email' => 'Los miembros pueden invitar a usuarios externos por correo electrónico',
    'Require group admin approval after registration' => 'Requerir aprobación del administrador del grupo después de registrarse',
];
