<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID Attribute' => '',
    'Not changeable LDAP attribute to unambiguously identify the user in the directory. If empty the user will be determined automatically by e-mail address or username. Examples: objectguid (ActiveDirectory) or uidNumber (OpenLDAP)' => '',
    'Base DN' => 'DN de base',
    'E-Mail Address Attribute' => 'Atributo de dirección de correo',
    'Enable LDAP Support' => 'Activar soporte LDAP',
    'Encryption' => 'Cifrado',
    'Fetch/Update Users Automatically' => 'Cargar/actualizar usuarios automáticamente',
    'Hostname' => 'Nombre de servidor',
    'Login Filter' => 'Filtro de inicio de sesión',
    'Password' => 'Contraseña',
    'Port' => 'Puerto',
    'User Filer' => 'Filtro de usuario',
    'Username' => 'Nombre de usuario',
    'Username Attribute' => 'Atributo del nombre de usuario',
];
