<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Purchases' => '',
    'Available updates' => 'Actualizaciones disponibles',
    'Browse online' => 'Explorar en línea',
    'Installed' => 'Instalado',
    'Modules extend the functionality of HumHub. Here you can install and manage modules from the HumHub Marketplace.' => 'Los módulos permiten extender las funcionalidades de HumHub. Aquí puedes instalar y configurar módulos de la HumHub Marketplace.',
];
