<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'This group has no members yet.' => '',
    '<b>Nobody wrote something yet.</b><br>Make the beginning and post something...' => '<b>Personne n\'a rien écrit pour le moment.</b><br>Soyez le premier et écrivez quelque chose...',
    '<b>There are no profile posts yet!</b>' => '<b>Il n\'y a aucune publication actuellement</b>',
    '<strong>Directory</strong> menu' => 'Menu <strong>annuaire</strong>',
    '<strong>Group</strong> members - {group}' => '<strong>Membres</strong> du groupe - {group}',
    '<strong>Group</strong> stats' => 'Statistiques des <strong>groupe</strong>',
    '<strong>Member</strong> Group Directory' => 'Annuaire des <strong>membres de groupes</strong>',
    '<strong>Member</strong> directory' => 'Annuaire <strong>des membres</strong>',
    '<strong>Member</strong> stats' => '<strong>Statistiques</strong> des membres',
    '<strong>New</strong> people' => '<strong>Nouveaux</strong> membres',
    '<strong>New</strong> spaces' => '<strong>Nouveaux</strong> espaces',
    '<strong>Space</strong> directory' => 'Annuaire des <strong>espaces</strong>',
    '<strong>Space</strong> stats' => '<strong>Statistiques</strong> des espaces',
    'Average members' => 'Moyenne des membres',
    'Directory' => 'Annuaire',
    'Follows somebody' => 'Abonnés à quelqu\'un ',
    'Groups' => 'Groupes',
    'Members' => 'Membres',
    'Most members' => 'Plus de membres ',
    'No members found!' => 'Aucun membre.',
    'No spaces found!' => 'Aucun espace trouvé.',
    'Online right now' => 'En ligne en ce moment',
    'Private spaces' => 'Espaces privés',
    'Search' => 'Rechercher',
    'See all' => 'Voir tous',
    'Send invite' => 'Envoyer l\'invitation',
    'Spaces' => 'Espaces',
    'Top Group' => 'Groupe le plus actif',
    'Total groups' => 'Nombre de groupes',
    'Total spaces' => 'Nombre d\'espaces',
    'Total users' => 'Nombre de membres',
    'User profile posts' => 'Publications des membres',
    'You are a member of this space' => 'Vous êtes membre de cet espace',
    'search for members' => 'chercher des membres',
    'search for spaces' => 'chercher des espaces',
    'show all members' => 'Voir tous les membres',
];
