<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allows the user to create private content' => 'يسمح للمستخدم بإنشاء محتوى خاص',
    'Allows the user to create public content' => 'يسمح للمستخدم بإنشاء محتوى عام',
    'Allows the user to invite new members to the space' => 'يسمح للمستخدم بدعوة أعضاء جدد إلى الفضاء',
    'Can create hidden (private) spaces.' => 'يمكنه إنشاء فضاء مخفي (خاص)',
    'Can create public visible spaces. (Listed in directory)' => 'يمكن إنشاء فضاء عام مرئي. (مدرج في الدليل)',
    'Create private content' => 'إنشاء محتوى خاص',
    'Create private space' => 'إنشاء فضاء خاص',
    'Create public content' => 'إنشاء محتوى عام',
    'Create public space' => 'إنشاء فضاء عام',
    'Invite users' => 'دعوة المستخدمين',
];
