<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created at' => 'Luotu',
    'Created by' => 'Luonut',
    'Description' => 'Kuvaus',
    'Editable' => 'Muokattavissa',
    'Field Type could not be changed!' => 'Kentän tyyppiä ei voitu vaihtaa',
    'Fieldtype' => 'Kentän tyyppi',
    'ID' => 'ID',
    'Internal Name' => 'Sisäinen nimi',
    'Internal name already in use!' => 'Sisäinen nimi on jo käytössä!',
    'Internal name could not be changed!' => 'Sisäistä nimeä ei voitu vaihtaa!',
    'Invalid field type!' => 'Virheellinen kenttätyyppi!',
    'LDAP Attribute' => 'LDAP-ominaisuus',
    'Module' => 'Laajennus',
    'Only alphanumeric characters allowed!' => 'Vain aakkosnumeeriset ovat merkit sallittuja!',
    'Profile Field Category' => 'Profiilin kentän luokka',
    'Required' => 'Vaaditaan',
    'Searchable' => 'Haettavissa',
    'Show at registration' => 'Näytä reksiteröityessä',
    'Sort order' => 'Lajittelujärjestys',
    'Title' => 'Otsikko',
    'Translation Category ID' => 'Käännöstunnus',
    'Type Config' => 'Tyypin asetukset',
    'Updated at' => 'Päivitetty',
    'Updated by' => 'Päivittänyt',
    'Visible' => 'Näkyvyys',
];
