<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Join</strong> the network' => '',
    '<strong>Sign</strong> up' => '',
    'Don\'t have an account? Join the network by entering your e-mail address.' => '',
    'If you\'re already a member, please login with your username/email and password.' => '',
    'Register' => '',
    '<strong>Please</strong> sign in' => '<strong>Kirjaudu sisään</strong>',
    'Forgot your password?' => 'Unohditko salasanasi?',
    'Login' => 'Kirjaudu sisään',
    'Please login with your username/email and password.' => 'Kirjaudu sisään jotta pääset käyttämään intraa. <a href="http://www.vaajanvalppaat.fi/">Tästä pääset taikaisin nettisivulle</a>',
    'Remember me' => 'Muista minut',
    'Sign in' => 'Kirjaudu sisään',
    'email' => 'Sähkäposti',
    'password' => 'Salasana',
    'username or email' => 'Sähköposti tai käyttäjätunnus',
];
