<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Account</strong> registration' => '<strong>Registre</strong> d\'un compte',
    '<strong>Please</strong> sign in' => '<strong>Si us plau</strong> inicia sessió',
    '<strong>Sign</strong> up' => '<strong>Registrar-me</strong>',
    'Back' => 'Enrere',
    'Forgot your password?' => 'No recordes la contrasenya?',
    'Group' => 'Grup',
    'Login' => 'Inici de sessió',
    'Register' => 'Registre',
    'Sign in' => 'Inicia sessió',
    'Your password' => 'La teva contrasenya',
    'Your password has been successfully changed!' => 'La teva constrasenya s\'ha modificat correctament!',
    'back to home' => 'Torna a l\'inici',
    'email' => 'correu electrònic',
    'password' => 'contrasenya',
    'username or email' => 'usuari o correu ',
    '<strong>Change</strong> your password' => '',
    '<strong>Join</strong> the network' => '',
    '<strong>Password</strong> changed!' => '',
    '<strong>Password</strong> recovery' => '',
    '<strong>Password</strong> recovery!' => '',
    '<strong>Registration</strong> successful!' => '',
    '<strong>Your account</strong> has been successfully created!' => '',
    'Account' => '',
    'After activating your account by the administrator, you will receive a notification by email.' => '',
    'Change password' => '',
    'Create Account' => '',
    'Create account' => '',
    'Don\'t have an account? Join the network by entering your e-mail address.' => '',
    'Enter security code above' => '',
    'Go to login page' => '',
    'Hello {displayName}' => '',
    'Hello {displayName},' => '',
    'If you don\'t use this link within 24 hours, it will expire.' => '',
    'If you\'re already a member, please login with your username/email and password.' => '',
    'Just enter your e-mail address. We\'ll send you recovery instructions!' => '',
    'New user needs approval' => '',
    'Password recovery' => '',
    'Password reset' => '',
    'Please check your email and follow the instructions!' => '',
    'Please click on the link below to view request:' => '',
    'Please enter the letters from the image.' => '',
    'Please login with your username/email and password.' => '',
    'Please use the following link within the next day to reset your password.' => '',
    'Registration successful' => '',
    'Remember me' => '',
    'Reset Password' => '',
    'Reset password' => '',
    'To log in with your new account, click the button below.' => '',
    'User or Password incorrect.' => '',
    'We’ve sent you an email containing a link that will allow you to reset your password.' => '',
    'Your email' => '',
    'Your password is incorrect!' => '',
    'a new user {displayName} needs approval.' => '',
];
