<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Space' => 'Añadir espacio',
    'Create new space' => 'Crear nuevo espacio',
    'My spaces' => 'Mis espacios',
    'No member or following spaces found.' => 'No se han encontrado miembros o espacios que esté siguiendo.',
    'No result found for the given filter.' => 'No se han encontrado resultados para ese filtro.',
    'No spaces found for the given query' => 'No se han encontrado espacios para esa petición',
    'Search' => 'Buscar',
    'Search for spaces' => 'Buscar espacios',
    'Select {n,plural,=1{space} other{spaces}}' => 'Seleccionar {n,plural,=1{space} other{spaces}}',
    'This field only allows a maximum of {n,plural,=1{# space} other{# spaces}}' => 'Este campo admite sólo un máximo de {n,plural,=1{# space} other{# spaces}}',
    'This space is archived' => 'Este espacio está archivado',
    'To search for other spaces, type at least {count} characters.' => 'Para buscar otros espacios, teclee al menos {count} caracteres.',
    'You are a member of this space' => 'Eres miembro de este espacio',
    'You are following this space' => 'Usted está siguiendo a este espacio',
    '{n,plural,=1{# new entry} other{# new entries}} since your last visit' => '{n,plural,=1{# new entry} other{# new entries}} desde su última visita',
];
