<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Remove from space' => '',
    'Show all' => '',
    'As owner of this space you can transfer this role to another administrator in space.' => 'Como propietario de este espacio usted puede transferir este rol a otro administrador del espacio.',
    'Space owner' => 'Dueño del espacio',
    'The url contains illegal characters!' => '¡La URL contiene caracteres no válidos!',
    'Transfer ownership' => 'Transferir propiedad',
    'e.g. example for {baseUrl}/s/example' => 'p. ej. ejemplo para {baseUrl}/s/ejemplo',
    'the default start page of this space for members' => 'la página de inicio por defecto para los miembros de este espacio',
    'the default start page of this space for visitors' => 'la página de inicio por defecto para los visitantes de este espacio',
];
