<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '-' => '-',
    '<strong>Create</strong> new space' => '<strong>Crear</strong> nuevo espacio',
    '<strong>Manage</strong> members' => '<strong>Administrar</strong> miembros',
    '<strong>Members</strong>' => '<strong>Miembros</strong>',
    '<strong>Security</strong> settings' => 'Ajustes de <strong>Seguridad</strong>',
    '<strong>Space</strong> Modules' => '<strong>Módulos</strong> del espacio',
    '<strong>Space</strong> settings' => 'Configuración del <strong>espacio</strong>',
    'Actions' => 'Acciones',
    'Activated' => 'Activado',
    'Add <strong>Modules</strong>' => 'Añadir <strong>Modulos</strong>',
    'Advanced access settings' => 'Ajustes avanzados de acceso',
    'Archive' => 'Archivo',
    'Are you sure, that you want to delete this space? All published content will be removed!' => '¿Estás seguro de que quieres eliminar este espacio? ¡Todo el contenido publicado sera borrado!',
    'Are you sure? *ALL* module data for this space will be deleted!' => '¿Estás seguro? ¡*TODOS* los datos del módulo de este espacio seran borrados!',
    'As owner of this space you can transfer this role to another administrator in space.' => 'Como propietario de este espacio usted puede transferir este rol a otro administrador del espacio.',
    'Cancel Membership' => 'Cancelar Membresía',
    'Choose if new content should be public or private by default' => 'Selecciona si el nuevo contenido debe ser público o privado por defecto',
    'Choose the kind of membership you want to provide for this workspace.' => 'Elige el tipo de suscripción que quieres dar a este espacio.',
    'Choose the security level for this workspace to define the visibleness.' => 'Elige el nivel de seguridad para este espacio para definir la visibilidad.',
    'Configure' => 'Configurar',
    'Currently there are no modules available for this space!' => '¡Actualmente no hay módulos disponibles para este espacio!',
    'Delete' => 'Eliminar',
    'Disable' => 'Deshabilitar',
    'Don\'t receive notifications for new content' => 'No recibir notificaciones de contenido nuevo',
    'Enable' => 'Habilitar',
    'Enhance this space with modules.' => 'Mejora este espacio con módulos.',
    'Hide posts on dashboard' => 'Ocultar publicaciones en el panel de contol',
    'Invited By' => 'Invitado por',
    'Members' => 'Miembros',
    'Modules' => 'Módulos',
    'Next' => 'Siguiente',
    'Owner' => 'Propietario',
    'Pending Approvals' => 'Aprobaciones Pendientes',
    'Pending Invites' => 'Invitaciones Pendientes',
    'Permissions are assigned to different user-roles. To edit a permission, select the user-role you want to edit and change the drop-down value of the given permission.' => 'Se asignan permisos a diferentes roles de usuario. Para editar un permiso, seleccione el rol de usuario que quiere modificar y cambie el valor del del desplegable al nuevo permiso.',
    'Receive Notifications for new content' => 'Recibir notificaciones de contenido nuevo',
    'Remove from space' => 'Quitar del espacio',
    'Role' => 'Rol',
    'Security' => 'Seguridad',
    'Send & decline' => 'Enviar y declinar',
    'Show all' => 'Mostrar todo',
    'Show posts on dashboard' => 'Mostrar publicaciones en el panel de control',
    'Space name' => 'Nombre del Espacio',
    'Space owner' => 'Dueño del espacio',
    'Stream (Default)' => 'Flujo (predeterminado)',
    'The url contains illegal characters!' => '¡La URL contiene caracteres no válidos!',
    'This option will hide new content from this space at your dashboard' => 'Esta opción oculta nuevos contenidos de este espacio en el panel de control',
    'This option will show new content from this space at your dashboard' => 'Esta opción muestra nuevos contenidos de este espacio en el panel de control',
    'Transfer ownership' => 'Transferir propiedad',
    'Unarchive' => 'Desarchivar',
    'e.g. example for {baseUrl}/s/example' => 'p. ej. ejemplo para {baseUrl}/s/ejemplo',
    'never' => 'Nunca',
    'space description' => 'descripción del espacio',
    'the default start page of this space for members' => 'la página de inicio por defecto para los miembros de este espacio',
    'the default start page of this space for visitors' => 'la página de inicio por defecto para los visitantes de este espacio',
    'Please type the name of the space to proceed.' => '',
];
