<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> Action' => '',
    '<strong>Mail</strong> summary' => '',
    'Allow' => '',
    'An error occured while handling your last action. (Handler not found).' => '',
    'An unexpected error occured while loading the search result.' => '',
    'An unexpected error occured. If this keeps happening, please contact a site administrator.' => '',
    'An unexpected server error occured. If this keeps happening, please contact a site administrator.' => '',
    'An unknown error occured while uploading.' => '',
    'An unknown error occured while uploading. Hint: check your upload_max_filesize and post_max_size php settings.' => '',
    'Confirm' => '',
    'Copy to clipboard' => '',
    'Default' => '',
    'Deny' => '',
    'Do you really want to perform this action?' => '',
    'Error while running your last action (Invalid request method).' => '',
    'Error:' => '',
    'Info:' => '',
    'Loading...' => '',
    'Next' => '',
    'No error information given.' => '',
    'Open' => '',
    'Please type at least 3 characters' => '',
    'Show less' => '',
    'Show more' => '',
    'Some files could not be uploaded:' => '',
    'The date has to be in the past.' => '',
    'The file has been deleted.' => '',
    'The requested resource could not be found.' => '',
    'The space has been archived.' => '',
    'The space has been unarchived.' => '',
    'Unsubscribe' => '',
    'Upload' => '',
    'You are not allowed to run this action.' => '',
    '<strong>Latest</strong> updates' => '<strong>Ultimele</strong> actualizări',
    'Account settings' => 'Setări de Cont',
    'Administration' => 'Administrație',
    'Back' => 'Înapoi',
    'Back to dashboard' => 'Înapoi la panoul de control',
    'Cancel' => 'Anulează',
    'Choose language:' => 'Alege limba:',
    'Close' => 'Închide',
    'Collapse' => 'Strânge',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => 'Sursa Conținutului de Adaos trebuie să fie instanță a HActiveRecordContent sau a HActiveRecordContentAddon!',
    'Could not determine content container!' => 'Nu s-a putut determina containerul conținutului!',
    'Could not find content of addon!' => 'Nu s-a putut găsi conținutul adaosului!',
    'Error' => 'Eroare',
    'Expand' => 'Extinde',
    'It looks like you may have taken the wrong turn.' => 'Se pare că ai luat-o pe calea greșită.',
    'Language' => 'Limbă',
    'Login' => 'Autentificare',
    'Logout' => 'Ieșire cont',
    'Menu' => 'Meniu',
    'Module is not enabled on this content container!' => 'Modulul nu este pe acest container de conținut activat!',
    'My profile' => 'Profilul meu',
    'New profile image' => 'Imagine nouă de profil',
    'Oooops...' => 'Oooops...',
    'Save' => 'Salvează',
    'Saved' => '저장됨',
    'Search' => 'Căutare',
    'Space not found!' => 'Spațiul nu s-a găsit!',
    'User not found!' => 'Utilizator negăsit!',
];
