<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Create</strong> new space' => '<strong>Skapa</strong> nytt nätverk',
    '<strong>Members</strong>' => '<strong>Medlemmar</strong>',
    '<strong>Security</strong> settings' => '<strong>Säkerhetsinställningar</strong>',
    'Actions' => 'Åtgärder',
    'Add <strong>Modules</strong>' => 'Lägg till moduler',
    'Advanced access settings' => 'Avancerade åtkomstinställningar',
    'Archive' => 'Arikivera',
    'Are you sure, that you want to delete this space? All published content will be removed!' => 'Är du säker på att du vill ta bort detta nätverk? Allt publicerat material kommer tas bort!',
    'Configure' => 'Konfigurera',
    'Delete' => 'Ta bort',
    'Disable' => 'Inaktivera',
    'Enable' => 'Aktivera',
    'Members' => 'Medlemmar',
    'Modules' => 'Moduler',
    'Next' => 'Nästa',
    'Owner' => 'Ägare',
    'Pending Approvals' => 'Väntande godkännanden',
    'Pending Invites' => 'Väntande inbjudningar',
    'Remove from space' => 'Ta bort från nätverk',
    'Security' => 'Säkerhet',
    'Send & decline' => 'Sänd &amp; avböj',
    'Show all' => 'Visa alla',
    'Space name' => 'Nätverksnamn',
    'Space owner' => 'Ägare av nätverk',
    'Stream (Default)' => 'Flöde (Standard)',
    'The url contains illegal characters!' => 'Url innehåller ogiltliga tecken!',
    'Transfer ownership' => 'Flytta ägarskap',
    'Unarchive' => 'Återställ',
    '-' => '',
    '<strong>Manage</strong> members' => '',
    '<strong>Space</strong> Modules' => '',
    '<strong>Space</strong> settings' => '',
    'Activated' => '',
    'Are you sure you want to remove this member.' => '',
    'Are you sure? *ALL* module data for this space will be deleted!' => '',
    'As owner of this space you can transfer this role to another administrator in space.' => '',
    'Cancel Membership' => '',
    'Choose if new content should be public or private by default' => '',
    'Choose the kind of membership you want to provide for this workspace.' => '',
    'Choose the security level for this workspace to define the visibleness.' => '',
    'Currently there are no modules available for this space!' => '',
    'Don\'t receive notifications for new content' => '',
    'Enhance this space with modules.' => '',
    'Hide posts on dashboard' => '',
    'Invited By' => '',
    'Permissions are assigned to different user-roles. To edit a permission, select the user-role you want to edit and change the drop-down value of the given permission.' => '',
    'Please type the name of the space to proceed.' => '',
    'Receive Notifications for new content' => '',
    'Role' => '',
    'Show posts on dashboard' => '',
    'This option will hide new content from this space at your dashboard' => '',
    'This option will show new content from this space at your dashboard' => '',
    'e.g. example for {baseUrl}/s/example' => '',
    'never' => '',
    'the default start page of this space for members' => '',
    'the default start page of this space for visitors' => '',
];
