<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Configure' => 'Ρύθμιση',
    'Confirm' => 'Επιβεβαίωση',
    'Current password' => 'Υπάρχων κωδικός',
    'Disable' => 'Απενεργοποίηση',
    'E-Mail' => 'E-mail',
    'E-Mail change' => 'Αλλαγή e-mail',
    'Enable' => 'Ενεργοποίηση',
    'Language' => 'Γλώσσα',
    'Modules' => 'Ενότητες',
    'New E-Mail address' => 'Νέα διεύθυνση e-mail',
    'Notifications' => 'Ενημερώσεις',
    'Password Recovery' => 'Ανάκτηση κωδικού',
    'Save' => 'Αποθήκευση',
    'Save profile' => 'Αποθήκευση προφίλ',
    'Security' => 'Ασφάλεια',
    'Settings' => 'Ρυθμίσεις',
    'Tags' => 'Λέξεις κλειδιά',
    'The entered e-mail address is already in use by another user.' => 'Το e-mail που δηλώσατε είναι καταχωρημένο σε άλλο χρήστη.',
    'Users' => 'Χρήστες',
    '{attribute} "{value}" was not found!' => '{attribute} "{value}" δεν βρέθηκε!',
    '<strong>Account</strong> settings' => '',
    '<strong>Confirm</strong></strong> your new email address' => '',
    '<strong>Security</strong> settings' => '',
    '<strong>User</strong> modules' => '',
    '<strong>User</strong> settings' => '',
    '<strong>Your</strong> profile' => '',
    'All your personal data will be irrevocably deleted.' => '',
    'Are you really sure? *ALL* module data for your profile will be deleted!' => '',
    'Are you sure that you want to delete your account?' => '',
    'Changing the username can make some links unusable, for example old links to the profile.' => '',
    'Delete account' => '',
    'Do you really want to delete your icon image?' => '',
    'Do you really want to delete your logo image?' => '',
    'Enhance your profile with modules.' => '',
    'Enter your password to continue' => '',
    'Hello' => '',
    'Here you can edit your general profile data, which is visible in the about page of your profile.' => '',
    'Here you can manage your account permissions for different user-types. To edit a permission, select the user-type you want to edit and change the drop-down value of the given permission.' => '',
    'Hide introduction tour panel on dashboard' => '',
    'Invalid link! Please make sure that you entered the entire url.' => '',
    'New User name' => '',
    'Not registered users' => '',
    'Other users' => '',
    'Profile' => '',
    'Profile visibility' => '',
    'Registered users only' => '',
    'TimeZone' => '',
    'Username has been changed' => '',
    'Visible for all (also unregistered users)' => '',
    'We´ve just sent an confirmation e-mail to your new address. <br /> Please follow the instructions inside.' => '',
    'You are currently the owner of following spaces:' => '',
    'You have requested to change your e-mail address.<br>Your new e-mail address is {newemail}.<br><br>To confirm your new e-mail address please click on the button below.' => '',
    'You have successfully changed your username.<br>Your new username is {newUsername}.' => '',
    'You must transfer ownership or delete these spaces before you can delete your account.' => '',
    'Your account cannot be deleted!' => '',
    'Your current E-mail address is <b>{email}</b>. You can change your current E-mail address here.' => '',
    'Your current password can be changed here.' => '',
    'Your current username is <b>{username}</b>. You can change your current username here.' => '',
    'Your e-mail address has been successfully changed to {email}.' => '',
    'Your friends' => '',
    'Your password has been successfully changed!' => '',
    'Your username has been changed' => '',
    'Your username has been successfully changed. <br> We´ve just sent an e-mail to you with new information.' => '',
];
