<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created at' => 'Δημιουργήθηκε στις',
    'Created by' => 'Δημιουργήθηκε από',
    'Delete' => 'Διαγραφή',
    'Description' => 'Περιγραφή',
    'Follow' => 'Ακολούθησε',
    'General' => 'Γενικά',
    'Language' => 'Γλώσσα',
    'Modules' => 'Ενότητες',
    'Name' => 'Όνομα',
    'Notifications' => 'Ενημερώσεις',
    'Password' => 'Κωδικός',
    'Security' => 'Ασφάλεια',
    'Settings' => 'Ρυθμίσεις',
    'Sign up' => 'Εγγραφή',
    'Sort order' => 'Σειρά ταξινόμησης',
    'Space ID' => 'Χώρος ID',
    'Tags' => 'Λέξεις κλειδιά',
    'Unfollow' => 'Μην ακολουθείς',
    'Updated at' => 'Ανανεώθηκε στις',
    'Updated by' => 'Ανανεώθηκε από',
    'User' => 'Χρήστης',
    'Username' => 'Όνομα χρήστη',
    'Visibility' => 'Ορατότητα',
    'Welcome to %appName%' => 'Καλωσορίσατε στο %appName%',
    '<strong>Following</strong> user' => '',
    '<strong>Member</strong> in these spaces' => '',
    '<strong>User</strong> followers' => '',
    '<strong>User</strong> tags' => '',
    'Allows access to your about page with personal information' => '',
    'Auth Mode' => '',
    'Basic Settings' => '',
    'Change Email' => '',
    'Change Password' => '',
    'Change Username' => '',
    'Confirm new password' => '',
    'Connect account' => '',
    'Connected Accounts' => '',
    'Connected accounts' => '',
    'Current Password' => '',
    'Currently in use' => '',
    'Default Space' => '',
    'Delete Account' => '',
    'Disconnect account' => '',
    'E-Mail is already in use! - Try forgot password.' => '',
    'Email' => '',
    'Here you can connect to external service provider for using external services like a single sign on authentication.' => '',
    'Last Login' => '',
    'Manager' => '',
    'Missing E-Mail Attribute from AuthClient.' => '',
    'Missing ID AuthClient Attribute from AuthClient.' => '',
    'My Account' => '',
    'New password' => '',
    'No users found.' => '',
    'Permission' => '',
    'Profile' => '',
    'Profile posts only' => '',
    'Register now and participate!' => '',
    'Show At Directory' => '',
    'Show At Registration' => '',
    'Show all content' => '',
    'Sign in' => '',
    'Sign in / up' => '',
    'Sign up now' => '',
    'Source' => '',
    'Status' => '',
    'Unknown user status!' => '',
    'User has been invited.' => '',
    'User with the same email already exists but isn\'t linked to you. Login using your email first to link it.' => '',
    'Username contains invalid characters.' => '',
    'View your about page' => '',
    'Welcome to %appName%. Please click on the button below to proceed with your registration.' => '',
    'You got an invite' => '',
    'You\'re not registered.' => '',
    'You\'ve been invited to join {space} on {appName}' => '',
    'Your account is disabled!' => '',
    'Your account is not approved yet!' => '',
    'Your new password must not be equal your current password!' => '',
    'invited you to join {name}.' => '',
    'invited you to join {space} on {name}.' => '',
    'or' => '',
];
