<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Visible for all' => '@@Visible de tous@@',
    ' Invite and request' => ' Sur invitation et demande',
    'Could not delete user who is a space owner! Name of Space: {spaceName}' => 'Impossible d\'effacer un utilisateur propriétaire d\'un espace ! Espace concerné : {spaceName}',
    'Everyone can enter' => 'Tout le monde peut entrer',
    'Invite and request' => 'Sur invitation et demande',
    'Only by invite' => 'Sur invitation uniquement',
    'Private (Invisible)' => 'Privé (invisible)',
    'Public (Members & Guests)' => 'Public (membres et visiteurs)',
    'Public (Members only)' => 'Public (membres uniquement)',
    'Public (Registered users only)' => 'Public (utilisateurs enregistrés uniquement)',
    'Public (Visible)' => 'Public (visible)',
    'Visible for all (members and guests)' => 'Visite par tous (membres et visiteurs)',
];
