<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administration</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hurra!</strong> Det var alt lige nu.',
  '<strong>Modules</strong>' => '<strong>Moduler</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Som admin, kan du administrere hele platformen herfra.<br><br>Bortset fra moduler, vi vil ikke gå ind i dybdegående detajler her. Som enhver har de sin egen korte beskrivelse andetsted.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Du er lige nu i værktøjs menuer. Herfra kan du gå ind i HumHum markedsplads, hvor du kan installer et voksende nummer af værktøjer on-the-fly.<br><br>Som allerede nævnt, værktøjene udvider funktionerne og features tilgængelig på dine sider.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Du har nu lært omkring all af de mest vigtige features og indstillinger og er helt klar til at starte med at bruge platformen.<br><br>Vi håber du og alle fremtidige brugere vil nyde denne side. We ser frem til enhvert forslag og opbakning til vores projekt. Du er velkommen til at kontakte os via www.humbub.com<br><br> Stay tuned. :-)',
);
