<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> topic deletion' => '<strong>Xác nhận</strong> xóa chủ đề',
    '<strong>Edit</strong> Topic' => '<strong>Sửa</strong> Chủ đề',
    '<strong>Manage</strong> Topics' => '<strong>Quản lý</strong> Chủ đề',
    '<strong>Topic</strong> Overview' => 'Tổng quan <strong>Chủ đề</strong>',
    'Add Topic' => 'Thêm chủ đề',
    'Do you really want to delete this topic?' => 'Bạn thực sự muốn xóa chủ đề này?',
    'Topic' => 'Chủ đề',
    'Topic has been deleted!' => 'Chủ đề đã xóa!',
    'Topics' => 'Chủ đề',
    'Color' => '',
    'Name' => '',
    'Sort order' => '',
];
