<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Search</strong>' => '',
    'Could not find requested module!' => '@@Das gesuchte Modul konnte nicht gefunden werden!@@',
    'Invalid request.' => '@@Ungültige Anfrage.@@',
    'Keyword:' => '@@Suchbegriff:@@',
    'Nothing found with your input.' => '@@Nichts gefunden!@@',
    'Results' => '@@Ergebnisse@@',
    'Show more results' => '@@Mehr Ergebnisse anzeigen@@',
    'Sorry, nothing found!' => '@@Entschuldige, nichts gefunden!@@',
    'Welcome to %appName%' => '@@Willkommen bei %appName%@@',
    '<strong>Latest</strong> updates' => '<strong>Letzte</strong> Aktualisierungen',
    'Account settings' => 'Kontoeinstellungen',
    'Administration' => 'Administration',
    'Back' => 'Zurück',
    'Back to dashboard' => 'Zurück zum Dashboard',
    'Choose language:' => 'Sprache wählen:',
    'Collapse' => 'Einklappen',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => 'Die Quelle des Addons muss eine Instanz von HActiveRecordContent oder HActiveRecordContentAddon sein!',
    'Could not determine content container!' => 'Kann Content Container nicht finden.',
    'Could not find content of addon!' => 'Der Inhalt des Addons konnte nicht gefunden werden!',
    'Error' => 'Fehler',
    'Expand' => 'Erweitern',
    'Insufficent permissions to create content!' => 'Unzureichende Berechtigungen um Inhalte zu erstellen!',
    'It looks like you may have taken the wrong turn.' => 'Du hast womöglich den falschen Weg eingeschlagen.',
    'Language' => 'Sprache',
    'Latest news' => 'Neuigkeiten',
    'Login' => 'Anmelden',
    'Logout' => 'Ausloggen',
    'Menu' => 'Menü',
    'Module is not on this content container enabled!' => 'Dieses Modul ist in diesem Content Container nicht aktiviert!',
    'My profile' => 'Mein Profil',
    'New profile image' => 'Neues Profilbild',
    'Oooops...' => 'Uuuups...',
    'Search' => 'Suchen',
    'Search for users and spaces' => 'Suche nach Benutzern und Spaces',
    'Space not found!' => 'Space nicht gefunden!',
    'User Approvals' => 'Benutzerfreigaben',
    'User not found!' => 'Benutzer nicht gefunden',
    'You cannot create public visible content!' => 'Du hast nicht genügend Rechte um öffentlich sichtbaren Inhalt zu erstellen!',
    'Your daily summary' => 'Deine tägliche Übersicht',
];
