<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Warning</strong> incomplete setup!' => '',
    'Open documentation' => '',
    'The cron job for the background jobs (queue) does not seem to work properly.' => '',
    'The cron job for the regular tasks (cron) does not seem to work properly.' => '',
    'About' => 'Sobre',
    'Add purchased module by licence key' => 'Adicionar módulo comprado através de chave de licença',
    'Admin' => 'Admin',
    'Administration' => 'Administração',
    'Approval' => 'Aprovação',
    'Authentication' => 'Autenticação',
    'Back to overview' => 'Voltar para Visão Global',
    'Back to user overview' => 'Voltar para a visão global do usuário',
    'Base URL needs to begin with http:// or https://' => 'Endereço deve começar com http:// ou https://',
    'Basic' => 'Básico',
    'Caching' => 'Fazer cache',
    'Cronjobs' => 'Tarefas agendadas',
    'Design' => 'Design',
    'Files' => 'Arquivos',
    'Groups' => 'Grupos',
    'Groups (Note: The Administrator group of this user can\'t be managed with your permissions)' => 'Grupos (Nota: O grupo Administrador deste usuário não pode ser gerenciado com suas permissões)',
    'Invite' => 'Convite',
    'Invited by' => 'Convidado por',
    'Logging' => 'Registros de Log',
    'Mailing' => 'Correspondência',
    'Modules' => 'Módulos',
    'OEmbed providers' => 'Provedores Oembed',
    'Pending user registrations' => 'Registros de usuários pendentes',
    'Proxy' => 'Proxy',
    'Security' => 'Segurança',
    'Self test' => 'Auto teste',
    'Sign up' => 'Registre-se',
    'Spaces' => 'Espaços',
    'Statistics' => 'Estatísticas',
    'User posts' => 'Mensagens de usuários',
    'Userprofiles' => 'Perfis de usuário',
    'Users' => 'Usuários',
];
