<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Horizontal scrolling images on a mobile device' => '',
    'Base URL' => 'URL base',
    'Date input format' => 'Formato de data',
    'Default language' => 'Idioma padrão',
    'Default space' => 'Espaço padrão',
    'Default stream content order' => 'Orden padrão do stream',
    'Enable user friendship system' => 'Habilitar interface simplificada para o usuário.',
    'Invalid space' => 'Espaço inválido',
    'Logo upload' => 'Enviar logomarca',
    'Name of the application' => 'Nome da aplicação',
    'Server Timezone' => 'Fuso horário do servidor',
    'Show introduction tour for new users' => 'Mostrar tour de introdução para novos usuários',
    'Show user profile post form on dashboard' => 'Possibilitar ao usuário postar no painel',
    'Sort by creation date' => 'Classificar por data de criação',
    'Sort by update date' => 'Classificar por data de atualização',
];
