<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Information</strong>' => '<strong>Informação</strong>',
    '<strong>Settings</strong> and Configuration' => '<strong>Definições</strong> e Configuração',
    '<strong>User</strong> administration' => 'Administração de <strong>Usuário</strong>',
    'Active users' => 'Usuários ativos',
    'Add new group' => 'Adicionar novo grupo',
    'Add new user' => 'Adicionar novo usuário',
    'Are you really sure that you want to disable this user?' => 'Tem certeza de que deseja desabilitar esse usuário?',
    'Are you really sure that you want to enable this user?' => 'Você tem certeza de que deseja habilitar esse usuário?',
    'Are you really sure that you want to impersonate this user?' => 'Você tem certeza de que deseja se passar por esse usuário?',
    'Are you sure that you want to delete following user?' => 'Tem certeza de que deseja excluir o seguinte usuário?',
    'Cancel' => 'Cancelar',
    'Confirm user deletion' => 'Confirmar exclusão de usuário',
    'Delete all contributions of this user' => 'Excluir todas as contribuições deste usuário',
    'Delete spaces which are owned by this user' => 'Excluir espaços pertencentes a esse usuário',
    'Deleted users' => 'Usuários excluídos',
    'Disable' => 'Desabilitar',
    'Disabled users' => 'Usuários desabilitados',
    'Enable' => 'Habilitar',
    'Group Manager' => 'Gerente do Grupo',
    'Groups' => 'Grupos',
    'If this option is not selected, the ownership of the spaces will be transferred to your account.' => 'Se esta opção não estiver selecionada, a propriedade dos espaços será transferida para sua conta.',
    'Impersonate' => 'Representar',
    'Last login' => 'Último acesso',
    'List pending registrations' => 'Listar registros pendentes',
    'Manage group: {groupName}' => 'Gerenciar grupo: {groupName}',
    'Member since' => 'Membro desde',
    'Members' => 'Membros',
    'Overview' => 'Visão Global',
    'Pending approvals' => 'Aprovações pendentes',
    'Permanently delete' => 'Excluir permanentemente',
    'Permissions' => 'Permissões',
    'Profiles' => 'Perfis',
    'Search by name, email or id.' => 'Pesquise por nome, email ou id.',
    'Settings' => 'Configurações',
    'This overview contains a list of each registered user with actions to view, edit and delete users.' => 'Esta visão geral contém uma lista de cada usuário registrado com ações para visualizar, editar e excluir usuários.',
    'User deletion process queued.' => 'Processo de exclusão do usuário enfileirado.',
    'Using this option any contributions (e.g. contents, comments or likes) of this user will be irrevocably deleted.' => 'Usando essa opção, quaisquer contribuições (por exemplo, conteúdo, comentários ou curtidas) desse usuário serão irrevogavelmente excluídas.',
    'View profile' => 'Ver perfil',
    'You cannot delete yourself!' => 'Você não pode se deletar!',
    'never' => 'nunca',
];
