<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' likes this.' => '',
  'Administrator users' => '',
  'Back' => 'Terug',
  'Back to dashboard' => '',
  'Cancel' => 'Annuleren',
  'Choose a space... ' => '',
  'Close' => 'Sluiten',
  'Copyright © 2013 by humhub' => '',
  'Create account' => '',
  'Created At' => '',
  'Created By' => '',
  'Created at' => '',
  'Created by' => '',
  'Dashboard' => '',
  'Default space' => '',
  'Delete' => 'Verwijder',
  'Description' => 'Beschrijving',
  'Disable' => '',
  'Email preferences' => '',
  'Enable' => '',
  'Error' => '',
  'Follow' => '',
  'Group not found!' => '',
  'Guid' => '',
  'ID' => '',
  'Invalid content object!' => '',
  'Invalid request.' => '',
  'It looks like you may have taken the wrong turn.' => '',
  'Keyword:' => '',
  'Latest news' => '',
  'Messages' => 'Berichten',
  'Missing underlying content object!' => '',
  'Module' => '',
  'Name' => 'Naam',
  'New profile image' => 'Nieuwe profiel afbeelding',
  'Nothing found with your input.' => '',
  'Notifications' => '',
  'Oooops...' => '',
  'Post' => '',
  'Required' => 'Verplicht',
  'Save' => 'Opslaan',
  'Search' => 'Zoeken',
  'Search for users, spaces and posts' => 'Zoek naar gebruikers, spaces en posts',
  'Send' => 'Verstuur',
  'Show all messages' => 'Laat alle berichten zien',
  'Show more results' => 'Laat meer resultaten zien',
  'Sorry, nothing found!' => 'Sorry, niks gevonden!',
  'Sort order' => '',
  'Space ID or GUID' => '',
  'Spaces' => '',
  'Title' => 'Titel',
  'Unfollow' => '',
  'Updated at' => '',
  'Updated by' => '',
  'User details' => 'Gebruiker details',
  'User details new' => '',
  'User not found!' => 'Gebruiker niet gevonden',
  'Your daily summary' => '',
);
