<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '
Module successfully disabled!
' => 'Modul je uspješno onemogućen!',
    '
Module successfully enabled!
' => 'Modul je uspješno omogućen!',
    '--- Disable module: {moduleId} ---

' => '--- Onemogući modul: {moduleId} ---',
    '--- Enable module: {moduleId} ---

' => '--- Omogući modul: {moduleId} ---',
    '<strong>Activate</strong> your Professional Edition' => '<strong>Aktiviraj</strong> vašu profesionalnu verziju',
    'Add purchased module by licence key' => 'Dodajte kupljeni modul licenčnim ključem',
    'All modules are up to date!' => 'Svi moduli su ažurni!',
    'All {moduleId} module content will be deleted. Continue?' => 'Sav {moduleId} modul sadržaj će biti izbrisan. Nastaviti?',
    'Available updates' => 'Dostupna ažuriranja',
    'Browse online' => 'Pregledaj online',
    'Buy' => 'Kupi',
    'Buy (%price%)' => 'Kupi (%price%)',
    'Could not connect to licence server!' => 'Ne mogu se povezati s poslužiteljem licenci!',
    'Could not extract module!' => 'Ne mogu izdvojiti modul!',
    'Could not remove old module path!' => 'Nije moguće ukloniti staru putanju modula!',
    'Could not update licence. Error: ' => 'Nije moguće ažurirati licencu. Pogreška:',
    'Download of module failed!' => 'Preuzimanje modula nije uspjelo!',
    'Edit licence' => 'Uredi licencu',
    'If this Module is additionally marked as <strong>"Community"</strong> it is neither tested nor monitored by the HumHub project team.' => 'Ako je ovaj modul dodatno označen kao <strong>"Zajednica" </strong> projektni tim HumHub niti ga testira niti nadgleda.',
    'Include Community Modules' => 'Uključite module zajednice',
    'Include beta updates' => 'Uključite beta ažuriranja',
    'Install' => 'Instaliraj',
    'Installed' => 'Instalirano',
    'Installed version:' => 'Instalirana verzija:',
    'Installing module...' => 'Instaliram modul...',
    'Latest compatible Version:' => 'Zadnja kompatibilna verzija:',
    'Latest compatible version:' => 'Zadnja kompatibilna verzija:',
    'Latest version:' => 'Zadnja verzija:',
    'Licence Key:' => 'Licencni ključ:',
    'Licence key' => 'Ključ licence',
    'Licenced for max. {number} users.' => 'Licencirano za max. Broj korisnika: {number}.',
    'Licenced to:' => 'Licencirano za:',
    'Marketplace' => 'Trgovina',
    'Max. users:' => 'Maks. korisnika:',
    'Module directory %modulePath% is not writeable!' => 'Direktorij modula %modulePath% nije za pisanje!',
    'Module download failed! (%error%)' => 'Preuzimanje modula nije uspjelo! (%error%)',
    'Module not found or activated!
' => 'Modul nije pronađen ili aktiviran!',
    'Module not found!
' => 'Modul nije pronađen!',
    'More info' => 'Više info',
    'No compatible module version found!' => 'Nisu pronađene kompatibilne verzije modula!',
    'No license key? Find out more about the {pro} or contact us.' => 'Nemate licencni ključ? Saznajte više o {pro} ili nas kontaktirajte.',
    'No modules found!' => 'Moduli nisu pronađeni!',
    'No purchased modules found!' => 'Nisu pronađeni kupljeni moduli!',
    'Ok' => 'Ok',
    'Professional Edition is activated!' => 'Aktivirano je profesionalno izdanje!',
    'Purchases' => 'Kupovine',
    'Register' => 'Registriraj',
    'Remove licence key' => 'Uklonite ključ licence',
    'Save and update' => 'Spremi i ažuriraj',
    'Search' => 'Pretraži',
    'The HumHub project does not guarantee the functionality, quality or the continuous development of this Module.' => 'Projekt HumHub ne jamči funkcionalnost, kvalitetu ili kontinuirani razvoj ovog modula.',
    'Third-party' => 'Treća strana',
    'Third-party Modules are not covered by Professional Edition agreements.' => 'Moduli treće strane nisu obuhvaćeni sporazumima Professional Edition.',
    'Third-party disclaimer' => 'Odricanje treće strane',
    'This Module was developed by a third-party.' => 'Ovaj je modul razvila treća strana.',
    'Update' => 'Ažuriranje',
    'Updating module...' => 'Ažuriranje modula...',
    'Upgrade to Professional Edition' => 'Nadogradite na profesionalno izdanje',
    'Version:' => 'Verzija:',
    'View Changelog' => 'Pogledaj Changelog',
    'search for available modules online' => 'traži dostupne module online',
    '
No active Professional Edition license found!
' => '',
    '
PROFESSIONAL EDITION
' => '',
    '
The license could not be activated:
' => '',
    '
The license was successfully activated!

' => '',
    '
The license was successfully removed!

' => '',
];
