<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allowed file extensions' => 'İzin verilen dosya Uzantıları',
    'Convert command not found!' => 'Dönüştürme komutu bulunamadı!',
    'Got invalid image magick response! - Correct command?' => 'Boş image magick karşılığı! - Doğru komut?',
    'Hide file info (name, size) for images on wall' => 'Duvara görüntülenen dosyaların (isim, boyut) bilgilerini sakla',
    'Image Magick convert command (optional)' => 'Image Magick dönüştürme komutu (isteğe bağlı)',
    'Maximum preview image height (in pixels, optional)' => 'Maksimum görüntü önizleme yüksekliği (piksel, isteğe bağlı)',
    'Maximum preview image width (in pixels, optional)' => 'Maksimum önizleme görüntü genişliği (piksel, isteğe bağlı)',
    'Maximum upload file size (in MB)' => 'Maksimum dosya yükleme boyutu (MB türünden)',
    'Use X-Sendfile for File Downloads' => 'Dosya indirmek için X-Sendfile kullan',
];
