<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Administrative' => 'Yönetim',
    'Notify from {appName}. You were added to the group.' => '{appName} haberdar et. Gruba eklediniz.',
    'Notify from {appName}. You were removed from the group.' => '{appName} bildirimde bulunun. Gruptan kaldırıldınız.',
    'Receive Notifications for administrative events like available updates.' => 'Mevcut güncellemeler gibi yönetimsel etkinlikler için bildirimler alın.',
    'There is a new HumHub Version ({version}) available.' => 'Yeni ({version}) Humhub sürümü mevcut',
];
