<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Define here default settings for new spaces.' => 'Yeni mekanlar için varsayılan ayarları tanımla',
  'Overview' => 'Genel bakış',
  'Settings' => 'Ayarlar',
  '<strong>Manage</strong> spaces' => '<strong>Mekan</strong> Yönetimi',
  'All' => 'Hepsi',
  'Delete space' => 'Mekan sil',
  'Edit space' => 'Mekan düzenle',
  'In this overview you can find every space and manage it.' => 'Tüm mekanlar bulunabilir ve yönetilebilir.',
  'Search for space name' => 'Mekan adı için arama',
  'Search for space owner' => 'Mekan sahibi için arama',
  'Space name' => 'Mekan adı',
  'Space owner' => 'Mekan sahibi',
  'View space' => 'Mekan görüntüle',
);
