#!/usr/bin/env php
<?php

/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) 2025 HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */

use humhub\services\BootstrapService;

/**
 * @var $loader \Composer\Autoload\ClassLoader
 */
$loader = require(__DIR__ . '/vendor/autoload.php');

// Load Environment
$dotenv = Dotenv\Dotenv::createImmutable(__DIR__ . '/../', '.env');
$dotenv->safeLoad();

$humhubSrcPath = $_ENV['HUMHUB_ALIASES__HUMHUB'] ?? realpath(__DIR__ . '/../protected/humhub/');

// Load Bootstrap Helper
$loader->addClassMap(['humhub\\services\\BootstrapService' => $humhubSrcPath . '/services/BootstrapService.php']);

$bootstrap = new BootstrapService();
$bootstrap->runConsole();
