<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Following</strong> user' => 'Persone che <strong>seguo io</strong>',
    '<strong>Member</strong> in these spaces' => '<strong>Partecipa</strong> in questi space',
    '<strong>User</strong> followers' => 'Persone che <strong>mi seguono</strong>',
    '<strong>User</strong> tags' => 'Tag dell\'<strong>utente</strong>',
    'Allows access to your about page with personal information' => 'Permetti l\'accesso alla tua pagina con informazioni personali',
    'Auth Mode' => 'Modalità autenticato',
    'Basic Settings' => 'Impostazioni base',
    'Change Email' => 'Modifica email',
    'Change Password' => 'Modifica password',
    'Change Username' => 'Cambia nome utente',
    'Confirm new password' => 'Conferma nuova password',
    'Connect account' => 'Collega account',
    'Connected Accounts' => 'Account collegati',
    'Connected accounts' => 'Account collegati',
    'Created at' => 'Creato il',
    'Created by' => 'Creato da',
    'Current Password' => 'Password corrente',
    'Currently in use' => 'Al momento in uso',
    'Default Space' => 'Space predefinito',
    'Delete' => 'Cancella',
    'Delete Account' => 'Elimina Account',
    'Description' => 'Descrizione',
    'Disconnect account' => 'Disconnetti account',
    'E-Mail is already in use! - Try forgot password.' => 'Email già registrata! - Hai dimenticato la password?',
    'Email' => 'Email',
    'Follow' => 'Segui',
    'General' => 'Generale',
    'Here you can connect to external service provider for using external services like a single sign on authentication.' => 'Qui è possibile connettersi a provider di servizi esterni per utilizzare i servizi esterni come autenticazione integrata.',
    'Language' => 'Lingua',
    'Last Login' => 'Ultimo accesso',
    'Manager' => 'Responsabile',
    'Missing E-Mail Attribute from AuthClient.' => 'Attributo E-Mail mancante da AuthClient.',
    'Missing ID AuthClient Attribute from AuthClient.' => 'Attributo ID AuthClient mancante da AuthClient.',
    'Modules' => 'Moduli',
    'My Account' => 'Il mio Account',
    'Name' => 'Nome',
    'New password' => 'Nuova password',
    'No users found.' => 'Nessun utente trovato.',
    'Notifications' => 'Notifiche',
    'Password' => 'Password',
    'Permission' => 'Permessi',
    'Profile' => 'Profilo',
    'Register now and participate!' => 'Registrati adesso e partecipa!',
    'Security' => 'Sicurezza',
    'Settings' => 'Impostazioni',
    'Show At Directory' => 'Mostra negli Elenchi',
    'Show At Registration' => 'Mostra durante la registrazione',
    'Sign in' => 'Accedi',
    'Sign in / up' => 'Accedi/Iscriviti',
    'Sign up' => 'Accedi',
    'Sign up now' => 'Accedi ora',
    'Sort order' => 'Ordinamento',
    'Space ID' => 'ID spazio',
    'Status' => 'Stato',
    'Tags' => 'Tag',
    'Unfollow' => 'Non seguire più',
    'Unknown user status!' => 'Stato utente sconosciuto!',
    'Updated at' => 'Aggiornato il',
    'Updated by' => 'Aggiornato da',
    'User' => 'Utente',
    'User has been invited.' => 'L\'utente è stato invitato',
    'User with the same email already exists but isn\'t linked to you. Login using your email first to link it.' => 'Un Utente con la stessa email esiste già, ma non è collegato a te. Effettua il login utilizzando la tua email per collegarlo.',
    'Username' => 'Username',
    'Username contains invalid characters.' => 'Il nome utente contiene caratteri non validi',
    'View your about page' => 'Vedi la tua pagina di informazioni',
    'Visibility' => 'Visibilità',
    'Welcome to %appName%' => 'Benvenuto in %appName%',
    'Welcome to %appName%. Please click on the button below to proceed with your registration.' => 'Benvenuto in %appName%. Per favore clicca sul pulsante qui sotto per procedere con la registrazione.',
    'You got an invite' => 'Hai ricevuto un invito',
    'You\'re not registered.' => 'Non sei registrato',
    'You\'ve been invited to join {space} on {appName}' => 'Sei stato invitato a partecipare a {space} su {appName}.',
    'Your account is disabled!' => 'Il tuo account è disabilitato!',
    'Your account is not approved yet!' => 'Il tuo account non è ancora stato approvato!',
    'Your new password must not be equal your current password!' => 'Non puoi scegliere una password uguale alla precedente.',
    'invited you to join {name}.' => 'ti ha invitato ad unirti a {name}.',
    'invited you to join {space} on {name}.' => 'ti ha invitato ad unirti a {space} su {name}.',
    'or' => 'o',
];
