<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Notification</strong> Overview' => 'Visão geral de <strong>Notificação</strong>',
    '<strong>Notification</strong> Settings' => 'Configurações de <strong>Notificação</strong>',
    'Allow desktop notifications by default.' => 'Permitir notificações na área de trabalho por padrão.',
    'Filter' => 'Filtro',
    'In this view, you can define the default behavior for your users. These settings can be overwritten by users in their account settings page.' => 'Nessa página você pode definir o comportamento padrão para seus usuários. Essas configurações podem ser sobrescritas pelos usuários em suas páginas de configuração de conta.',
    'Mark all as seen' => 'Marcar tudo como visto',
    'Module Filter' => 'Filtro de Módulo',
    'New' => 'Novo',
    'No notifications found!' => 'Nenhuma notificação encontrada!',
    'Notifications' => 'Notificações',
    'Notifications are sent directly to your users to inform them about new activities in your network.' => 'Notificações são enviadas diretamente a seus usuários para informá-los sobre atividades em sua rede.',
    'Notifications are sent instantly to you to inform you about new activities in your network.' => 'Notificações são enviadas instantaneamente para você para informá-lo sobre novas atividades em sua rede.',
    'Open the notification dropdown menu' => 'Abrir o menu de notificação',
    'Receive \'New Content\' Notifications for the following spaces' => 'Receber notificações de \'Conteúdo Novo\' para os seguintes espaços',
    'Receive desktop notifications when you are online.' => 'Receber notificações na área de trabalho quando estiver conectado.',
    'Reset to defaults' => 'Redefinir para valores padrão',
    'Show all notifications' => 'Exibir todas as notificações',
    'The requested content is not valid or was removed!' => 'O conteúdo requisitado não é válido ou foi removido!',
    'There are no notifications yet.' => 'Não há notificações ainda',
    'This view allows you to configure your notification settings by selecting the desired targets for the given notification categories.' => 'Essa página permite que você configure suas notificações selecionando os alvos desejados para cada categoria.',
    'Type' => 'Tipo',
    'View online:' => 'Ver online:',
    '{displayName} and {displayName2}' => '{displayName} e {displayName2}',
    '{displayName} and {number} others' => '{displayName} e {number} outros',
];
