<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Warning</strong> incomplete setup!' => '',
    'Add purchased module by licence key' => '',
    'Admin' => '',
    'Approval' => '',
    'Authentication' => '',
    'Back to overview' => '',
    'Back to user overview' => '',
    'Base URL needs to begin with http:// or https://' => '',
    'Basic' => '',
    'Caching' => '',
    'Cronjobs' => '',
    'Design' => '',
    'Files' => '',
    'Groups (Note: The Administrator group of this user can\'t be managed with your permissions)' => '',
    'Invite' => '',
    'Invited by' => '',
    'Logging' => '',
    'Mailing' => '',
    'OEmbed providers' => '',
    'Open documentation' => '',
    'Pending user registrations' => '',
    'Proxy' => '',
    'Self test' => '',
    'Sign up' => '',
    'Statistics' => '',
    'The cron job for the background jobs (queue) does not seem to work properly.' => '',
    'The cron job for the regular tasks (cron) does not seem to work properly.' => '',
    'User posts' => '',
    'Userprofiles' => '',
    'Users' => '',
    'About' => 'عن',
    'Administration' => 'الإدارة',
    'Groups' => 'المجموعات',
    'Modules' => 'الموديل',
    'Security' => 'الأمان',
    'Spaces' => 'الباحات',
];
