<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Date input format' => '',
    'Default stream content order' => '',
    'Enable user friendship system' => '',
    'Horizontal scrolling images on a mobile device' => '',
    'Server Timezone' => '',
    'Sort by creation date' => '',
    'Sort by update date' => '',
    'Base URL' => 'العنوان الرئيسي للموقع',
    'Default language' => 'اللغة الإفتراضية',
    'Default space' => 'الباحة الإفتراضية',
    'Invalid space' => 'باحة خاطئة',
    'Logo upload' => 'رفع شعار الموقع',
    'Name of the application' => 'اسم النظام',
    'Show introduction tour for new users' => 'عرض دليل الموقع للأعضاء الجدد',
    'Show user profile post form on dashboard' => 'إظهار خانة كتابة موضوع جديد للصفحة الشخصية في واجهة سطح المكتب',
];
