<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Hide file info (name, size) for images on wall' => '',
  'Hide file list widget from showing files for these objects on wall.' => '',
  'Image Magick convert command (optional)' => '',
  'Maximum preview image height (in pixels, optional)' => '',
  'Maximum preview image width (in pixels, optional)' => '',
  'Allowed file extensions' => 'Extensão de arquivos permitidos',
  'Convert command not found!' => 'Não encontrado comando de conversão!',
  'Got invalid image magick response! - Correct command?' => 'Obteve uma resposta inválida na imagem mágica (magick)! - O comando está correcto?',
  'Maximum upload file size (in MB)' => 'Tamanho máximo de upload de ficheiros (em mb)',
  'Use X-Sendfile for File Downloads' => 'Usar X-Sendfile para realizar download de arquivos',
);
