<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Fetch/Update Users Automatically' => '',
  'Base DN' => 'Base DN',
  'Enable LDAP Support' => 'Activar o Suporte LDAP',
  'Encryption' => 'Ciptografia',
  'Hostname' => 'Nome do hospedeiro',
  'Login Filter' => 'Filtro de Login',
  'Password' => 'Palavra-passe',
  'Port' => 'Porta',
  'User Filer' => 'Filtro de Utilizador',
  'Username' => 'Nome de Utilizador',
  'Username Attribute' => 'Atribuição de nome de utilizador',
);
