<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Following</strong> user' => 'A felhasználó <strong>követi</strong>',
    '<strong>Member</strong> in these spaces' => '<strong>Tag</strong> ezekben a közösségekben',
    '<strong>User</strong> followers' => 'A felhasználót <strong>követi</strong>',
    '<strong>User</strong> tags' => '<strong>Felhasználó</strong> cimkék',
    'Allows access to your about page with personal information' => 'Hozzáférés biztosítása a személyes információkhoz a \'Rólam\' oldaladon',
    'Auth Mode' => 'Hitelesítés Módja',
    'Basic Settings' => 'Általános beállitások',
    'Change Email' => 'Email cím módosítása',
    'Change Password' => 'Jelszó módosítása',
    'Confirm new password' => 'Új jelszó megerősítése',
    'Connect account' => 'Fiók összekapcsolása',
    'Connected Accounts' => 'Kapcsolt fiókok',
    'Connected accounts' => 'Kapcsolt fiókok',
    'Created at' => 'Létrehozva',
    'Created by' => 'Létrehozta',
    'Current Password' => 'Jelenlegi jelszó',
    'Currently in use' => 'Jelenleg használatban',
    'Default Space' => 'Alapértelmezett közösség',
    'Delete' => 'Törlés',
    'Delete Account' => 'Fiók törlése',
    'Description' => 'Leírás',
    'Disconnect account' => 'Fiók szétkapcsolása',
    'E-Mail is already in use! - Try forgot password.' => 'Az email cím már használatban van! Próbálj visszaemlékezni a jelszóra.',
    'Email' => 'Email',
    'Follow' => 'Követés',
    'General' => 'Általános',
    'Here you can connect to external service provider for using external services like a single sign on authentication.' => 'Itt külső szolgáltatóhoz csatlakozhatsz olyan külső szolgáltatások igénybe vételéhez, mint például az egyszeri feliratkozást igénylő hitelesítés.',
    'Language' => 'Nyelv',
    'Last Login' => 'Utolsó bejelentkezés',
    'Manager' => 'Kezelő',
    'Missing E-Mail Attribute from AuthClient.' => 'Az AuthClient-ből hiányzik az email attribútum.',
    'Missing ID AuthClient Attribute from AuthClient.' => 'Az AuthClient-ből hiányzik az AuthClient azonosító attribútum.',
    'Modules' => 'Modulok',
    'My Account' => 'Fiókom',
    'Name' => 'Név',
    'New password' => 'Új jelszó',
    'No users found.' => 'Nem találhatók felhasználók.',
    'Notifications' => 'Értesítések',
    'Password' => 'Jelszó',
    'Permission' => 'Engedély',
    'Profile' => 'Profil',
    'Register now and participate!' => 'Regisztrálj és vegyél részt benne!',
    'Security' => 'Biztonság',
    'Settings' => 'Beállítások',
    'Show At Directory' => 'Mutassa a könyvtárban',
    'Show At Registration' => 'Mutassa a regisztrációnál',
    'Sign in' => 'Belépés',
    'Sign in / up' => 'Regisztráció',
    'Sign up' => 'Feliratkozás',
    'Sign up now' => 'Iratkozz fel most',
    'Sort order' => 'Rendezési sorrend',
    'Space ID' => 'A közösség azonosítója',
    'Status' => 'Státusz',
    'Tags' => 'Címkék',
    'Unfollow' => 'Követés leállítása',
    'Unknown user status!' => 'Ismeretlen felhasználói státusz!',
    'Updated at' => 'Frissítve',
    'Updated by' => 'Frissítette',
    'User' => 'Felhasználó',
    'User has been invited.' => 'Felhasználó meghívva.',
    'User with the same email already exists but isn\'t linked to you. Login using your email first to link it.' => 'Már létezik egy felhasználó ezzel az email címmel, de nincsen veled összekapcsolva. Először lépj be az email címeddel, majd össze tudod kapcsolni őket.',
    'Username' => 'Felhasználónév',
    'View your about page' => 'Láthassa az \'Rólam\' oldaladat',
    'Visibility' => 'Láthatóság',
    'Welcome to %appName%' => 'Üdvözöllek a(z) %appName% -n',
    'Welcome to %appName%. Please click on the button below to proceed with your registration.' => 'Üdvözöllek a(z) %appName% -n. Kattintsd a gombra a regisztrációd megkezdéséhez.',
    'You got an invite' => 'Meghívód érkezett',
    'You\'re not registered.' => 'Nem vagy regisztrálva.',
    'You\'ve been invited to join {space} on {appName}' => 'Meghívást kaptál, hogy csatlakozz a(z) {space} közösséghez itt: {appName}',
    'Your account is disabled!' => 'A fiókod fel van függesztve!',
    'Your account is not approved yet!' => 'A fiókod még nincs jóváhagyva!',
    'Your new password must not be equal your current password!' => 'Az új jelszavad nem egyezhet meg a jelenlegi jelszavaddal!',
    'invited you to join {name}.' => 'meghivott, hogy csatlakozz ehhez: {name}',
    'invited you to join {space} on {name}.' => 'meghivott, hogy csatlakozz ehhez: {space} itt: {name}.',
    'or' => 'vagy',
    'Change Username' => '',
    'Username contains invalid characters.' => '',
];
