<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Basic Settings' => 'Általános beállitások',
    'Change Email' => 'Email cím módosítása',
    'Change Password' => 'Jelszó módosítása',
    'Confirm new password' => 'Új jelszó megerősítése',
    'Connect account' => 'Fiók összekapcsolása',
    'Connected Accounts' => 'Kapcsolt fiókok',
    'Connected accounts' => 'Kapcsolt fiókok',
    'Crop profile background' => 'Profil háttér vágása',
    'Crop profile image' => 'Profilkép vágása',
    'Current Password' => 'Jelenlegi jelszó',
    'Currently in use' => 'Jelenleg használatban',
    'Delete' => 'Törlés',
    'Delete Account' => 'Fiók törlése',
    'Delete profile image' => 'Profilkép törlése',
    'Disconnect account' => 'Fiók szétkapcsolása',
    'E-Mail is already in use! - Try forgot password.' => 'Az email cím már használatban van! Próbálj visszaemlékezni a jelszóra.',
    'Email' => 'Email',
    'General' => 'Általános',
    'Here you can connect to external service provider for using external services like a single sign on authentication.' => 'Itt külső szolgáltatóhoz csatlakozhatsz olyan külső szolgáltatások igénybe vételéhez, mint például az egyszeri feliratkozást igénylő hitelesítés.',
    'Missing E-Mail Attribute from AuthClient.' => 'Az AuthClient-ből hiányzik az email attribútum.',
    'Missing ID AuthClient Attribute from AuthClient.' => 'Az AuthClient-ből hiányzik az AuthClient azonosító attribútum.',
    'Modules' => 'Modulok',
    'My Account' => 'Fiókom',
    'Name' => 'Név',
    'New password' => 'Új jelszó',
    'No users found.' => 'Nem találhatók felhasználók.',
    'Notifications' => 'Értesítések',
    'Password' => 'Jelszó',
    'Profile' => 'Profil',
    'Security' => 'Biztonság',
    'Settings' => 'Beállítások',
    'Sign in' => 'Belépés',
    'Sign in / up' => 'Regisztráció',
    'Unknown user status!' => 'Ismeretlen felhasználói státusz!',
    'Upload profile banner' => 'Profil banner feltöltése',
    'Upload profile image' => 'Profilkép feltöltése',
    'User' => 'Felhasználó',
    'User with the same email already exists but isn\'t linked to you. Login using your email first to link it.' => 'Már létezik egy felhasználó ezzel az email címmel, de nincsen veled összekapcsolva. Először lépj be az email címeddel, majd össze tudod kapcsolni őket.',
    'You\'re not registered.' => 'Nem vagy regisztrálva.',
    'Your account is disabled!' => 'A fiókod fel van függesztve!',
    'Your account is not approved yet!' => 'A fiókod még nincs jóváhagyva!',
    'Your new password must not be equal your current password!' => 'Az új jelszavad nem egyezhet meg a jelenlegi jelszavaddal!',
    'or' => 'vagy',
    'Change Username' => '',
];
