<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Mode' => 'Hitelesítés Módja',
    'Created at' => 'Létrehozva',
    'Created by' => 'Létrehozta',
    'Default Space' => 'Alapértelmezett közösség',
    'Description' => 'Leírás',
    'Email' => 'Email',
    'Language' => 'Nyelv',
    'Last Login' => 'Utolsó bejelentkezés',
    'Manager' => 'Kezelő',
    'Name' => 'Név',
    'Show At Directory' => 'Mutassa a könyvtárban',
    'Show At Registration' => 'Mutassa a regisztrációnál',
    'Sort order' => 'Rendezési sorrend',
    'Space ID' => 'A közösség azonosítója',
    'Status' => 'Státusz',
    'Tags' => 'Címkék',
    'Updated at' => 'Frissítve',
    'Updated by' => 'Frissítette',
    'Username' => 'Felhasználónév',
    'Visibility' => 'Láthatóság',
    'Username contains invalid characters.' => '',
];
