<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Please enter the letters from the image.' => '',
    '<strong>Join</strong> the network' => '<strong>Csatlakozás</strong> a hálózathoz',
    '<strong>Please</strong> sign in' => '<strong>Kérjük</strong> lépj be',
    '<strong>Sign</strong> up' => '<strong>Regisztráció</strong>',
    'Don\'t have an account? Join the network by entering your e-mail address.' => 'Nincs még fiókod? Csatlakozz a hálózathoz az email cimed megadásával.',
    'Forgot your password?' => 'Elfelejtetted a jelszavad?',
    'If you\'re already a member, please login with your username/email and password.' => 'Amennyiben már tag vagy, lépj be a felhasználóneveddel/emaileddel és a jelszavaddal.',
    'Login' => 'Belépés',
    'Please login with your username/email and password.' => 'Jelentkezz be a felhasználó neveddel/emaileddel és a jelszavaddal.',
    'Register' => 'Regisztráció',
    'Remember me' => 'Emlékezz rám',
    'Sign in' => 'Belépés',
    'email' => 'Email cím',
    'password' => 'Jelszó',
    'username or email' => 'Felhasználónév vagy email cím',
];
