<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Account</strong> settings' => '<strong>Hesap</strong> ayarları',
    '<strong>Confirm</strong></strong> your new email address' => 'Yeni mail adresinizi <strong>doğrulayın</strong></strong>',
    '<strong>Security</strong> settings' => '<strong>Güvenlik </strong> ayarları',
    '<strong>User</strong> modules' => '<strong>Kullanıcı</strong> modülleri',
    '<strong>User</strong> settings' => '<strong>Kullanıcı</strong> ayarları',
    '<strong>Your</strong> profile' => '<strong>Senin</strong> profilin',
    'All your personal data will be irrevocably deleted.' => 'Tüm kişisel verileriniz geri alınamaz bir şekilde silinecek.',
    'Are you really sure? *ALL* module data for your profile will be deleted!' => 'Profilindeki *TÜM* modül verileri silinmiş olacak! Emin misin?',
    'Are you sure that you want to delete your account?' => 'Hesabınızı silmek istediğinize emin misiniz?',
    'Configure' => 'Kurulum',
    'Confirm' => 'Doğrula',
    'Current password' => 'Kullandığın şifren',
    'Delete account' => 'Hesabı sil',
    'Disable' => 'Deaktif',
    'Do you really want to delete your logo image?' => 'Logo görüntüsünü silmek istiyor musun?',
    'E-Mail' => 'Email',
    'E-Mail change' => 'Mail adresi değiştir',
    'Enable' => 'Aktif',
    'Enhance your profile with modules.' => 'Profilini modüllerle genişlet.',
    'Enter your password to continue' => 'Devam etmek için şifrenizi girin',
    'Hello' => 'Merhaba',
    'Here you can edit your general profile data, which is visible in the about page of your profile.' => 'Buradan profil sayfasında görünen genel verilerinizi düzenleyebilirsiniz.',
    'Hide introduction tour panel on dashboard' => 'Kontrol panelinde tanıtım tur panelini gizle',
    'Invalid link! Please make sure that you entered the entire url.' => 'Geçersiz link! Lütfen url nin tamamını girdiğinizden emin olun.',
    'Language' => 'Dil',
    'Modules' => 'Modüller',
    'New E-Mail address' => 'Yeni mail adresi',
    'Not registered users' => 'Kayıtlı olmayan kullanıcılar',
    'Notifications' => 'Bildirimler',
    'Other users' => 'Diğer kullanıcılar',
    'Password Recovery' => 'Şifre Kurtarma',
    'Profile' => 'Profil',
    'Profile visibility' => 'Profil görünürlük',
    'Registered users only' => 'Kayıtlı kullanıcılar sadece',
    'Save' => 'Kaydet',
    'Save profile' => 'Profili kaydet',
    'Security' => 'Güvenlik',
    'Settings' => 'Ayarlar',
    'Tags' => 'Etiketler',
    'The entered e-mail address is already in use by another user.' => 'Girdiğin mail adresi zaten başka bir kullanıcı tarafından kullanımda.',
    'TimeZone' => 'Zaman Dilimi',
    'Users' => 'Kullanıcılar',
    'Visible for all (also unregistered users)' => 'Görünürlük tüm (ayrıca kayıtsız kullanıcılar için) ',
    'We´ve just sent an confirmation e-mail to your new address. <br /> Please follow the instructions inside.' => 'Yeni mail adresine bir doğrulama maili gönderdik. <br /> Lütfen içindeki adımları takip et',
    'You are currently the owner of following spaces:' => 'Şu anda aşağıdaki mekanların sahibi sizsiniz:',
    'You have requested to change your e-mail address.<br>Your new e-mail address is {newemail}.<br><br>To confirm your new e-mail address please click on the button below.' => 'Email adresini değiştirmek için istek yolladın.<br> Yeni mail adresin {newemail}.<br><br> Yeni mail adresini kabul etmek için aşağıdaki butona tıkla.',
    'You must transfer ownership or delete these spaces before you can delete your account.' => 'Hesabınızı silmeden önce sahipliği aktarmanız veya bu mekanları silmeniz gerekir.',
    'Your account cannot be deleted!' => 'Hesabınız silinemez!',
    'Your e-mail address has been successfully changed to {email}.' => 'Yeni mail adresin {email} adresi ile başarıyla değiştirildi.',
    'Your friends' => 'Arkadaşların',
    'Your password has been successfully changed!' => 'Şifren başarı ile değiştirildi!',
    '{attribute} "{value}" was not found!' => '{attribute} "{value}" bulunamadı!',
    'Changing the username can make some links unusable, for example old links to the profile.' => '',
    'Do you really want to delete your icon image?' => '',
    'Here you can manage your account permissions for different user-types. To edit a permission, select the user-type you want to edit and change the drop-down value of the given permission.' => '',
    'New User name' => '',
    'Username has been changed' => '',
    'You have successfully changed your username.<br>Your new username is {newUsername}.' => '',
    'Your current E-mail address is <b>{email}</b>. You can change your current E-mail address here.' => '',
    'Your current password can be changed here.' => '',
    'Your current username is <b>{username}</b>. You can change your current username here.' => '',
    'Your username has been changed' => '',
    'Your username has been successfully changed. <br> We´ve just sent an e-mail to you with new information.' => '',
];
