<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All your personal data will be irrevocably deleted.' => '',
    'Are you sure that you want to delete your account?' => '',
    'Delete account' => '',
    'Enter your password to continue' => '',
    'You are currently the owner of following spaces:' => '',
    'You must transfer ownership or delete these spaces before you can delete your account.' => '',
    'Your account cannot be deleted!' => '',
    '<strong>Modify</strong> your profile image' => '<strong>Profil</strong> fotoğrafını değiştir',
    '<strong>Modify</strong> your title image' => '<strong>Başlık</strong> fotoğrafını değiştir',
    '<strong>Security</strong> settings' => '<strong>Güvenlik </strong> ayarları',
    '<strong>User</strong> settings' => '<strong>Kullanıcı</strong> ayarları',
    '<strong>Your</strong> profile' => '<strong>Senin</strong> profilin',
    'E-Mail Summaries' => 'E-posta Özetleri',
    'Not registered users' => 'Kayıtlı kullanıcı yok',
    'Notifications' => 'Bildirimler',
    'Other users' => 'Diğer kullanıcılar',
    'Users' => 'Kullanıcılar',
    'Your friends' => 'Arkadaşların',
];
