<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'YouTube URL' => '',
    'About' => 'Hakkında',
    'Birthday' => 'Doğumtarihi',
    'City' => 'Şehir',
    'Country' => 'Ülke',
    'Custom' => 'Gelenek',
    'Facebook URL' => 'Facebook Adres',
    'Fax' => 'Fax',
    'Female' => 'Bayan',
    'First name' => 'Ad',
    'Flickr URL' => 'Flickr Adres',
    'Gender' => 'Cinsiyet',
    'Google+ URL' => 'Google+ Adres',
    'Hide year in profile' => 'Yılı profilde gizle',
    'Last name' => 'Soyad',
    'LinkedIn URL' => 'LinkedIn Adres',
    'MSN' => 'MSN',
    'Male' => 'Erkek',
    'Mobile' => 'Mobil',
    'MySpace URL' => 'MySpace Adres',
    'Phone Private' => 'Telefon No',
    'Phone Work' => 'İş Telefonu',
    'Skype Nickname' => 'Skype Adı',
    'State' => 'İlçe',
    'Street' => 'Cadde',
    'Title' => 'Başlık',
    'Twitter URL' => 'Twitter Adres',
    'Url' => 'Adres',
    'Vimeo URL' => 'Vimeo Adres',
    'XMPP Jabber Address' => 'XMPP Jabber Adres',
    'Xing URL' => 'Xing Adres',
    'Zip' => 'Zip',
];
