<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Warning</strong> incomplete setup!' => '',
    'Back to user overview' => '',
    'Base URL needs to begin with http:// or https://' => '',
    'Groups (Note: The Administrator group of this user can\'t be managed with your permissions)' => '',
    'Invite' => '',
    'Invited by' => '',
    'Open documentation' => '',
    'Pending user registrations' => '',
    'Sign up' => '',
    'The cron job for the background jobs (queue) does not seem to work properly.' => '',
    'The cron job for the regular tasks (cron) does not seem to work properly.' => '',
    'About' => 'O mně',
    'Add purchased module by licence key' => 'Vložit koupený modul pomocí licenčního klíče',
    'Admin' => 'Správce',
    'Administration' => 'Administrace',
    'Approval' => 'Schválit',
    'Authentication' => 'Ověřování',
    'Back to overview' => 'Zpět na přehled',
    'Basic' => 'Základní',
    'Caching' => 'Cache',
    'Cronjobs' => 'Cron',
    'Design' => 'Vzhled',
    'Files' => 'Soubory',
    'Groups' => 'Skupiny',
    'Logging' => 'Protokol',
    'Mailing' => 'Zasílání e-mailů',
    'Modules' => 'Moduly',
    'OEmbed providers' => 'Poskytovatelé obsahu',
    'Proxy' => 'Proxy',
    'Security' => 'Zabezpečení',
    'Self test' => 'Vlastní test',
    'Spaces' => 'prostor(y)',
    'Statistics' => 'Statistiky',
    'User posts' => 'Příspěvky uživatele',
    'Userprofiles' => 'Uživateleské profily',
    'Users' => 'Uživatelé',
];
