<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Admin' => '@@Administratorius@@',
    'All' => '@@Visi@@',
    'Delete user account' => '@@Ištrinti vartotojo paskyrą@@',
    'Edit user account' => '@@Redaguoti vartotojo paskyrą@@',
    'Email' => '@@Elektroninis paštas@@',
    'No' => '@@Ne@@',
    'Search for email' => '@@Ieškoti elektroninio pašto adreso@@',
    'Search for username' => '@@Ieškoti vartotojo vardo@@',
    'Username' => '@@Vartotojo vardas@@',
    'View user profile' => '@@Peržiūrėti vartotojo profilį@@',
    'Yes' => '@@Taip@@',
    '<strong>Manage</strong> users' => '<strong>Redaguoti</strong> profilio kategoriją',
    'Add new user' => 'Pridėti naują vartotoją',
    'In this overview you can find every registered user and manage him.' => 'Šioje apžvalgoje Jūs galite rasti visus registruotus vartotojus ir valdyti juos.',
    'Overview' => 'Apžvalga',
];
