<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Latest</strong> updates' => '<strong>Последние</strong> обновления',
  'Account settings' => 'Настройки аккаунта',
  'Administration' => 'Администрирование',
  'Back to dashboard' => 'Вернуться на главную',
  'Collapse' => 'Свернуть',
  'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => 'Источник Content Addon должен быть сущностью HActiveRecordContent либо HActiveRecordContentAddon!',
  'Could not determine content container!' => 'Не удалось определить оболочку контента!',
  'Could not find content of addon!' => 'Не удалось найти содержимое дополнения!',
  'Could not find requested module!' => 'Не удалось найти запрашиваемый модуль!',
  'Error' => 'Ошибка',
  'Expand' => 'Развернуть',
  'Insufficent permissions to create content!' => 'Недостаточно прав чтобы создать контент!',
  'Invalid request.' => 'Некорректный запрос.',
  'It looks like you may have taken the wrong turn.' => 'Похоже что вы сделали что-то не так.',
  'Keyword:' => 'Ключевое слово:',
  'Latest news' => 'Последние новости',
  'Logout' => 'Выйти',
  'Menu' => 'Меню',
  'Module is not on this content container enabled!' => 'Модуль не включён в этой оболочке контента',
  'My profile' => 'Мой профиль',
  'New profile image' => 'Новое изображение профиля',
  'Nothing found with your input.' => 'Ничего не найдено по вашему запросу.',
  'Oooops...' => 'Ой...',
  'Results' => 'Результаты',
  'Search' => 'Поиск',
  'Search for users and spaces' => 'Искать людей и пространства',
  'Show more results' => 'Показать больше результатов',
  'Sorry, nothing found!' => 'Извините, ничего не найдено!',
  'Space not found!' => 'Пространство не найдено!',
  'User Approvals' => 'Подтверждение пользователей',
  'User not found!' => 'Пользователь не найден!',
  'Welcome to %appName%' => 'Добро пожаловать в %appName%',
  'You cannot create public visible content!' => 'Вы не можете создать публичный контент!',
  'Your daily summary' => 'Ваш дневной итог',
);
