<?php

/**
 * @link https://www.humhub.org/
 * @copyright Copyright (c) 2017 HumHub GmbH & Co. KG
 * @license https://www.humhub.com/licences
 */

namespace humhub\commands;

use yii\helpers\Console;
use yii\helpers\VarDumper;

/**
 * Extends Yii's `asset` compress command so target bundles publish via
 * AssetManager at runtime.
 *
 * Yii's `saveTargets()` hard-codes `sourcePath = null` and writes the
 * configured `basePath`/`baseUrl` into the generated `assets-prod.php`,
 * which would make the runtime bundle serve straight from
 * `@humhub/resources` (not web-accessible). We rewrite the file after Yii
 * has written it: targets that were configured with a `sourcePath` get
 * that `sourcePath` restored and lose `basePath`/`baseUrl`, so
 * `AssetBundle::publish()` copies the resources tree to the assets mount
 * on first request.
 */
class AssetController extends \yii\console\controllers\AssetController
{
    protected function saveTargets($targets, $bundleFile)
    {
        parent::saveTargets($targets, $bundleFile);

        $config = require $bundleFile;
        $changed = false;

        foreach ($this->targets as $name => $targetConfig) {
            if (!isset($config[$name], $targetConfig['sourcePath'])) {
                continue;
            }
            $config[$name]['sourcePath'] = $targetConfig['sourcePath'];
            unset($config[$name]['basePath'], $config[$name]['baseUrl']);
            $changed = true;
        }

        if (!$changed) {
            return;
        }

        $exported = VarDumper::export($config);
        $version = date('Y-m-d H:i:s');
        $content = <<<EOD
<?php
/**
 * This file is generated by the "yii {$this->id}" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version {$version}
 */
return {$exported};
EOD;

        if (file_put_contents($bundleFile, $content, LOCK_EX) === false) {
            throw new \yii\console\Exception("Unable to write output bundle configuration at '{$bundleFile}'.");
        }

        $this->stdout("Adjusted target bundle paths for runtime publishing.\n", Console::FG_GREEN);
    }
}
