<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Do not change placeholders like {displayName} if you want them to be automatically filled by the system. To reset the email content fields with the system default, leave them empty.' => '',
    'LDAP' => '',
    'General' => 'Gennerelt',
    'Min value is 20 seconds. If not set, session will timeout after 1400 seconds (24 minutes) regardless of activity (default session timeout)' => 'Minste verdi er 20 sekunder. Hvis ikke satt, vil en session timeout etter 1400 sekunder (24 minutter), uavhengig av aktivitet (standard timeout sesjon)',
    'Only applicable when limited access for non-authenticated users is enabled. Only affects new users.' => 'Gjelder bare når begrenset tilgang for ikke-godkjente brukere er aktivert. Bare påvirker nye brukere.',
    'Save' => 'Lagre',
    'Visible for members only' => '
Synlig kun for medlemmer',
    'Visible for members+guests' => 'Synlig for medlemmer + gjester',
];
