<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '
Module successfully disabled!
' => 'Modül başarıyla devre dışı!',
    '
Module successfully enabled!
' => 'Modül başarıyla etkinleştirildi!',
    '--- Disable module: {moduleId} ---

' => '--- Modülü devre dışı bırak: {moduleId} ---',
    '--- Enable module: {moduleId} ---

' => '--- Modülü etkinleştir: {moduleId} ---',
    'Add purchased module by licence key' => 'Satın alınan lisans anahtarı ile modül ekle',
    'All modules are up to date!' => 'Tüm modüller güncel!',
    'Available updates' => 'Mevcut güncellemeler',
    'Browse online' => 'Çevrimiçi gözat',
    'Buy (%price%)' => 'Satın Al (%price%)',
    'Could not extract module!' => 'Modül çıkarılamadı!',
    'Download of module failed!' => 'Modülü indirme başarısız oldu!',
    'Install' => 'Yükle',
    'Installed' => 'Yüklendi',
    'Installed version:' => 'Yüklenen versiyon:',
    'Installing module...' => 'Modül yükleniyor ...',
    'Latest compatible Version:' => 'En son uyumlu versiyon:',
    'Latest compatible version:' => 'En son uyumlu sürüm:',
    'Latest version:' => 'Son versiyon:',
    'Licence Key:' => 'Lisans Anahtarı:',
    'Module directory %modulePath% is not writeable!' => 'Modül yolu %modulePath% yazılabilir değil!',
    'Module download failed! (%error%)' => 'Modül indirme başarısız! %error%',
    'Module not found or activated!
' => 'Modül bulunamadı veya aktif!',
    'Module not found!
' => 'Modül bulunamadı!',
    'More info' => 'Daha fazla bilgi',
    'No compatible module version found!' => 'Hiçbir uyumlu modül sürümü bulundu!',
    'No modules found!' => 'Modül bulunamadı!',
    'No purchased modules found!' => 'Satın alınan modül bulunamadı!',
    'Ok' => 'Tamam',
    'Purchases' => 'Satın Alınanlar',
    'Register' => 'Kayıt Ol',
    'Search' => 'Arama',
    'Third-party' => 'Üçüncü taraf',
    'Third-party disclaimer' => 'Üçüncü taraf reddi',
    'Update' => 'Güncelle',
    'Updating module...' => 'Modül güncelleniyor...',
    'Version:' => 'Sürüm:',
    'search for available modules online' => 'bulunabilir modül ara',
    '
No active Professional Edition license found!
' => '',
    '
PROFESSIONAL EDITION
' => '',
    '
The license could not be activated:
' => '',
    '
The license was successfully activated!

' => '',
    '
The license was successfully removed!

' => '',
    '<strong>Activate</strong> your Professional Edition' => '',
    'All {moduleId} module content will be deleted. Continue?' => '',
    'Buy' => '',
    'Could not connect to licence server!' => '',
    'Could not remove old module path!' => '',
    'Could not update licence. Error: ' => '',
    'Edit licence' => '',
    'If this Module is additionally marked as <strong>"Community"</strong> it is neither tested nor monitored by the HumHub project team.' => '',
    'Include Community Modules' => '',
    'Include beta updates' => '',
    'Licence key' => '',
    'Licenced for max. {number} users.' => '',
    'Licenced to:' => '',
    'Marketplace' => '',
    'Max. users:' => '',
    'No license key? Find out more about the {pro} or contact us.' => '',
    'Professional Edition is activated!' => '',
    'Remove licence key' => '',
    'Save and update' => '',
    'The HumHub project does not guarantee the functionality, quality or the continuous development of this Module.' => '',
    'Third-party Modules are not covered by Professional Edition agreements.' => '',
    'This Module was developed by a third-party.' => '',
    'Upgrade to Professional Edition' => '',
    'View Changelog' => '',
];
