<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Load more' => '',
    'The content has been archived.' => '',
    'The content has been deleted.' => '',
    'The content has been pinned.' => '',
    'The content has been unarchived.' => '',
    'The content has been unpinned.' => '',
    'Your last edit state has been saved!' => '',
    'Back to stream' => 'بازگشت به جریان',
    'Content with attached files' => 'محتوا با فایل‌های پیوست‌شده',
    'Created by me' => 'ایجادشده توسط من',
    'Creation time' => 'زمان ایجاد',
    'Filter' => 'فیلتر',
    'Include archived posts' => 'شامل پست‌های آرشیوشده',
    'Last update' => 'آخرین به‌روزرسانی',
    'No matches with your selected filters!' => 'هیچ مورد هم‌خوان با فیلترهای انتخابی شما یافت نشد!',
    'Nothing here yet!' => 'هنوز چیزی این‌جا نیست!',
    'Only private posts' => 'فقط پست‌های خصوصی',
    'Only public posts' => 'فقط پست‌های عمومی',
    'Posts only' => 'فقط پست‌ها',
    'Posts with links' => 'پست‌های حاوی لینک',
    'Sorting' => 'مرتب‌سازی',
    'Where I´m involved' => 'جایی که من درگیر هستم',
];
