<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Searchable' => '',
    'Created at' => 'Sukurtas',
    'Created by' => 'Sukurtas',
    'Description' => 'Aprašymas',
    'Editable' => 'Taisomas',
    'Field Type could not be changed!' => 'Negali būti keičiamas!',
    'Fieldtype' => 'Tipas',
    'ID' => 'ID',
    'Internal Name' => 'Slapyvardis',
    'Internal name already in use!' => 'Slapyvardis užimtas!',
    'Internal name could not be changed!' => 'Slapyvardis negali būti keičiamas!',
    'Invalid field type!' => 'Netinkamas tipas!',
    'LDAP Attribute' => 'LDAP',
    'Module' => 'Modulis',
    'Only alphanumeric characters allowed!' => 'Leidžiami tik raidiniai ir skaitmeniniai simboliai!',
    'Profile Field Category' => 'Kategorija',
    'Required' => 'Reikalinga',
    'Show at registration' => 'Rodyti registracijos metu',
    'Sort order' => 'Rūšiavimo tvarka',
    'Title' => 'Pavadinimas',
    'Translation Category ID' => 'Vertimo kategorija ID',
    'Type Config' => 'Tipas Confing',
    'Updated at' => 'Atnaujinta',
    'Updated by' => 'Atnaujinta',
    'Visible' => 'Matomas',
];
