<?php
/**
 * Translation: Paul (https://paul.bid) paulbid@protonmail.com
 * 
 */
return array (
  '<strong>Administration</strong>' => '<strong>Панель Управления</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Ура!</strong> Это все на сегодня.',
  '<strong>Modules</strong>' => '<strong>Управление модулями</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Будучи администратором, Вы можете управлять всем сайтом отсюда - из Панели Управления.<br><br>Помимо управления модулями, мы не будем вдаваться в подробности, так как у каждого раздела в Панели Управления есть свое краткое описание.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Слева находится основное меню Панели Управления. В частности, отсюда Вы можете получить доступ к HumHub Маркету, где Вы можете устанавливать все большее и большее количество модулей в пару кликов мышью.<br><br>Как уже упоминалось, модули расширяют возможности, доступные для сообществ, профилей или для всего сайта в целом.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Поздравляем, Вы узнали обо всех наиболее важных функциях и настройках и готовы приступить к использованию и развитию сайта.<br><br>Мы надеемся, что Вам и всем будущим пользователям понравится этот сайт. Мы с нетерпением ждём любых предложений, которые Вы хотели бы направить нам для дальнейшего развития нашего проекта. Также Вы можете поддержать нас финансово или принять участие в разработке. Не стесняйтесь обращаться к нам через www.humhub.org.<br><br>Оставайтесь с нами. 😊',
);
