<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{displayName} revoked your invitation for the space {spaceName}' => '',
    'You were added to Space {spaceName}' => 'Hozzáadtad a {spaceName} nevű közösséget.',
    '{displayName} accepted your invite for the space {spaceName}' => '{displayName} elfogadta a meghívásod a(z) {spaceName} közösségbe',
    '{displayName} approved your membership for the space {spaceName}' => '{displayName} jóváhagyta belépésedet a(z) {spaceName} közösségbe',
    '{displayName} changed your role to {roleName} in the space {spaceName}.' => '{displayName} megváltoztatta a szereped: {roleName} ebben a közösségben: {spaceName}.',
    '{displayName} declined your invite for the space {spaceName}' => '{displayName} nem fogadta el a meghívásod a {spaceName} közösségbe',
    '{displayName} declined your membership request for the space {spaceName}' => '{displayName} elutasította a tagsági kérelmed a {spaceName} közösségbe',
    '{displayName} invited you to the space {spaceName}' => '{displayName} meghívott a {spaceName} közösségbe',
    '{displayName} requests membership for the space {spaceName}' => '{displayName} kérte felvételét a {spaceName} közösségbe',
];
