<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> post deletion' => '<strong>Potvrdi</strong> brisanje objave',
    '<strong>Permalink</strong> to this post' => '@@@@',
    'Add a member to notify' => 'Dodaj člana za obaviještavanje',
    'Archived' => 'Arhivirano',
    'Back to stream' => 'Povratak na stream',
    'Cancel' => 'Poništi',
    'Cancel Edit' => 'Poništi uređivanje',
    'Content' => 'Sadržaj',
    'Content Tag with invalid contentcontainer_id assigned.' => 'Dodijeljena je oznaka za sadržaj s nevažećim contentcontainer_id.',
    'Content visibility' => 'Vidljivost sadržaja',
    'Could not delete content!' => 'Nije bilo moguće izbrisati sadržaj!',
    'Could not delete content: Access denied!' => 'Nije bilo moguće izbrisati sadržaj: Pristup je odbijen!',
    'Could not find requested content!' => 'Nije bilo moguće pronaći traženi sadržaj!',
    'Created by me' => 'Kreirao sam',
    'Creation time' => 'Vrijeme kreiranja',
    'Delete' => 'Obriši',
    'Do you really want to delete this post? All likes and comments will be lost!' => 'Želite li doista izbrisati taj post? Svi \'\'like-ovi\'\' i komentari bit će izgubljeni!',
    'Edit' => 'Uredi',
    'Filter' => 'Filter',
    'Invalid content id given!' => 'Navedeni ID sadržaj nije valjan!',
    'Invalid request method!' => 'Nevažeći način zahtjeva!',
    'Last update' => 'Zadnje ažuriranje',
    'Load more' => 'Učitaj još',
    'Make private' => 'Učini privatnim',
    'Make public' => 'Učini javnim',
    'Move content' => 'Premjesti sadržaj',
    'Move to archive' => 'Premjesti u arhivu',
    'No matches with your selected filters!' => 'Nema podudaranja s vašim postavljenim filterima!',
    'None' => 'Nijedan',
    'Nothing here yet!' => 'Još ništa ovdje!',
    'Notify members' => 'Obavijesti članove',
    'Only private content' => 'Samo privatni sadržaj',
    'Only public content' => 'Samo javni sadržaj',
    'Permalink' => '@@@@',
    'Pin to top' => 'Prikači na vrh',
    'Pinned' => 'Prikačeno',
    'Public' => 'Javno',
    'Submit' => 'Potvrdi',
    'Tag' => 'Tag',
    'Target Space' => 'Ciljani prostor',
    'The content has been archived.' => 'Sadržaj je arhiviran.',
    'The content has been deleted.' => 'Sadržaj je obrisan.',
    'The content has been unarchived.' => 'Sadržaj je dearhiviran.',
    'The given name is already in use.' => 'Navedeno ime već je u upotrebi.',
    'This action is disabled!' => 'Ova je radnja onemogućena!',
    'This space is archived.' => 'Prostor je arhiviran.',
    'This space is not visible!' => 'Ovaj prostor nije vidljiv!',
    'Topics' => 'Teme',
    'Turn off notifications' => 'Isključi obavijesti',
    'Turn on notifications' => 'Uključi obavijesti',
    'Unarchive' => 'Dearhiviraj',
    'Unpin' => 'Otkači',
    'Updated' => 'Ažurirano',
    'Your last edit state has been saved!' => 'Vaše zadnje uređeno stanje je spremljeno!',
    'in' => 'u',
    '(Also visible to non-members of this space)' => '',
    '<strong>Move</strong> content' => '',
    'Content has been moved to {spacename}' => '',
    'Invalid space selection.' => '',
    'Maximum number of pinned items reached!<br>You can only pin up to {count} items at once.' => '',
    'Specify who can see this content.' => '',
    'The author of this content is not allowed to create private content within the selected space.' => '',
    'The author of this content is not allowed to create public content within the selected space.' => '',
    'The author of this content is not allowed to create this type of content within this space.' => '',
    'The content can\'t be moved to its current space.' => '',
    'The module {moduleName} is not enabled on the selected target space.' => '',
    'This content type can\'t be moved due to a missing module-id setting.' => '',
    'This content type can\'t be moved.' => '',
    'Where I\'m involved' => '',
    'With file attachments' => '',
    'You do not have the permission to move this content to the given space.' => '',
    'You do not have the permission to move this content.' => '',
];
