<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administration</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hurra!</strong> Das wäre es für den Moment.',
  '<strong>Modules</strong>' => '<strong>Module</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Als Admin , kannst du die gesamte Plattform von hier aus verwalten. <br>Ausser den Modulen, werden wir hier nicht in jedem Punkt bis ins Detail erläutern, da jeder seine eigene kurze Beschreibung anderswo hat.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Du befindest dich im Menü <strong>Werkzeuge</strong>. Von hier aus kannst du auf den HumHub Online-Marktplatz zugreifen, wo eine immer größer werdende Anzahl von Werkzeugen zur Verfügung steht um diese on-the- fly zu installieren. <br> Wie bereits erwähnt, erhöhen die Werkzeuge , die für Ihren Space verfügbaren Funktionen .',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Du hast nun alle wichtigen Funktionen und Einstellungen eingestellt, beginnen mit der Nutzung der Plattformbeginnen. <br><br>Wir hoffen, dass du und alle zukünftigen Nutzer die Nutzung dieser Plattform zu genießen. Wir freuen uns auf Ihre Anregungen oder Unterstützung,die du für unser Projekt anbieten möchtest. Konatktiere uns über www.humhub.org. <br> Stay tuned . :-)',
);
