<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> comment deleting' => '<strong>Bekræft</strong> kommentar sletning',
    'Cancel' => 'Afbryd',
    'Comment' => 'Kommentar',
    'Comment has been deleted' => 'Kommentar er blevet slettet',
    'Comments' => 'Kommentarer',
    'Delete' => 'Slet',
    'Do you really want to delete this comment?' => 'Vil du virkelig slette denne kommentar?',
    'Edit' => 'Rediger',
    'Edit your comment...' => 'Rediger din kommentar...',
    'Read full comment...' => 'Læs fuld kommentar...',
    'Send' => 'Send',
    'Show all {total} comments' => 'Vis alle {total} kommentarer',
    'Show {count} more comments' => 'Vis {count} yderligere kommentarer',
    'The comment must not be empty!' => 'Kommentaren må ikke være tom!',
    'Whenever a new comment was written.' => 'Når som helst en ny kommentar blev skrevet.',
    'Write a new comment...' => 'Skriv en ny kommentar...',
    'comment' => 'Kommentar',
    '{displayName} wrote a new comment ' => '{displayName} skrev en ny kommentar',
    'Cancel Edit' => '',
    'Comment could not be saved!' => '',
    'Reply' => '',
    'Write a new reply...' => '',
];
