<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Save' => 'Kaydet',
  'Search' => 'Ara',
  'Search members' => 'Üyelerde ara',
  '<strong>Manage</strong> your space members' => '<strong>Mekan üyelerini</strong> yönet',
  '<strong>Outstanding</strong> sent invitations' => '<strong>Gönderilmeyi</strong> bekleyen davetler',
  '<strong>Outstanding</strong> user requests' => '<strong>Gönderilmeyi</strong> bekleyen istekler',
  '<strong>Remove</strong> member' => '<strong>Üyeyi</strong> sil',
  'Accept' => 'Onayla',
  'Allow this user to<br>invite other users' => 'Bu kullanıcının diğerlerini<br>davet etmesine izin ver',
  'Allow this user to<br>make content public' => 'Bu kullanıcının içerik<br>oluşturmasına izin ver',
  'Are you sure, that you want to remove this member from this space?' => 'Bu üyeyi mekandan silmek istediğinize emin misiniz?',
  'Can invite' => 'Davet edebilir',
  'Can share' => 'Paylaşabilir',
  'Change space owner' => 'Mekan sahibi değiştir',
  'Decline' => 'Reddet',
  'External users who invited by email, will be not listed here.' => 'Kimler eposta ile davet gönderebilir, burada listelenmez.',
  'In the area below, you see all active members of this space. You can edit their privileges or remove it from this space.' => 'Aşağıdaki mekanda aktif kullanıcılara bakın. Ayrıcalıklarını düzenleyebilir ya da kaldırabilirsiniz.',
  'Is admin' => 'Yönetici',
  'Make this user an admin' => 'Bu kullanıcıyı yönetici yap',
  'No, cancel' => 'Hayır, iptal',
  'Remove' => 'Sil',
  'Request message' => 'İstek mesajı',
  'Revoke invitation' => 'Daveti geri al',
  'Space owner' => 'Mekan sahibi',
  'The following users waiting for an approval to enter this space. Please take some action now.' => 'Aşağıdaki kullanıcılar mekana katılmak için onay bekliyor. Lütfen bir aksiyon seçin.',
  'The following users were already invited to this space, but haven\'t accepted the invitation yet.' => 'Aşağıdaki kullanıcılar zaten bu mekana davet edildi, fakat şimdiye kadar daveti takip etmediler.',
  'The space owner is the super admin of a space with all privileges and normally the creator of the space. Here you can change this role to another user.' => 'Tüm ayrıcalıklara ve süper admin yetkilerine olan mekan sahipleri ve mekan oluşturan normal kullanıcılar. Burda başka bir kullanıcı ile rolleri değiştirebilirsiniz.',
  'User' => 'Kullanıcı',
  'Yes, remove' => 'Evet, sil',
);
