<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add:' => '',
    'Could not find requested page.' => '',
    'Delete' => '',
    'Edit' => '',
    'Please type at least {count} characters' => '',
    '<strong>Confirm</strong> Action' => '<strong>Potvrdi</strong> akciju',
    '<strong>Latest</strong> updates' => '<strong>Zadnje</strong> ažuriranje',
    '<strong>Mail</strong> summary' => '<strong>Mail</strong> sažetak',
    'Account settings' => 'Postavke računa',
    'Administration' => 'Administracija',
    'Allow' => 'Dopusti',
    'An error occurred while handling your last action. (Handler not found).' => 'Došlo je do pogreške pri rukovanju vašom posljednjom radnjom. (Handler nije pronađen).',
    'An unexpected error occurred while loading the search result.' => 'Došlo je do neočekivane pogreške prilikom učitavanja rezultata pretraživanja.',
    'An unexpected error occurred. If this keeps happening, please contact a site administrator.' => 'Došlo je do neočekivane pogreške. Ako se to nastavi, kontaktirajte administratora web mjesta.',
    'An unexpected server error occurred. If this keeps happening, please contact a site administrator.' => 'Došlo je do neočekivane pogreške poslužitelja. Ako se to nastavi, kontaktirajte administratora web mjesta.',
    'An unknown error occurred while uploading.' => 'Došlo je do nepoznate pogreške prilikom prijenosa.',
    'An unknown error occurred while uploading. Hint: check your upload_max_filesize and post_max_size php settings.' => 'Došlo je do nepoznate pogreške prilikom prijenosa. Savjet: provjerite postavke php postavki upload_max_filesize i post_max_size.',
    'Back' => 'Povratak',
    'Back to dashboard' => 'Povratak na upravljačku ploču',
    'Cancel' => 'Poništi',
    'Choose language:' => 'Odaberite jezik:',
    'Close' => 'Zatvori',
    'Collapse' => 'Spusti',
    'Confirm' => 'Potvrdi',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => 'Izvor sadržaja Addon mora biti primjerak HActiveRecordContent ili HActiveRecordContentAddon!',
    'Copy to clipboard' => 'Kopirati u međuspremnik',
    'Could not find content of addon!' => 'Nije moguće pronaći sadržaj addona!',
    'Default' => 'Zadano',
    'Deny' => 'Odbiti',
    'Do you really want to perform this action?' => 'Želite li zaista uraditi ovu akciju?',
    'Error' => 'Error',
    'Error while running your last action (Invalid request method).' => 'Pogreška prilikom izvođenja zadnje radnje (nevažeći način zahtjeva).',
    'Error:' => 'Error:',
    'Expand' => 'Proširi',
    'Export' => 'Izvoz',
    'Info:' => 'Info:',
    'Invalid request method!' => 'Nevažeći način zahtjeva!',
    'It looks like you may have taken the wrong turn.' => 'Izgleda da ste se pogrešno skrenuli.',
    'Language' => 'Jezik',
    'Loading...' => 'Učitavam...',
    'Login' => 'Prijava',
    'Logo of {appName}' => 'Logo {appName}',
    'Logout' => 'Odjava',
    'Menu' => 'Izbornik',
    'Module is not enabled on this content container!' => 'Modul nije omogućen na ovom spremniku sadržaja!',
    'My profile' => 'Moj profil',
    'My profile image' => 'Moja profilna slika',
    'New profile image' => 'Nova profilna slika',
    'Next' => 'Dalje',
    'No error information given.' => 'Nema podataka o pogrešci.',
    'Oooops...' => 'Oooops...',
    'Open' => 'Otvori',
    'Please type at least 3 characters' => 'Upišite najmanje 3 znaka',
    'Profile dropdown' => 'Padajući izbornik profila',
    'Profile image of {displayName}' => 'Profilna slika od {displayName}',
    'Profile picture of {displayName}' => 'Profilna slika od {displayName}',
    'Save' => 'Spremi',
    'Saved' => 'Spremljeno',
    'Search' => 'Pretraži',
    'Select Me' => 'Izaberi mene',
    'Show less' => 'Prikaži manje',
    'Show more' => 'Prikaži više',
    'Some files could not be uploaded:' => 'Neke datoteke nisu prenesene:',
    'Text could not be copied to clipboard' => 'Tekst nije mogao biti kopiran u privremenu memoriju',
    'Text has been copied to clipboard' => 'Tekst je kopiran u privremenu memoriju',
    'The date has to be in the past.' => 'Datum mora biti u prošlosti.',
    'The file has been deleted.' => 'Datoteka je izbrisana.',
    'The requested resource could not be found.' => 'Traženi resurs nije moguće pronaći.',
    'The space has been archived.' => 'Prostor je arhiviran.',
    'The space has been unarchived.' => 'Prostor je od-arhiviran.',
    'Time Zone' => 'Vremenska zona',
    'Toggle comment menu' => 'Prebacivanje izbornika komentara',
    'Toggle panel menu' => 'Prebacivanje izbornika na ploči',
    'Toggle post menu' => 'Prelazak na izbornik posta',
    'Toggle stream entry menu' => 'Prebacivanje izbornika unosa u stream',
    'Unsubscribe' => 'Otkažite pretplatu',
    'Upload' => 'Dodaj',
    'Upload file' => 'Dodaj datoteku',
    'You are not allowed to run this action.' => 'Nije vam dozvoljena ova akcija.',
];
