<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'This group has no members yet.' => '',
    '<b>Nobody wrote something yet.</b><br>Make the beginning and post something...' => '<b>هنوز کسی چیزی ننوشته‌است.</b> <b>شروع‌کننده باشی و یک مطلب پست کنید . . </b>',
    '<b>There are no profile posts yet!</b>' => '<b>هنوز هیچ پست پروفایلی موجود نیست!</b>',
    '<strong>Directory</strong> menu' => 'منوی <strong>لیست‌ها</strong>',
    '<strong>Group</strong> members - {group}' => '<strong>{group} اعضاي گروه</strong>',
    '<strong>Group</strong> stats' => 'آمار <strong>گروه‌ها</strong>',
    '<strong>Member</strong> Group Directory' => 'آدرس گروه <strong>اعضا</strong>',
    '<strong>Member</strong> directory' => 'لیست <strong>اعضا</strong>',
    '<strong>Member</strong> stats' => 'آمار <strong>اعضا</strong>',
    '<strong>New</strong> people' => 'افراد <strong>جدید</strong>',
    '<strong>New</strong> spaces' => 'انجمن‌های <strong>جدید</strong>',
    '<strong>Space</strong> directory' => 'لیست <strong>انجمن‌ها</strong>',
    '<strong>Space</strong> stats' => 'آمار <strong>انجمن</strong>',
    'Average members' => 'کاربران متوسط',
    'Directory' => 'لیست‌ها',
    'Follows somebody' => 'کسی را دنبال می‌کند',
    'Groups' => 'گروه‌ها',
    'Members' => 'اعضا',
    'Most members' => 'اکثریت کاربران',
    'No members found!' => 'هیچ عضوی یافت نشد!',
    'No spaces found!' => 'هیچ انجمنی یافت نشد!',
    'Online right now' => 'هم‌اکنون آنلاین',
    'Private spaces' => 'انجمن‌های خصوصی',
    'Search' => 'جستجو',
    'See all' => 'مشاهده‌ی همه',
    'Send invite' => 'ارسال',
    'Spaces' => 'انجمن‌ها',
    'Top Group' => 'گروه برتر',
    'Total groups' => 'کلیه‌ی گروه‌ها',
    'Total spaces' => 'کلیه‌ی انجمن‌ها',
    'Total users' => 'کلیه‌ی کاربران',
    'User profile posts' => 'پست‌های پروفایل کاربران',
    'You are a member of this space' => 'شما عضوی از این انجمن هستید',
    'search for members' => 'جستجوی اعضا',
    'search for spaces' => 'جستحوی انجمن‌ها',
    'show all members' => 'نمایش تمامی اعضا',
];
