<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Weekly' => '',
    'Your weekly summary' => '',
    '<strong>E-Mail</strong> Summaries' => '<strong>E-Mail</strong> samenvattingen',
    'Activities' => 'Activiteiten',
    'Daily' => 'Dagelijks',
    'E-Mail Summaries' => 'E-mail samenvattingen',
    'E-Mail summaries are sent to inform you about recent activities in the network.' => 'E-mail samenvattingen informeren u over de recente activiteiten.',
    'E-Mail summaries are sent to users to inform them about recent activities in your network.' => 'E-mail samenvattingen informeren andere gebruikers over uw recente activiteiten',
    'Exclude spaces below from the mail summary' => 'Negeer de volgende ruimtes in de e-mail samenvattingen',
    'Hourly' => 'Om het uur',
    'Interval' => 'Interval',
    'Latest news' => 'Laatste nieuws',
    'Never' => 'Nooit',
    'On this page you can configure the contents and the interval of these e-mail updates.' => 'Op deze pagina kunt u de inhoud en het interval van deze e-mail updates instellen.',
    'On this page you can define the default behavior for your users. These settings can be overwritten by users in their account settings page.' => 'Op deze pagina kunt u het standaard gedrag voor uw gebruikers instellen. De gebruikers kunnen deze instellingen overschrijven op hun accountinstellingen pagina.',
    'Only include spaces below to the mail summary' => 'Alleen de volgende ruimte in de e-mail samenvatting opnemen.',
    'Reset to defaults' => 'Terugzetten naar standaardinstellingen',
    'Spaces' => 'Ruimtes',
    'You will only receive an e-mail if there is something new.' => 'U ontvangt alleen een e-mail bij nieuwe berichten.',
    'Your daily summary' => 'Uw dagelijkse samenvatting',
];
