<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to stream' => 'Retour au fil d\'actualités',
    'Content with attached files' => 'Contenu avec pièces jointes',
    'Created by me' => 'Créé par moi',
    'Creation time' => 'Date de création',
    'Filter' => 'Filtre',
    'Include archived posts' => 'Inclure les archives',
    'Last update' => 'Dernière mise à jour',
    'No matches with your selected filters!' => 'Aucun résultat.',
    'Nothing here yet!' => 'Rien à afficher actuellement.',
    'Only private posts' => 'Uniquement les publications privées',
    'Only public posts' => 'Uniquement les publications publiques',
    'Posts only' => 'Uniquement les publications',
    'Posts with links' => 'Publications avec liens',
    'Sorting' => 'Tri',
    'Where I´m involved' => 'Où je suis impliqué',
];
