<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>My</strong> friends' => '<strong>Kaverit</strong>',
    '<strong>Pending</strong> friend requests' => '<strong>Odottavat</strong> ystäväpyynnöt',
    '<strong>Sent</strong> friend requests' => '<strong>Lähetetyt</strong> ystäväpyynnöt',
    'Accept Friend Request' => 'Hyväksy ystäväpyyntö',
    'Add Friend' => 'Lisää ystävä',
    'Cancel friend request' => 'Peruuta ystäväpyyntö',
    'Deny friend request' => 'Hylkää ystäväpyyntö',
    'Friends' => 'Ystävät',
    'Friendship' => 'Ystävyys',
    'Requests' => 'Pyynnöt',
    'Sent requests' => 'Lähetetyt pyynnöt',
    'Show all friends' => 'Näytä kaikki kaverit',
    'Unfriend' => 'Ei kaveri',
];
