<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to user overview' => '',
    'Invite' => '',
    'Invited by' => '',
    'Pending user registrations' => '',
    'Sign up' => '',
    'About' => 'Informació',
    'Add purchased module by licence key' => 'Afegir mòdul adquirit per clau de llicència',
    'Admin' => 'Administrador',
    'Administration' => 'Administració',
    'Approval' => 'Aprovació',
    'Authentication' => 'Autentificació',
    'Back to overview' => 'Tornar a la vista general',
    'Basic' => 'Bàsic',
    'Caching' => 'Emmagatzematge en memòria cau (caching)',
    'Cronjobs' => 'Treballs del cron (cronjobs)',
    'Design' => 'Disseny',
    'Files' => 'Arxius',
    'Groups' => 'Grups',
    'Logging' => 'Inici de sessió',
    'Mailing' => 'Enviament de correu electrònic',
    'Modules' => 'Mòduls',
    'OEmbed providers' => 'Proveïdors OEmbed',
    'Proxy' => 'Proxy',
    'Security' => 'Seguretat',
    'Self test' => 'Auto test',
    'Spaces' => 'Espais',
    'Statistics' => 'Estadístiques',
    'User posts' => 'Publicacions de l\'usuari',
    'Userprofiles' => 'Perfils d\'usuari',
    'Users' => 'Usuaris',
];
