<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administracja</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hura!</strong> To wszystko na teraz.',
  '<strong>Modules</strong>' => '<strong>Moduły</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Jako administrator, możesz zarządzać całą platformą z tego miejsca.<br><br>Inaczej niż w modułach, nie będziemy tutaj przechodzić z punktu do punktu, jako że każdy ma swój własny krótki opis gdzie indziej.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Jesteś właśnie w menu narzędzi. Stąd możesz mieć dostęp do marketu HumHub dostępnego online, gdzie możesz instalować w locie rosnącą liczbę narzędzi.<br><br>Jak już wspomnieliśmy, narzędzia zwiększają liczbę cech dostępnych w twojej strefie.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Nauczyłeś się już wszystkich najważniejszych cech i ustawień, wszystko jest już ustawione w celu używania platformy.<br><br>Mamy nadzieję że ty i wszyscy przyszli użytkownicy będą cieszyli się z użytkowania strony. Patrzymy naprzód na każdą sugestię i wsparcie którą możesz zaoferować naszemu projektowi. Możesz skontaktować się z nami przez www.humhub.org.<br><br>Pozostań z nami. :-)',
);
