<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Default' => '默认',
    'Everyone can enter' => '所有人能加入',
    'Private' => '私有',
    'Public' => '公共',
    'Public (Members & Guests)' => '公共 (成员 & 游客)',
    'Public (Members only)' => '公共 (仅成员)',
    'Public (Registered users only)' => '公共 (仅注册用户)',
    'Visible for all (members and guests)' => '所有人可见 (成员和游客)',
    'Could not delete user who is a space owner! Name of Space: {spaceName}' => '无法删除用户，用户是版块{spaceName}的主人',
    'Invite and request' => '邀请和请求',
    'Only by invite' => '只有通过邀请',
    'Private (Invisible)' => '私有(不可见)',
    'Public (Visible)' => '公共(可见)',
    'All' => '所有人',
    'Actions' => '操作',
];
