<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Change</strong> Owner' => '<strong>更换</strong> 拥有者',
    '<strong>General</strong> settings' => '<strong>常规</strong> 设置',
    '<strong>Security</strong> settings' => '<strong>安全</strong> 设置',
    'As owner of this space you can transfer this role to another administrator in space.' => '作为这个空间的所有者，您可以将此角色传递给另一个空间中的管理员',
    'Color' => '颜色',
    'Space owner' => '空间拥有者',
    'Transfer ownership' => '转让所有权',
];
