<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Administrators' => '超级管理用户',
    'Color' => '颜色',
    'Default content visibility' => '默认内容可见性',
    'Homepage' => '首页',
    'Homepage (Guests)' => '首页 (游客)',
    'Members' => '成员',
    'Moderators' => '版主',
    'Users' => '用户',
    'Created At' => '创建于',
    'Created By' => '创建人',
    'Description' => '描述',
    'Join Policy' => '加入政策',
    'Name' => '名字',
    'Owner' => '拥有者',
    'Status' => '状态',
    'Tags' => '标签',
    'Updated At' => '修改于',
    'Updated by' => '修改人',
    'Visibility' => '可见性',
    'You cannot create private visible spaces!' => '你不能创建私有的空间',
    'You cannot create public visible spaces!' => '你不能创建公共空间',
];
