<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Adds a taskmanager to your spaces. With this module you can create and assign tasks to users in spaces.' => '',
  'Assigned to me' => '',
  'Click, to finish this task' => '',
  'Could not access task!' => '',
  'Created by me' => '',
  'Do you want to handle this task?' => '',
  'I do it!' => '',
  'My tasks' => '',
  'No tasks found which matches your current filter(s)!' => '',
  'Nobody assigned' => '',
  'State is finished' => '',
  'State is open' => '',
  'Tasks' => '',
  'There are no tasks yet!' => '',
  'This task is already done' => '',
  'This task is already done. Click to reopen.' => '',
  'You\'re not assigned to this task' => '',
  'assigned you to' => '',
  'finished' => '',
  'go to task' => '',
);
