<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Configuration</strong>' => '<strong>配置</strong>',
    'My club' => '我的俱乐部',
    'My community' => '我的社区',
    'My company (Social Intranet / Project management)' => '我的公司（社会网络/项目管理）',
    'My educational institution (school, university)' => '我的教育机构（学校，大学）',
    'Skip this step, I want to set up everything manually' => '跳过这一步，我想手动设置一切',
    'To simplify the configuration, we have predefined setups for the most common use cases with different options for modules and settings. You can adjust them during the next step.' => '为了简化配置，我们预定义了几个最常见的用例，采用了不同的选项模块和设置。你可以在稍后调整他们。',
];
