<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> Action' => '',
    '<strong>Mail</strong> summary' => '',
    'Allow' => '',
    'An error occured while handling your last action. (Handler not found).' => '',
    'An unexpected error occured while loading the search result.' => '',
    'An unexpected error occured. If this keeps happening, please contact a site administrator.' => '',
    'An unexpected server error occured. If this keeps happening, please contact a site administrator.' => '',
    'An unknown error occured while uploading.' => '',
    'An unknown error occured while uploading. Hint: check your upload_max_filesize and post_max_size php settings.' => '',
    'Close' => '',
    'Confirm' => '',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => '',
    'Copy to clipboard' => '',
    'Could not determine content container!' => '',
    'Could not find content of addon!' => '',
    'Default' => '',
    'Deny' => '',
    'Do you really want to perform this action?' => '',
    'Error while running your last action (Invalid request method).' => '',
    'Error:' => '',
    'Info:' => '',
    'It looks like you may have taken the wrong turn.' => '',
    'Loading...' => '',
    'Module is not enabled on this content container!' => '',
    'Next' => '',
    'No error information given.' => '',
    'Open' => '',
    'Please type at least 3 characters' => '',
    'Saved' => '',
    'Show less' => '',
    'Show more' => '',
    'Some files could not be uploaded:' => '',
    'The date has to be in the past.' => '',
    'The file has been deleted.' => '',
    'The requested resource could not be found.' => '',
    'The space has been archived.' => '',
    'The space has been unarchived.' => '',
    'Unsubscribe' => '',
    'Upload' => '',
    'You are not allowed to run this action.' => '',
    '<strong>Latest</strong> updates' => '<strong>Последни</strong> ъпдейти',
    'Account settings' => 'Настройки на акаунта',
    'Administration' => 'Администрация',
    'Back' => 'Назад',
    'Back to dashboard' => 'Върни се в работното място',
    'Cancel' => 'Отказ',
    'Choose language:' => 'Избери език:',
    'Collapse' => 'Свий',
    'Error' => 'Грешка',
    'Expand' => 'Разшири',
    'Language' => 'Език',
    'Login' => 'Вход',
    'Logout' => 'Изход',
    'Menu' => 'Меню',
    'My profile' => 'Моят Профил',
    'New profile image' => 'Нова профилна картинка',
    'Oooops...' => 'Опаля...',
    'Save' => 'Запази',
    'Search' => 'Търси',
    'Space not found!' => 'Зоната не е открита!',
    'User not found!' => 'Потребителя не е намерен!',
];
