<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administración</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>¡Enhorabuena!</strong> Esto es todo por ahora.',
  '<strong>Modules</strong>' => '<strong>Módulos</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Como administrador, puedes gestionar la plataforma desde aquí.<br><br>Además de los módulos, no vamos a entrar en detalle aquí, ya que cada módulo muestra su propia descripción.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Ahora te encuentras en el menú de herramientas. Desde aquí puedes acceder al Marketplace de HumHub, donde puedes instalar una cantidad cada vez mayor de módulos al instante.<br><br>Como ya se ha mencionado, los módulos incrementan las características de tu sitio.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Ahora ya has aprendido las características y los ajustes más importantes y ya estñas preparado para utilizar la plataforma.<br><br>Esperamos que tú y todos los futuros usuarios disfruten del sitio. Estamos siempre mejorando y siempre puedes enviarnos sugerencias o te podemos ofrecer soporte para tu proyecto. Siéntete libre de contactar con nosotros vía www.humhub.org.<br><br>Mantente en contacto :-)',
);
