<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administração</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Uhuuu!</strong> Isso é tudo por agora.',
  '<strong>Modules</strong>' => '<strong>Módulos</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Como administrador, você pode gerenciar toda a plataforma a partir daqui. <br> Além dos módulos, nós não estamos indo para cada ponto em detalhes, pois cada um tem a sua própria descrição em outro lugar.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Você está atualmente no menu de ferramentas. A partir daqui você pode acessar o mercado online HumHub, onde você pode instalar um número cada vez maior de ferramentas on-the-fly. <br> Como já mencionado, as ferramentas para aumentar os recursos disponíveis para o seu espaço.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Você já aprendeu sobre todas as características e configurações mais importantes e está tudo pronto para começar a utilizar a plataforma. <br> Esperamos que você e todos os futuros usuários gostem de usar este site. Nós estamos olhando para a frente e quaisquer sugestões ou apoio que desejam oferecer para o nosso projeto. Não hesite em contactar-nos através do www.humhub.org. <br> Fique atento. :-)',
);
