<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Drag a photo here or click to browse your files' => 'Arrossegar una foto aquí o feu clic per navegar pels arxius',
    'Hide my year of birth' => 'Ocultar el meu any de naixement',
    'Save and close' => 'Desar i eliminar',
    'You are the first user here... Yehaaa! Be a shining example and complete your profile,<br>so that future users know who is the top dog here and to whom they can turn to if they have questions.' => 'Vostè és el primer usuari aquí ... Yehaaa! Sigui un exemple brillant i completi el seu perfil, per a que els futurs usuaris sàpiguen qui és vosté i així podran acudir a vosté si tenen preguntes.',
    'Your firstname' => 'El teu nom',
    'Your lastname' => 'Els teus cognoms',
    'Your mobile phone number' => 'El seu número de telèfon',
    'Your phone number at work' => 'El seu número de telèfon al treball',
    'Your skills, knowledge and experience (comma seperated)' => 'Les seues habilitats, coneixements i experiència (separades per comes)',
    'Your title or position' => 'El teu títol o posició',
    'Howdy <strong>%firstname%</strong>, thank you for using %community%.' => '',
];
