<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Include captcha in registration form' => '',
    'Allow limited access for non-authenticated users (guests)' => 'Permitir acesso limitado para usuários não autenticados (convidados)',
    'Anonymous users can register' => 'Usuários anônimos podem se registrar',
    'Default content of the registration approval email' => 'Conteúdo padrão do e-mail de aprovação de registro',
    'Default content of the registration denial email' => 'Conteúdo padrão do e-mail de negação de registro',
    'Default user group for new users' => 'Grupo de usuário padrão para novos usuários',
    'Default user idle timeout, auto-logout (in seconds, optional)' => 'Tempo padrão de ócio para logout (em segundos, opcional)',
    'Default user profile visibility' => 'Visibilidade padrão do perfil do usuário',
    'Members can invite external users by email' => 'Membros podem convidar usuários externos por e-mail',
    'Require group admin approval after registration' => 'Exigir aprovação do grupo de administração após o registro',
];
