<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'You\'ve been invited to join %appName%' => '',
    '<strong>Invite</strong> new people' => '<strong>Пригласить</strong> новых пользователей',
    'Email address(es)' => 'E-mail адрес(а)',
    'Please add the email addresses of people you want to invite below.' => 'Пожалуйста, добавьте e-mail пользователей, которых вы хотите пригласить.',
    'Send invite' => 'Отправить приглашение',
    'Separate multiple email addresses by comma.' => 'Разделите e-mail адреса запятыми.',
    '{email} is already registered!' => '{email} уже зарегистрирован!',
    '{email} is not valid!' => '{email} некорректный!',
];
