<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Searchable' => 'Доступно для поиска',
    'Created at' => 'Создано в',
    'Created by' => 'Создано пользователем',
    'Description' => 'Описание',
    'Editable' => 'Доступно для редактирования',
    'Field Type could not be changed!' => 'Тип поля не может быть изменен!',
    'Fieldtype' => 'Тип поля',
    'ID' => 'ID',
    'Internal Name' => 'Внутренний Id',
    'Internal name already in use!' => 'Такой id уже используется!',
    'Internal name could not be changed!' => 'Внутренний Id невозможно будет изменить!',
    'Invalid field type!' => 'Некорректный тип поля!',
    'LDAP Attribute' => 'Атрибут LDAP',
    'Module' => 'Модуль',
    'Only alphanumeric characters allowed!' => 'Допустимы только  алфавитно-цифровые символы',
    'Profile Field Category' => 'Категория профиля',
    'Required' => 'Обязательное',
    'Show at registration' => 'Показывать при регистрации',
    'Sort order' => 'Порядок сортировки',
    'Title' => 'Заголовок',
    'Translation Category ID' => 'ID категории перевода',
    'Type Config' => 'Тип конфигурации',
    'Updated at' => 'Обновлено',
    'Updated by' => 'Обновлено пользователем',
    'Visible' => 'Видимо',
];
