<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'Par',
    'Admin' => 'Administrācija',
    'Administration' => 'Administrācija',
    'Administrative group' => 'Administrējošā grupa',
    'Advanced' => 'Izvērsti',
    'Approval' => 'Apstiprināšana',
    'Authentication' => 'Autentifikācija',
    'Back to overview' => 'Atpakaļ uz pārskatu',
    'Basic' => 'Pamata',
    'Caching' => 'Kešs',
    'Cronjobs' => 'Cronjob',
    'Design' => 'Dizains',
    'Files' => 'Faili',
    'General' => 'Galvenais',
    'Groups' => 'Grupas',
    'Logging' => 'Žurnālēšana',
    'Mailing' => 'Ziņojumi',
    'Modules' => 'Moduļi',
    'OEmbed providers' => 'OEmbed provaideri',
    'Permissions' => 'Atļaujas',
    'Proxy' => 'Proxy',
    'Security' => 'Drošība',
    'Self test' => 'Paštests',
    'Settings' => 'Uzstādījumi',
    'Spaces' => 'Vietas',
    'Statistics' => 'Statistika',
    'User posts' => 'Lietotāju ieraksti',
    'Userprofiles' => 'Lietotāju profili',
    'Users' => 'Lietotāji',
    '<strong>Administration</strong> menu' => '',
    '<strong>Module </strong> administration' => '',
    '<strong>Warning</strong> incomplete setup!' => '',
    'Appearance' => '',
    'Back to user overview' => '',
    'Base URL needs to begin with http:// or https://' => '',
    'Groups (Note: The Administrator group of this user can\'t be managed with your permissions)' => '',
    'Information' => '',
    'Invite' => '',
    'Invited by' => '',
    'Logs' => '',
    'Notifications' => '',
    'OEmbed' => '',
    'Open documentation' => '',
    'Pending user registrations' => '',
    'Sign up' => '',
    'The cron job for the background jobs (queue) does not seem to work properly.' => '',
    'The cron job for the regular tasks (cron) does not seem to work properly.' => '',
];
