<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administravimas</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Valio!</strong> Šiam kartui tiek.',
  '<strong>Modules</strong>' => '<strong>Moduliai</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Kaip administratorius, Jūs galite valdyti visą platformą iš čia. <br><br> Išskyrus modulius, kurių mes nenaudosim detaliai, todėl, kad kiekvienas turi savo trumpą aprašymą kažkur kitur.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Šiuo metu Jūs esate įrankių meniu. Iš čia Jūs galite naudotis HumHub internetine prekyviete, kur Jūs galite įsidiegti vis didėjantį įrankių skaičių tiesiog dabar. <br><br> Kaip jau buvo minėta, įrankiai išplečia funkcijų galimybes Jūsų erdvėje.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Jūs jau sužinojote viską apie svarbiausias funkcijas ir nustatymus ir viskas paruošta naudotis platforma. <br><br> Mes tikimės, kad Jūs ir visi tolesni vartotojai mėgausis šiuo tinklapiu. Mes esame atviri Jūsų pasiūlymams ar pagalbai projektams. Susisiekite su mumis www.humhub.org.<br><br> Sekite naujienas. :-)',
);
