<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'This action is disabled!' => '',
    'Could not delete content!' => 'Inhalt konnte nicht gelöscht werden!',
    'Could not delete content: Access denied!' => 'Inhalt konnte nicht gelöscht werden: Zugriff verweigert!',
    'Could not load requested object!' => 'Konnte das angeforderte Objekt nicht laden!',
    'Invalid request method!' => 'Unzulässige Anfragemethode!',
    'Maximum number of pinned items reached!

You can pin to top only two items at once.
To however pin this item, unpin another before!' => 'Das Maximum der Beiträge, die angeftet werden können, ist erreicht! Du kannst nur zwei Einträge gleichzeitig anheften. Um den Beitrag anzufheten, bitte vorher die Anheftung eines anderen Beitrages aufheben.',
];
