<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'YouTube URL' => '',
    'About' => 'À propos',
    'Birthday' => 'Date de naissance',
    'City' => 'Ville',
    'Country' => 'Pays',
    'Custom' => 'Personnalisé',
    'Facebook URL' => 'Lien Facebook',
    'Fax' => 'Fax',
    'Female' => 'Femme',
    'Firstname' => 'Prénom',
    'Flickr URL' => 'Lien Flickr',
    'Gender' => 'Genre',
    'Google+ URL' => 'Lien Google+',
    'Hide year in profile' => 'Masquer l\'année dans votre profil',
    'Lastname' => 'Nom',
    'LinkedIn URL' => 'Lien LinkedIn',
    'MSN' => 'MSN',
    'Male' => 'Homme',
    'Mobile' => 'Tel. portable',
    'MySpace URL' => 'Lien MySpace',
    'Phone Private' => 'Tel. privé',
    'Phone Work' => 'Tel. travail',
    'Skype Nickname' => 'ID Skype',
    'State' => 'Région',
    'Street' => 'Rue',
    'Title' => 'Civilité',
    'Twitter URL' => 'Lien Twitter',
    'Url' => 'Lien',
    'Vimeo URL' => 'Lien Vimeo',
    'XMPP Jabber Address' => 'Adresse XMPP/Jabber',
    'Xing URL' => 'Lien Xing',
    'Zip' => 'Code postal',
];
