<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Your new password must not be equal your current password!' => '',
    'Basic Settings' => 'Grundlegende Einstellungen',
    'Change Email' => 'E-Mail ändern',
    'Change Password' => 'Passwort ändern',
    'Confirm new password' => 'Neues Passwort bestätigen',
    'Connect account' => 'Account verbinden',
    'Connected Accounts' => 'Verbundene Accounts ',
    'Connected accounts' => 'Verbundene Accounts ',
    'Crop profile background' => 'Profilhintergrundbild zuschneiden',
    'Crop profile image' => 'Profilbild zuschneiden',
    'Current Password' => 'Derzeitiges Passwort',
    'Currently in use' => 'Zurzeit in Benutzung',
    'Delete' => 'Löschen',
    'Delete Account' => 'Account löschen',
    'Delete profile image' => 'Profilbild löschen',
    'Disconnect account' => 'Account trennen',
    'E-Mail is already in use! - Try forgot password.' => 'Diese E-Mail Adresse ist bereits registriert! - Versuche dein Passwort wiederherzustellen.',
    'Email' => 'E-Mail',
    'General' => 'Allgemein',
    'Here you can connect to external service provider for using external services like a single sign on authentication.' => 'Hier können externe Service-Anbieter angebunden werden, zum Beispiel für Single Sign On Authentifizierung.',
    'Missing E-Mail Attribute from AuthClient.' => 'Fehlenes E-Mail Attribut über AuthClient',
    'Missing ID AuthClient Attribute from AuthClient.' => 'Fehlendes AuthClient-ID Attribut über AuthClient',
    'Modules' => 'Module',
    'My Account' => 'Mein Account',
    'New password' => 'Neues Passwort',
    'No users found.' => 'Keine Benutzer gefunden.',
    'Notifications' => 'Mitteilungen',
    'Password' => 'Passwort',
    'Profile' => 'Profil',
    'Security' => 'Sicherheit',
    'Settings' => 'Einstellungen',
    'Sign in' => 'Einloggen',
    'Sign in / up' => 'An-/Abmelden',
    'Unknown user status!' => 'Unbekannter User-Status!',
    'Upload profile banner' => 'Profilhintergrundbild hochladen',
    'Upload profile image' => 'Profilbild hochladen',
    'User' => 'Benutzer',
    'User with the same email already exists but isn\'t linked to you. Login using your email first to link it.' => 'Ein Benutzer mit der selben Email-Adresse existiert bereits. Dieser ist aber nicht mit dir verknüpft. Melde dich mit deiner Email-Adresse an, um die Verkn&uuml;pfung herzustellen.',
    'You\'re not registered.' => 'Du bist noch nicht registriert.',
    'Your account is disabled!' => 'Dein Account ist deaktiviert!',
    'Your account is not approved yet!' => 'Dein Account wurde noch nicht freigeschaltet!',
    'or' => 'oder',
];
