<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Mode' => 'Authentifizierungs-Verfahren',
    'Created at' => 'Erstellt am',
    'Created by' => 'Erstellt durch',
    'Default Space' => 'Standard-Space',
    'Description' => 'Beschreibung',
    'Email' => 'E-Mail Adresse',
    'Language' => 'Sprache',
    'Last Login' => 'Zuletzt angemeldet am',
    'Manager' => 'Manager',
    'Name' => 'Name',
    'Show At Directory' => 'Im Verzeichnis anzeigen',
    'Show At Registration' => 'Bei Registrierung anzeigen',
    'Space ID' => 'Space Id',
    'Status' => 'Status',
    'Tags' => 'Tags',
    'Updated at' => 'Zuletzt geändert am',
    'Updated by' => 'Zuletzt geändert durch',
    'Username' => 'Benutzername',
    'Visibility' => 'Sichtbarkeit',
];
