<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> Action' => '',
    '<strong>Mail</strong> summary' => '',
    'An error occured while handling your last action. (Handler not found).' => '',
    'An unexpected error occured while loading the search result.' => '',
    'An unexpected error occured. If this keeps happening, please contact a site administrator.' => '',
    'An unexpected server error occured. If this keeps happening, please contact a site administrator.' => '',
    'An unknown error occured while uploading.' => '',
    'An unknown error occured while uploading. Hint: check your upload_max_filesize and post_max_size php settings.' => '',
    'Copy to clipboard' => '',
    'Do you really want to perform this action?' => '',
    'Error while running your last action (Invalid request method).' => '',
    'Error:' => '',
    'Info:' => '',
    'Loading...' => '',
    'No error information given.' => '',
    'Open' => '',
    'Show less' => '',
    'Show more' => '',
    'Some files could not be uploaded:' => '',
    'The date has to be in the past.' => '',
    'The file has been deleted.' => '',
    'The requested resource could not be found.' => '',
    'The space has been archived.' => '',
    'The space has been unarchived.' => '',
    'Unsubscribe' => '',
    'Upload' => '',
    'You are not allowed to run this action.' => '',
    '<strong>Latest</strong> updates' => '<strong>Nyeste</ strong> opdateringer',
    'Account settings' => 'Kontoindstillinger',
    'Administration' => 'Administration',
    'Allow' => 'Tillad',
    'Back' => 'Tilbage',
    'Back to dashboard' => 'Tilbage til dashboard',
    'Cancel' => 'Afbryd',
    'Choose language:' => 'Vælg sprog:',
    'Close' => 'Luk',
    'Collapse' => 'Kollaps',
    'Confirm' => 'Bekræft',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => 'Indholdskilde addon skal være del en af HActiveRecordContent eller HActiveRecordContentAddon!',
    'Could not determine content container!' => 'Kunne ikke fastslå indholdscontainer!',
    'Could not find content of addon!' => 'Kunne ikke finde addonindhold!',
    'Default' => 'Standard',
    'Deny' => 'Afslå',
    'Error' => 'Fejl',
    'Expand' => 'Udvid',
    'It looks like you may have taken the wrong turn.' => 'Det ser ud som du måske har taget den forkerte drejning.',
    'Language' => 'Sprog',
    'Login' => 'Log ind',
    'Logout' => 'Log ud',
    'Menu' => 'Menu',
    'Module is not enabled on this content container!' => 'Modulet er ikke aktiveret i denne indholdscontainer!',
    'My profile' => 'Min profil',
    'New profile image' => 'Nyt profilbillede',
    'Next' => 'Næste',
    'Oooops...' => 'Hovsa...',
    'Please type at least 3 characters' => 'Venligst indtast mindst 3 tegn',
    'Save' => 'Gem',
    'Saved' => 'Gemt',
    'Search' => 'Søg',
    'Space not found!' => 'Side ikke fundet!',
    'User not found!' => 'Bruger ikke fundet!',
];
