<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Latest</strong> updates' => '',
    'Allow' => '',
    'Back' => '',
    'Choose language:' => '',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => '',
    'Could not determine content container!' => '',
    'Default' => '',
    'Deny' => '',
    'It looks like you may have taken the wrong turn.' => '',
    'Language' => '',
    'Login' => '',
    'Next' => '',
    'Please type at least 3 characters' => '',
    'Save' => '',
    'Account settings' => 'Innstillinger',
    'Administration' => 'Administrasjon',
    'Back to dashboard' => 'Tilbake til oversikten',
    'Collapse' => 'Trekk sammen',
    'Could not find content of addon!' => 'Kunne ikke finne innhold i tillegg!',
    'Error' => 'Feil',
    'Expand' => 'Utvid',
    'Insufficent permissions to create content!' => 'Ikke tilgang til å lage innhold!',
    'Latest news' => 'Siste nytt',
    'Logout' => 'Logg ut',
    'Menu' => 'Meny',
    'Module is not on this content container enabled!' => 'Modulen er ikke aktivert for dette innholdet',
    'My profile' => 'Min profil',
    'New profile image' => 'Nytt profilbilde',
    'Oooops...' => 'Oooops...',
    'Search' => 'Søk',
    'Search for users and spaces' => 'Søk etter brukere eller områder',
    'Space not found!' => 'Fant ikke område.',
    'User Approvals' => 'Godkjenninger',
    'User not found!' => 'Fant ikke bruker.',
    'You cannot create public visible content!' => 'Du kan ikke opprette offentlig synlig innhold!',
    'Your daily summary' => 'Daglig sammendrag',
];
