<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Back to stream' => 'Повернутись до потоку',
    'Content with attached files' => 'Контент з прикріпленими файлами',
    'Created by me' => 'Створено мною',
    'Creation time' => 'Час створення',
    'Filter' => 'Фільтр',
    'Include archived posts' => 'Включено архівовані публікації',
    'Last update' => 'Останє оновлення',
    'No matches with your selected filters!' => 'Відсутнє співпадіння по вашим вибраним фільтрам!',
    'Nothing here yet!' => 'Ще нічого немає тут!',
    'Only private posts' => 'Лише приватні публікації',
    'Only public posts' => 'Лише публічні публікації',
    'Posts only' => 'Лише публікації',
    'Posts with links' => 'Публікації з посиланнями',
    'Sorting' => 'Сортувати',
    'Where I´m involved' => 'Де мене згадано',
    '<b>Nobody wrote something yet.</b><br>Make the beginning and post something...' => '@@@@',
    '<b>This profile stream is still empty</b>' => '@@@@',
    '<b>This space is still empty!</b><br>Start by posting something here...' => '@@@@',
    '<b>Your dashboard is empty!</b><br>Post something on your profile or join some spaces!' => '@@@@',
    '<b>Your profile stream is still empty</b><br>Get started and post something...' => '@@@@',
    'Nothing found which matches your current filter(s)!' => '@@@@',
    'Show all' => '@@@@',
];
