<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>CronJob</strong> Status' => '<strong>CronJob</strong> status',
    '<strong>Queue</strong> Status' => '<strong>Wachtrij</strong> status',
    'About HumHub' => 'Over',
    'Background Jobs' => 'Achtergrond taken',
    'Checking HumHub software prerequisites.' => 'Software vereisten controleren.',
    'Currently installed version: %currentVersion%' => 'Huidige versie: %currentVersion%',
    'Database' => 'Gegevensbank',
    'Database migration results:' => 'Resultaten van de gegevensbank-migratie',
    'Delayed' => 'Uitgesteld',
    'Displaying {count} entries per page.' => 'Er worden {count} berichten getoond per pagina.',
    'Done' => 'Klaar',
    'Driver' => 'Stuurprogramma',
    'Flush entries' => 'Flush berichten',
    'HumHub is currently in debug mode. Disable it when running on production!' => 'HumHub bevindt zich momenteel in de foutopsporingsmodus. Schakel dit uit wanneer u in productie draait!',
    'Last run (daily):' => 'Laatste dagelijkse run:',
    'Last run (hourly):' => 'Laatste run per uur:',
    'Licences' => 'Licenties',
    'Logging' => 'Logging',
    'Never' => 'Nooit',
    'Please refer to the documentation to setup the cronjobs and queue workers.' => 'Raadpleeg de documentatie om cronjobs in te stellen en workers in de wachtrij te zetten.',
    'Prerequisites' => 'Vereisten',
    'Queue successfully cleared.' => 'Wachtrij succesvol gewist.',
    'Re-Run tests' => 'Test opnieuw uitvoeren',
    'Reserved' => 'Wordt uitgevoerd',
    'Search index rebuild in progress.' => 'Bezig met  het opnieuw opbouwen van de zoekindex.',
    'See installation manual for more details.' => 'Bekijk de installatie handleiding voor meer info.',
    'The current main HumHub database name is ' => 'De huidige naam van de HumHub-gegevensbank is',
    'There is a new update available! (Latest version: %version%)' => 'Er is een nieuwe update beschikbaar! (Laatste versie: %version%)',
    'This HumHub installation is up to date!' => 'Deze installatie is up-to-date!',
    'Total {count} entries found.' => '{count} berichten gevonden.',
    'Waiting' => 'Aan het wachten',
];
