<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Information</strong>' => '<strong>Informatie</strong>',
    '<strong>Settings</strong> and Configuration' => '<strong>Instellingen</strong> en configuratie',
    '<strong>User</strong> administration' => '<strong>Gebruiker</strong> administratie',
    'Active users' => 'Actieve gebruikers',
    'Add new group' => 'Nieuwe groep toevoegen',
    'Add new user' => 'Voeg een nieuwe gebruiker toe',
    'Are you really sure that you want to disable this user?' => 'Weet u zeker dat u deze gebruiker wilt uitschakelen?',
    'Are you really sure that you want to enable this user?' => 'Weet u zeker dat u deze gebruiker wilt inschakelen?',
    'Are you really sure that you want to impersonate this user?' => 'Weet u zeker dat u deze gebruiker wilt imiteren?',
    'Are you sure that you want to delete following user?' => 'Weet u zeker dat u de volgende gebruiker wilt verwijderen?',
    'Cancel' => 'Annuleer',
    'Confirm user deletion' => 'Bevestig de verwijdering van de gebruiker',
    'Delete all contributions of this user' => 'Verwijder alle bijdragen van deze gebruiker',
    'Delete spaces which are owned by this user' => 'Verwijder alle ruimtes die eigendom zijn van deze gebruiker',
    'Deleted users' => 'Verwijder gebruikers',
    'Disable' => 'Deactiveer',
    'Disabled users' => 'Uitgeschakelde gebruikers',
    'Enable' => 'Activeer',
    'Group Manager' => 'Groepsmanager',
    'Groups' => 'Groepen',
    'If this option is not selected, the ownership of the spaces will be transferred to your account.' => 'Als deze optie niet is geselecteerd, wordt het eigendom van de spaties overgedragen aan uw account.',
    'Impersonate' => 'Imiteren ( wordt deze gebruiker)',
    'Last login' => 'Laatste aanmelding',
    'List pending registrations' => 'Lijst met in behandeling zijnde registraties',
    'Manage group: {groupName}' => 'Beheer groep: {groupName}',
    'Member since' => 'Lid sinds',
    'Members' => 'Leden',
    'Overview' => 'Overzicht',
    'Pending approvals' => 'Wachtende goedkeuringen',
    'Permanently delete' => 'Permanent verwijderen',
    'Permissions' => 'Machtigingen',
    'Profiles' => 'Profielen',
    'Search by name, email or id.' => 'Zoeken op naam, e-mailadres of ID.',
    'Settings' => 'Instellingen',
    'This overview contains a list of each registered user with actions to view, edit and delete users.' => 'Deze lijst toont alle geregistreerde gebruikers met opties om te bekijken, te bewerken en te verwijderen.',
    'User deletion process queued.' => 'Het verwijderen van de gebruiker is in de wachtrij geplaatst.',
    'Using this option any contributions (e.g. contents, comments or likes) of this user will be irrevocably deleted.' => 'Met behulp van deze optie worden alle bijdragen (zoals inhoud, opmerkingen of vind-ik-leuks) van deze gebruiker onherroepelijk verwijderd.',
    'View profile' => 'Bekijk profiel',
    'You cannot delete yourself!' => 'U kunt uzelf niet verwijderen!',
    'never' => 'Nooit',
];
