<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Comma separated list. Leave empty to allow all.' => '逗号分割列表。留空为允许所有。',
    'Current Image Library: {currentImageLibrary}' => '当前图片库：{currentImageLibrary}',
    'If not set, height will default to 200px.' => '如果没有设置，高度默认为200像素。',
    'If not set, width will default to 200px.' => '如果没有设置，宽度默认为200像素。',
    'PHP reported a maximum of {maxUploadSize} MB' => 'PHP最大上传大小 {maxUploadSize} MB',
    'Save' => '保 存',
];
