<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> Action' => '',
    '<strong>Mail</strong> summary' => '',
    'An error occured while handling your last action. (Handler not found).' => '',
    'An unexpected error occured while loading the search result.' => '',
    'An unexpected error occured. If this keeps happening, please contact a site administrator.' => '',
    'An unexpected server error occured. If this keeps happening, please contact a site administrator.' => '',
    'Cancel' => '',
    'Close' => '',
    'Confirm' => '',
    'Copy to clipboard: Ctrl/Cmd+C' => '',
    'Do you really want to perform this action?' => '',
    'Error while running your last action (Invalid request method).' => '',
    'Loading...' => '',
    'No error information given.' => '',
    'Open' => '',
    'Saved' => '',
    'Show less' => '',
    'Some files could not be uploaded:' => '',
    'The file has been deleted.' => '',
    'The requested resource could not be found.' => '',
    'The space has be archived.' => '',
    'The space has be unarchived.' => '',
    'You are not allowed to run this action.' => '',
    '<strong>Latest</strong> updates' => 'Atualizações',
    'Account settings' => 'Configurações da conta',
    'Administration' => 'Administração',
    'Allow' => 'Permitir',
    'Back' => 'Voltar',
    'Back to dashboard' => 'Voltar para o painel',
    'Choose language:' => 'Escolha o idioma:',
    'Collapse' => 'Minimizar',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => 'Conteúdo fonte Addon deve ser instância de HActiveRecordContent ou HActiveRecordContentAddon!',
    'Could not determine content container!' => 'Não foi possível determinar o conteúdo!',
    'Could not find content of addon!' => 'Não foi possível encontrar o conteúdo !',
    'Default' => 'Padrão',
    'Deny' => 'Recusar',
    'Error' => 'Erro',
    'Expand' => 'Expandir',
    'It looks like you may have taken the wrong turn.' => 'Parece que você pode ter tomado o caminho errado.',
    'Language' => 'Língua',
    'Login' => 'Login',
    'Logout' => 'Sair',
    'Menu' => 'Menu',
    'Module is not enabled on this content container!' => 'O módulo não está habilitado para este container!',
    'My profile' => 'Meu perfil',
    'New profile image' => 'Nova imagem de perfil',
    'Next' => 'Avançar',
    'Oooops...' => 'Oooops...',
    'Please type at least 3 characters' => 'Por favor digite pelo menos 3 caracteres',
    'Save' => 'Salvar',
    'Search' => 'Busca',
    'Show more' => 'Mostrar mais',
    'Space not found!' => 'Espaço não encontrado!',
    'The date has to be in the past.' => 'A data tem de ser no passado.',
    'Unsubscribe' => 'Desinscrever',
    'User not found!' => 'Usuário não encontrado!',
];
