<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Guest mode not active, please login first.' => '',
    'Login required for this section.' => '',
    'You are not permitted to access this section.' => '',
    'You need admin permissions to access this section.' => '',
    'Your user account has not been approved yet, please try again later or contact a network administrator.' => '',
    'Your user account is inactive, please login with an active account or contact a network administrator.' => '',
    '<strong>Login</strong> required' => '<strong>Login</strong> Requerido',
    'An internal server error occurred.' => 'Ocorreu um erro interno no servidor.',
    'You are not allowed to perform this action.' => 'Você não tem permissão para executar esta ação.',
];
