<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Remove from space' => '',
    'Show all' => '',
    'As owner of this space you can transfer this role to another administrator in space.' => 'Là chủ sở hữu của KGLV này bạn có thể chuyển nhượng quyền này cho người quản trị khác thuộc cùng KGLV.',
    'Space owner' => 'Chủ sở hữu KGLV',
    'The url contains illegal characters!' => 'Địa chỉ URL chứa ký tự không hợp lệ!',
    'Transfer ownership' => 'Chuyển nhượng quyền sở hữu',
    'e.g. example for {baseUrl}/s/example' => 'ví dụ {baseUrl}/s/example',
    'the default start page of this space for members' => 'trang chủ mặc định của KGLV này dành cho thành viên',
    'the default start page of this space for visitors' => 'trang chủ mặc định của KGLV này dành cho khách thăm',
];
