<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel Membership' => 'Hủy quyền thành viên',
    'Don\'t receive notifications for new content' => 'Không nhận thông báo về nội dung mới',
    'Hide posts on dashboard' => 'Ẩn post trên trang chính',
    'Members' => 'Thành viên',
    'Modules' => 'Modules',
    'Receive Notifications for new content' => 'Nhận thông báo cho nội dung mới',
    'Security' => 'Bảo mật',
    'Show posts on dashboard' => 'Hiển thị post trên trang chính',
    'This option will hide new content from this space at your dashboard' => 'Lựa chọn này sẽ ẩn nội dung mới từ KGLV này trên trang chính của bạn',
    'This option will show new content from this space at your dashboard' => 'Lựa chọn này sẽ hiện nội dung mới từ KGLV này trên trang chính của bạn',
];
