<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> comment deleting' => '<strong>Potwierdź</strong> usunięcie komentarza',
    'Access denied!' => 'Odmowa dostępu!',
    'Cancel' => 'Anuluj',
    'Cancel Edit' => 'Anuluj Edycję',
    'Comment' => 'Komentuj ',
    'Comment has been deleted' => 'Komentarz został usunięty',
    'Comments' => 'Komentarze ',
    'Delete' => 'Usuń',
    'Do you really want to delete this comment?' => 'Czy naprawdę chcesz usunąć ten komentarz?',
    'Edit' => 'Edytuj',
    'Edit your comment...' => 'Edytuj swój komentarz... ',
    'Insufficent permissions!' => 'Uprawnienia niedostateczne!',
    'Read full comment...' => 'Przeczytał cały komentarz...',
    'Send' => 'Wyślij',
    'Show all {total} comments.' => 'Pokaż wszystkie {total} komentarze. ',
    'Show {count} more comments' => 'Pokaż {count} kolejnych komentarzy',
    'The comment must not be empty!' => 'Komentarz nie może być pusty!',
    'Whenever a new comment was written.' => 'Za każdym razem gdy zostanie napisany nowy komentarz.',
    'Write a new comment...' => 'Napisz nowy komentarz... ',
    'You are not allowed to comment.' => 'Nie jesteś uprawniony do komentowania.',
    'comment' => 'Komentarz ',
    '{displayName} wrote a new comment ' => '{displayName} napisał(a) nowy komentarz ',
    'Reply' => '',
    'Write a new reply...' => '',
];
