<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Following</strong> user' => '<strong>Theo</strong> user',
    '<strong>Member</strong> in these spaces' => '<strong>Thành viên</strong> trong những diễn đàn này',
    '<strong>User</strong> followers' => 'Người theo <strong>User</strong>',
    '<strong>User</strong> tags' => 'Thẻ <strong>Người dùng</strong> (tags)',
    'Allows access to your about page with personal information' => 'Cho phép truy cập tới trang giới thiệu của bạn kèm thông tin cá nhân',
    'Auth Mode' => 'Chế độ xác thực',
    'Basic Settings' => 'Thiết lập cơ bản',
    'Change Email' => 'Đổi Email',
    'Change Password' => 'Đổi mật khẩu',
    'Change Username' => 'Đổi Username',
    'Confirm new password' => 'Xác nhận mật khẩu mới',
    'Connect account' => 'Kết nối tài khoản',
    'Connected Accounts' => 'Tài khoản được kết nối',
    'Connected accounts' => 'Tài khoản được kết nối',
    'Created at' => 'Tạo lúc',
    'Created by' => 'Tạo bởi',
    'Current Password' => 'Mật khẩu hiện tại',
    'Currently in use' => 'Đang được sử dụng',
    'Default Space' => 'Nhóm mặc định',
    'Delete' => 'Xóa',
    'Delete Account' => 'Xóa tài khoản',
    'Description' => 'Miêu tả',
    'Disconnect account' => 'Ngưng kết nối tài khoản',
    'E-Mail is already in use! - Try forgot password.' => 'E-Mail đã được sử dụng! - Hãy thử "quên mật khẩu"',
    'Email' => 'Email',
    'Follow' => 'Theo dõi',
    'General' => 'Chung',
    'Here you can connect to external service provider for using external services like a single sign on authentication.' => 'Ở đây bạn có thể kết nối tới nhà cung cấp dịch vụ bên ngoài để sử dụng các dịch vụ ngoài khác như: Dịch vụ đăng nhập một cửa (SSO)',
    'Language' => 'Ngôn ngữ',
    'Last Login' => 'Lần đăng nhập cuối',
    'Manager' => 'Người quản lý',
    'Missing E-Mail Attribute from AuthClient.' => 'Thiếu thuộc tính E-Mail trong AuthClient.',
    'Missing ID AuthClient Attribute from AuthClient.' => 'Thiếu thuộc tính ID AuthClient trong AuthClient',
    'Modules' => 'Modules',
    'My Account' => 'Tài khoản của tôi',
    'Name' => 'Tên',
    'New password' => 'Mật khẩu mới',
    'No users found.' => 'Không tìm thấy users nào.',
    'Notifications' => 'Thông báo',
    'Password' => 'Mật khẩu',
    'Permission' => 'Phân quyền',
    'Profile' => 'Hồ sơ',
    'Register now and participate!' => 'Đăng ký ngay và tham gia!',
    'Security' => 'Bảo mật',
    'Settings' => 'Cấu hình',
    'Show At Directory' => 'Hiện ở Thư mục chính',
    'Show At Registration' => 'Hiện lúc đăng ký',
    'Sign in' => 'Đăng nhập',
    'Sign in / up' => 'Đăng nhập/Đăng ký',
    'Sign up' => 'Đăng ký',
    'Sign up now' => 'Đăng ký ngay',
    'Sort order' => 'Thứ tự sắp xếp',
    'Space ID' => 'ID diễn đàn',
    'Status' => 'Trạng thái',
    'Tags' => 'Thẻ',
    'Unfollow' => 'Ngừng theo dõi',
    'Unknown user status!' => 'Không rõ trạng thái người dùng!',
    'Updated at' => 'Cập nhật lúc',
    'Updated by' => 'Cập nhật bởi',
    'User' => 'Người dùng',
    'User has been invited.' => 'Người dùng đã được mời.',
    'User with the same email already exists but isn\'t linked to you. Login using your email first to link it.' => 'Người dùng với cùng địa chỉ email đã tồn tại nhưng không được liên kết tới bạn. Đăng nhập sử dụng email trước để tạo liên kết.',
    'Username' => 'Tên truy cập',
    'Username contains invalid characters.' => 'Username chứa ký tự không hợp lệ',
    'View your about page' => 'Xem trang giới thiệu của bạn',
    'Visibility' => 'Hiển thị',
    'Welcome to %appName%' => 'Chào mừng bạn đến với %appName%',
    'Welcome to %appName%. Please click on the button below to proceed with your registration.' => 'Chào mừng bạn đến với %appName%. Vui lòng click nút dưới đây để tiến hành đăng ký.',
    'You got an invite' => 'Bạn nhận được một lời mời',
    'You\'re not registered.' => 'Bạn chưa đăng ký.',
    'You\'ve been invited to join {space} on {appName}' => 'Bạn đã được mời tham gia diễn đàn {space} trên {appName}',
    'Your account is disabled!' => 'Tài khoản của bạn bị vô hiệu hóa!',
    'Your account is not approved yet!' => 'Tài khoản của bạn chưa được quản trị hệ thống xét duyệt!',
    'Your new password must not be equal your current password!' => 'Mật khẩu mới không được trùng với mật khẩu hiện tại!',
    'invited you to join {name}.' => 'đã mời bạn tham gia {name}.',
    'invited you to join {space} on {name}.' => 'đã mời bạn tham gia diễn đàn {space} trên {name}.',
    'or' => 'hoặc',
];
