<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Must contain at least one character.' => '',
    'Created at' => 'Tạo lúc',
    'Created by' => 'Tạo bởi',
    'Description' => 'Miêu tả',
    'Editable' => 'Có thể chỉnh sửa',
    'Field Type could not be changed!' => 'Không thể thay đổi Kiểu Trường',
    'Fieldtype' => 'Kiểu Trường',
    'ID' => 'ID',
    'Internal Name' => 'Tên nội bộ',
    'Internal name already in use!' => 'Tên nội bộ đã được sử dụng!',
    'Internal name could not be changed!' => 'Không thể thay đổi Tên nội bộ',
    'Invalid field type!' => 'Kiểu trường không hợp lệ!',
    'LDAP Attribute' => 'Thuộc tính LDAP',
    'Module' => 'Module',
    'Only alphanumeric characters allowed!' => 'Chỉ cho phép ký tự chữ và số!',
    'Profile Field Category' => 'Loại trường thông tin Hồ sơ cá nhân',
    'Required' => 'Bắt buộc',
    'Searchable' => 'Có thể tìm kiếm',
    'Show at registration' => 'Hiển thị lúc đăng ký',
    'Sort order' => 'Thứ tự sắp xếp',
    'Title' => 'Tiêu đề',
    'Translation Category ID' => 'ID chuyên mục dịch thuật',
    'Type Config' => 'Cấu hình kiểu',
    'Updated at' => 'Cập nhật lúc',
    'Updated by' => 'Cập nhật bởi',
    'Visible' => 'Có thể thấy',
];
