<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Must contain at least one character.' => '',
    'Created at' => 'ایجادشده در',
    'Created by' => 'ایجادشده توسط',
    'Description' => 'توضیحات',
    'Editable' => 'قابل ویرایش',
    'Field Type could not be changed!' => 'نوع فیلد قابل تغییر نیست!',
    'Fieldtype' => 'نوع فیلد',
    'ID' => 'شناسه',
    'Internal Name' => 'نام داخلی',
    'Internal name already in use!' => 'نام داخلی در حال استفاده است!',
    'Internal name could not be changed!' => 'نام داخلی قابل تغییر نیست!',
    'Invalid field type!' => 'نوع فیلد نامعتبر است!',
    'LDAP Attribute' => 'صفت LDAP',
    'Module' => 'ماژول',
    'Only alphanumeric characters allowed!' => 'تنها کاراکترهای عددی و الفبایی مجاز است!',
    'Profile Field Category' => 'گروه فیلد پروفایل',
    'Required' => 'مورد نیاز',
    'Searchable' => 'قابل جستجو',
    'Show at registration' => 'نمایش در ثبت‌نام',
    'Sort order' => 'ترتیب مرتب‌سازی',
    'Title' => 'عنوان',
    'Translation Category ID' => 'شناسه‌ی گروه ترجمه',
    'Type Config' => 'تنظیمات نوع',
    'Updated at' => 'به‌روزرسانی‌شده در',
    'Updated by' => 'به‌روزرسانی‌شده توسط',
    'Visible' => 'قابل نمایش',
];
