<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Authentication mode' => '@@حالت تایید هویت@@',
    'Created At' => '@@ایجادشده در@@',
    'Created by' => '@@ایجادشده توسط@@',
    'Email' => '@@ایمیل@@',
    'Group' => '@@گروه@@',
    'Guid' => '@@راهنما@@',
    'ID' => '@@شناسه@@',
    'Invalid language!' => '@@زبان نامعتبر!@@',
    'Language' => '@@زبان@@',
    'Tags' => '@@تگ‌ها@@',
    'Updated at' => '@@به‌روزرسانی‌شده در@@',
    'Updated by' => '@@به‌روزرسانی‌شده توسط@@',
    'Username' => '@@نام کاربری@@',
    'Username can contain only letters, numbers, spaces and special characters (+-._)' => '@@نام کاربری می‌تواند تنها شامل حروف، اعداد، فاصله و یا کاراکترهای خاص باشد (+ـ۰-)@@',
    'Visibility' => '@@قابلیت مشاهده@@',
    'Wall' => '@@صفحه‌ی اعلانات@@',
    'New user needs approval' => 'کاربر جدید نیاز به تایید دارد',
];
