<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Administration</strong> menu' => '<strong>Administrations-</strong>Menü',
    '<strong>Module </strong> administration' => '<strong>Modul</strong>-Administration',
    '<strong>Warning</strong> incomplete setup!' => '<strong>Warnung</strong> Setup unvollständig!',
    'About' => 'Über',
    'Admin' => 'Admin',
    'Administration' => 'Administration',
    'Administrative group' => 'Administrations-Gruppe',
    'Advanced' => 'Erweitert',
    'Appearance' => 'Darstellung',
    'Approval' => 'Genehmigung',
    'Authentication' => 'Authentifizierung',
    'Back to overview' => 'Zurück zur Übersicht',
    'Back to user overview' => 'Zurück zur Benutzerübersicht',
    'Base URL needs to begin with http:// or https://' => 'Basis-URL muss mit http:// oder https:// beginnen',
    'Basic' => 'Allgemein',
    'Caching' => 'Caching',
    'Cronjobs' => 'Cronjobs',
    'Design' => 'Design',
    'Files' => 'Dateien',
    'General' => 'Allgemein',
    'Groups' => 'Gruppen',
    'Groups (Note: The Administrator group of this user can\'t be managed with your permissions)' => 'Gruppen (Hinweis: Die Administratorgruppe dieses Benutzers kann nicht mit deinen Berechtigungen verwaltet werden).',
    'Information' => 'Informationen',
    'Invite' => 'Einladen',
    'Invited by' => 'Eingeladen von',
    'Logging' => 'Protokollierung',
    'Logs' => 'Protokolle',
    'Mailing' => 'Mailing',
    'Modules' => 'Module',
    'Notifications' => 'Mitteilungen',
    'OEmbed' => 'OEmbed',
    'OEmbed providers' => 'OEmbed-Provider',
    'Open documentation' => 'Dokumentation öffnen',
    'Pending user registrations' => 'Ausstehende Benutzerregistrierungen',
    'Permissions' => 'Berechtigungen',
    'Proxy' => 'Proxy',
    'Security' => 'Sicherheit',
    'Self test' => 'Selbsttest',
    'Settings' => 'Einstellungen',
    'Sign up' => 'Registrieren',
    'Spaces' => 'Spaces',
    'Statistics' => 'Statistiken',
    'The cron job for the background jobs (queue) does not seem to work properly.' => 'Der Cron-Job für die Hintergrundjobs (Queue) scheint nicht richtig zu funktionieren.',
    'The cron job for the regular tasks (cron) does not seem to work properly.' => 'Der Cron-Job für die regulären Aufgaben (cron) scheint nicht richtig zu funktionieren.',
    'User posts' => 'Benutzerbeiträge',
    'Userprofiles' => 'Benutzerprofile',
    'Users' => 'Benutzer',
];
