<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Account Request for \'{displayName}\' has been approved.' => 'Zugang für \'{displayName}\' wurde genehmigt.',
    'Account Request for \'{displayName}\' has been declined.' => 'Zugang für \'{displayName}\' wurde abgelehnt.',
    'Hello {displayName},<br><br>

   your account has been activated.<br><br>

   Click here to login:<br>
   <a href=\'{loginURL}\'>{loginURL}</a><br><br>

   Kind Regards<br>
   {AdminName}<br><br>' => 'Hallo {displayName},<br><br>

   Dein Zugang wurde aktiviert.<br><br>

   Hier klicken um Dich einzuloggen:<br>
   <a href=\'{loginURL}\'>{loginURL}</a><br><br>

   Mit freundlichem Gruß<br>
   {AdminName}<br><br>',
    'Hello {displayName},<br><br>

   your account request has been declined.<br><br>

   Kind Regards<br>
   {AdminName}<br><br>' => '@@Hallo {displayName},<br><br>
  
   deine Zugangsanfrage wurde abgelehnt.<br><br> 
      
   mit freundlichen Grüßen<br>
   {AdminName}<br><br>@@',
    'User not found!' => 'Benutzer nicht gefunden!',
];
