<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '
Module successfully disabled!
' => 'Module succesvol uitgeschakeld!',
    '
Module successfully enabled!
' => 'Module succesvol ingeschakeld!',
    '--- Disable module: {moduleId} ---

' => '---  Schakel module: {moduleId}  uit ---',
    '--- Enable module: {moduleId} ---

' => '---  Schakel module: {moduleId}  in ---',
    '<strong>Activate</strong> your Professional Edition' => '<strong>Activeer</strong> uw Professional-editie',
    'Add purchased module by licence key' => 'Aangeschafte module toevoegen met de licentie code',
    'All modules are up to date!' => 'Alle modules zijn up-to-date!',
    'All {moduleId} module content will be deleted. Continue?' => 'Alle inhoud van de module {moduleId} wordt verwijderd. Wilt u doorgaan?',
    'Available updates' => 'Beschikbare updates',
    'Browse online' => 'Blader online',
    'Buy (%price%)' => 'Koop (%price%)',
    'Could not connect to licence server!' => 'Kan geen verbinding maken met de licentieserver!',
    'Could not extract module!' => 'Kon module niet uitpakken!',
    'Could not remove old module path!' => 'Kan het oude modulepad niet verwijderen!',
    'Could not update licence. Error: ' => 'Kan de licentie niet updaten. Fout:',
    'Download of module failed!' => 'Download van module mislukt!',
    'Edit licence' => 'Licentie bewerken',
    'Install' => 'Installeren',
    'Installed' => 'Geïnstalleerd',
    'Installed version:' => 'Geïnstalleerde versie:',
    'Installing module...' => 'Module installeren...',
    'Latest compatible Version:' => 'Nieuwste compatibele versie:',
    'Latest compatible version:' => 'Nieuwste compatibele versie:',
    'Latest version:' => 'Nieuwste versie:',
    'Licence Key:' => 'Licentie code:',
    'Licence key' => 'Licentiesleutel',
    'Licenced for max. {number} users.' => 'Licentie voor maximaal {number} gebruikers.',
    'Licenced to:' => 'Licentie verleend aan:',
    'Marketplace' => 'Marktplein',
    'Max. users:' => 'Maximale aantal gebruikers:',
    'Module directory %modulePath% is not writeable!' => 'Modulemap %modulePath% is niet schrijfbaar!',
    'Module download failed! (%error%)' => 'Download van module mislukt! (%error%)',
    'Module not found or activated!
' => 'Module niet gevonden of geactiveerd!',
    'Module not found!
' => 'Module niet gevonden',
    'More info' => 'Meer info',
    'No compatible module version found!' => 'Geen compatibele moduleversie gevonden!',
    'No license key? Find out more about the {pro} or contact us.' => 'Geen licentiesleutel? Lees meer over de {pro} of neem contact met ons op.',
    'No modules found!' => 'Geen modules gevonden!',
    'No purchased modules found!' => 'Geen aangeschafte modules gevonden!',
    'Ok' => 'Ok',
    'Professional Edition is activated!' => 'Professional Edition is geactiveerd!',
    'Purchases' => 'Aankopen',
    'Register' => 'Registreren',
    'Remove licence key' => 'Licentiesleutel verwijderen',
    'Save and update' => 'Opslaan en bijwerken',
    'Search' => 'Zoek',
    'Third-party' => 'Derden',
    'Third-party disclaimer' => 'Derde partij disclamer',
    'Update' => 'Bijwerken',
    'Updating module...' => 'Module bijwerken...',
    'Upgrade to Professional Edition' => 'Upgrade naar Professional Edition',
    'Version:' => 'Versie:',
    'View Changelog' => 'Bekijk changelog',
    'search for available modules online' => 'Zoek online naar beschikbare modules',
    'Buy' => '',
    'If this Module is additionally marked as <strong>"Community"</strong> it is neither tested nor monitored by the HumHub project team.' => '',
    'Include Community Modules' => '',
    'Include beta updates' => '',
    'The HumHub project does not guarantee the functionality, quality or the continuous development of this Module.' => '',
    'Third-party Modules are not covered by Professional Edition agreements.' => '',
    'This Module was developed by a third-party.' => '',
];
