<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Birthday' => '',
  'Custom' => '',
  'Female' => '',
  'Gender' => '',
  'Hide year in profile' => '',
  'Male' => '',
  'About' => 'Sobre',
  'City' => 'Cidade',
  'Country' => 'País',
  'Facebook URL' => 'URL do Facebook',
  'Fax' => 'Fax',
  'First name' => 'Primeiro nome',
  'Flickr URL' => 'URL do Flickr',
  'Google+ URL' => 'URL do Google+',
  'Last name' => 'Último nome',
  'LinkedIn URL' => 'URL do LinkedIn',
  'MSN' => 'MSN',
  'Mobile' => 'Celular',
  'MySpace URL' => 'URL do MySpace',
  'Phone Private' => 'Telefone Privado',
  'Phone Work' => 'Telefone de Trabalho',
  'Skype Nickname' => 'Apelido do Skype',
  'State' => 'Estado',
  'Street' => 'Rua',
  'Title' => 'Título',
  'Twitter URL' => 'URL do Twitter',
  'Url' => 'Url',
  'User' => 'Usuário',
  'Vimeo URL' => 'URL do Vimeo',
  'XMPP Jabber Address' => 'Endereço do XMPP Jabber',
  'Xing URL' => 'URL do Xing',
  'Youtube URL' => 'URL do Youtube',
  'Zip' => 'CEP',
);
