<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Security</strong> settings' => '<strong>الأمان</strong> الاعدادات
',
    '<strong>User</strong> settings' => '<strong>المستخدم</strong> الإعدادت',
    '<strong>Your</strong> profile' => '<strong>حسابك</strong> الشخصي
',
    'Configure' => 'إعدادات',
    'Current password' => 'كلمة المرور الحالية',
    'Disable' => 'إلغاء التفعيل',
    'E-Mail' => 'البريد الالكتروني',
    'E-Mail change' => 'تغيير البريد الالكتروني',
    'Enable' => 'تفعيل',
    'Hide introduction tour panel on dashboard' => 'إخفاء لوحة دليل المستخدم في لوحة المعلومات
',
    'Invalid link! Please make sure that you entered the entire url.' => 'ارتباط غير صالح! الرجاء التأكد من أنك قمت بإدخال عنوان url بالكامل.
',
    'Language' => 'اللغة',
    'Modules' => 'الموديل',
    'New E-Mail address' => 'بريد الكتروني جديد',
    'Notifications' => 'التنبيهات',
    'Password Recovery' => 'ارجاع كلمة المرور',
    'Profile' => 'الحساب',
    'Profile visibility' => 'اتاحة الحساب',
    'Save' => 'حفظ',
    'Save profile' => 'حفظ الحساب',
    'Security' => 'الأمان',
    'Settings' => 'الإعدادات',
    'Tags' => 'الأوسمة',
    'The entered e-mail address is already in use by another user.' => 'عنوان البريد الإلكتروني تم إدخاله مسبقاً قيد الاستخدام من قبل مستخدم آخر.
',
    'TimeZone' => 'التوقيت الزمني',
    '{attribute} "{value}" was not found!' => '{attribute} "{value}" غير موجود!
',
    '<strong>Account</strong> settings' => 'إعدادات <strong> الحساب </strong>',
    '<strong>Confirm</strong></strong> your new email address' => '<strong> تأكد </strong> عنوان بريدك الإلكتروني الجديد',
    '<strong>User</strong> modules' => 'وحدات <strong> المستخدم </strong>',
    'All your personal data will be irrevocably deleted.' => 'سيتم حذف جميع بياناتك الشخصية بشكل لا رجعة فيه.',
    'Are you really sure? *ALL* module data for your profile will be deleted!' => 'هل انت حقا متاكد؟ * سيتم حذف جميع بيانات الوحدة * لملف التعريف الخاص بك!',
    'Are you sure that you want to delete your account?' => 'هل أنت متأكد أنك تريد حذف حسابك؟',
    'Changing the username can make some links unusable, for example old links to the profile.' => 'يمكن أن يؤدي تغيير اسم المستخدم إلى جعل بعض الروابط غير قابلة للاستخدام ، مثل الروابط القديمة للملف الشخصي.',
    'Confirm' => 'أكد',
    'Delete account' => 'حذف الحساب',
    'Do you really want to delete your icon image?' => 'هل تريد حقًا حذف صورة الرمز الخاصة بك؟',
    'Do you really want to delete your logo image?' => 'هل تريد حقًا حذف صورة شعارك؟',
    'Enhance your profile with modules.' => 'تعزيز ملف التعريف الخاص بك مع الوحدات.',
    'Enter your password to continue' => '',
    'Hello' => 'مرحبا',
    'Here you can edit your general profile data, which is visible in the about page of your profile.' => 'هنا يمكنك تعديل بيانات ملفك الشخصي العامة ، والتي تكون مرئية في صفحة حول ملفك الشخصي.',
    'Here you can manage your account permissions for different user-types. To edit a permission, select the user-type you want to edit and change the drop-down value of the given permission.' => 'هنا يمكنك إدارة أذونات حسابك لأنواع المستخدمين المختلفة. لتحرير إذن ، حدد نوع المستخدم الذي تريد تحريره وقم بتغيير القيمة المنسدلة للإذن المحدد.',
    'New User name' => 'اسم مستخدم جديد',
    'Not registered users' => 'المستخدمين غير المسجلين',
    'Other users' => 'المستخدمون الآخرون',
    'Registered users only' => 'الأعضاء المسجلين والمفعلين',
    'Username has been changed' => 'تم تغيير اسم المستخدم',
    'Users' => 'المستخدمون',
    'Visible for all (also unregistered users)' => 'مرئي للجميع (أيضًا المستخدمين غير المسجلين)',
    'We´ve just sent an confirmation e-mail to your new address. <br /> Please follow the instructions inside.' => 'لقد أرسلنا للتو رسالة بريد إلكتروني للتأكيد إلى عنوانك الجديد. <br /> يرجى اتباع التعليمات في الداخل.',
    'You are currently the owner of following spaces:' => 'أنت حاليًا مالك المساحات التالية:',
    'You have requested to change your e-mail address.<br>Your new e-mail address is {newemail}.<br><br>To confirm your new e-mail address please click on the button below.' => 'لقد طلبت تغيير عنوان بريدك الإلكتروني. <br> عنوان بريدك الإلكتروني الجديد هو {newemail}. <br> <br> لتأكيد عنوان بريدك الإلكتروني الجديد ، يرجى النقر على الزر أدناه.',
    'You have successfully changed your username.<br>Your new username is {newUsername}.' => 'لقد غيرت اسم المستخدم بنجاح. <br> اسم المستخدم الجديد هو {newUsername}.',
    'You must transfer ownership or delete these spaces before you can delete your account.' => 'يجب عليك نقل الملكية أو حذف هذه المساحات قبل أن تتمكن من حذف حسابك.',
    'Your account cannot be deleted!' => 'لا يمكن حذف حسابك!',
    'Your current E-mail address is <b>{email}</b>. You can change your current E-mail address here.' => 'عنوان بريدك الإلكتروني الحالي هو <b> {email} </b>. يمكنك تغيير عنوان بريدك الإلكتروني الحالي هنا.',
    'Your current password can be changed here.' => 'يمكن تغيير كلمة المرور الحالية هنا.',
    'Your current username is <b>{username}</b>. You can change your current username here.' => 'اسم المستخدم الحالي الخاص بك هو <b> {اسم المستخدم} </ b>. يمكنك تغيير اسم المستخدم الحالي الخاص بك هنا.',
    'Your e-mail address has been successfully changed to {email}.' => 'تم تغيير عنوان بريدك الإلكتروني إلى {email}.',
    'Your friends' => 'أصدقائك',
    'Your password has been successfully changed!' => 'كلمة السر الخاصة بك تم تغييرها بنجاح!',
    'Your username has been changed' => 'تم تغيير اسم المستخدم الخاص بك',
    'Your username has been successfully changed. <br> We´ve just sent an e-mail to you with new information.' => 'تم تغيير اسم المستخدم الخاص بك بنجاح. <br> لقد أرسلنا لك للتو رسالة بريد إلكتروني تحتوي على معلومات جديدة.',
];
