<?php
return array (
  '<strong>Administration</strong>' => '<strong>Администрация</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Ура!</strong> Това засега е всичко.',
  '<strong>Modules</strong>' => '<strong>Модули</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Като администратор можете да управлявате цялата платформа оттук.<br><br>Освен модулите, няма да разглеждаме подробно всяка точка тук, тъй като всеки има свое кратко описание на друго място.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'В момента сте в менюто с инструменти. Оттук можете да получите достъп до онлайн пазара на HumHub, където можете да инсталирате все по-голям брой инструменти, докато работите.<br><br>Както вече споменахме, инструментите увеличават наличните функции за вашият раздел.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Вече научихте за всички най-важни функции и настройки и сте готови да започнете да използвате платформата.<br><br>Надяваме се, че вие и всички бъдещи потребители ще се радвате да използвате този сайт. Очакваме всички предложения или подкрепа, които желаете да предложите за нашия проект. Чувствайте се свободни да се свържете с нас чрез www.humhub.org.<br><br>Останете на линия. :-)',
);
