<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Latest</strong> updates' => '',
    '<strong>Search</strong>' => '',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => '',
    'Could not determine content container!' => '',
    'Could not find content of addon!' => '',
    'Expand' => '',
    'Insufficent permissions to create content!' => '',
    'It looks like you may have taken the wrong turn.' => '',
    'Latest news' => '',
    'Module is not on this content container enabled!' => '',
    'New profile image' => '',
    'Oooops...' => '',
    'Search for users and spaces' => '',
    'Space not found!' => '',
    'User Approvals' => '',
    'You cannot create public visible content!' => '',
    'Your daily summary' => '',
    'Could not find requested module!' => '@@@@',
    'Invalid request.' => '@@@@',
    'Keyword:' => '@@Riječi:@@',
    'Nothing found with your input.' => '@@@@',
    'Results' => '@@Rezultati@@',
    'Show more results' => '@@Prikaži više rezultata@@',
    'Sorry, nothing found!' => '@@@@',
    'Welcome to %appName%' => '@@Dobrodošao/la na %appName%@@',
    'Account settings' => 'Postavke računa',
    'Administration' => 'Administracija',
    'Back' => 'Natrag',
    'Back to dashboard' => 'Natrag na naslovnicu',
    'Choose language:' => 'Odaberi jezik:',
    'Collapse' => 'Umanji',
    'Error' => 'Error',
    'Language' => 'Jezik',
    'Login' => 'Prijavi se',
    'Logout' => 'Odjavi se',
    'Menu' => 'Meni',
    'My profile' => 'Moj profil',
    'Search' => 'Traži',
    'User not found!' => 'Korisnik nije pronađen',
];
