<?php
return array (
  '<strong>Administration</strong>' => '<strong>Quản trị</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hurraa!</strong> Thế là đủ.',
  '<strong>Modules</strong>' => '<strong>Modules</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Là một quản trị viên, bạn có thể quản lý toàn bộ hệ thống ở đây. <br><br>Tách biệt khỏi các modules, ở đây chúng ta không đi vào chi tiết từng phần cụ thể vì mỗi phần ở đâu đó đều đã có mô tả trực quan để bạn hình dung.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Bạn đang ở menu công cụ. Từ đây bạn có thể truy cập chợ ứng dụng HumHub, nơi bạn có thể cài đặt thêm các modules. <br><br>Như đã đề cập, các modules sẽ tăng thêm các tiện ích tương tác/công cụ/tính năng cho các phòng làm việc của bạn.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Giờ đây bạn đã học toàn bộ những tính năng và cài đặt quan trọng nhất và đã đủ kiến thức để thiết lập hoạt động cho hệ thống. <br><br>Chúng tôi hy vọng bạn và các thành viên trong tương lai sẽ thích thú với việc sử dụng hệ thống. Chúng tôi mong muốn lắng nghe mọi ý kiến đóng góp hoặc hỗ trợ mà bạn mong muốn cho dự án của chúng tôi. Hân hạnh được tương tác với các bạn qua website www.humbhub.org <br><br>. Cùng bắt tay nhé! :-)',
);
