<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Drag a photo here or click to browse your files' => 'Přetáhněte sem fotografii nebo procházejte soubory',
    'Hide my year of birth' => 'Skrýt můj rok narození',
    'Save and close' => 'Uložit a zavřít',
    'You are the first user here... Yehaaa! Be a shining example and complete your profile,<br>so that future users know who is the top dog here and to whom they can turn to if they have questions.' => 'Jste zde první uživatel  ... Yehaaa! Buďte světelným příkladem a doplňte svůj profil, aby budoucí uživatelé věděli, kdo je tady nejlepší a na koho se uživatelé mohou obrátit.',
    'Your firstname' => 'Jméno',
    'Your lastname' => 'Přijmení',
    'Your mobile phone number' => 'Mobilní telefon',
    'Your phone number at work' => 'Telefon do zaměstnání',
    'Your skills, knowledge and experience (comma seperated)' => 'Vaše dovednosti, zkušenosti atd...',
    'Your title or position' => 'Název Vaší pozice',
    'Howdy <strong>%firstname%</strong>, thank you for using %community%.' => '',
];
