<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allow friendships between members' => '',
    'Allow access for non-registered users to public content (guest access)' => 'Tillad adgang for ikke-registrerede bruger til offentligt indhold (gæste adgang)',
    'External users can register (show registration form on login)' => 'Ekstern bruger kan registrere sig (Registreringen formularen vil blive vist på login siden)',
    'Newly registered users have to be activated by an admin first' => 'Nylig registrerede brugere skal aktiveres af en admin først',
    'Registered members can invite new users via email' => 'Registrerede brugere kan invitere nye brugere via email',
];
