<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Crop profile background' => '',
    'Crop profile image' => '',
    'Delete profile image' => '',
    'Missing E-Mail Attribute from AuthClient.' => '',
    'Missing ID AuthClient Attribute from AuthClient.' => '',
    'Sign in / up' => '',
    'Unknown user status!' => '',
    'Upload profile banner' => '',
    'Upload profile image' => '',
    'Your account is disabled!' => '',
    'Your account is not approved yet!' => '',
    'Basic Settings' => 'Ajustes básicos',
    'Change Email' => 'Cambiar correo',
    'Change Password' => 'Cambiar clave',
    'Confirm new password' => 'Confirmar clave',
    'Connect account' => 'Conectar cuenta',
    'Connected Accounts' => 'Cuentas Conectadas',
    'Connected accounts' => 'Cuentas conectadas',
    'Current Password' => 'Clave actual',
    'Currently in use' => 'Actualmente en uso',
    'Delete' => 'Borrar',
    'Delete Account' => 'Borrar cuenta',
    'Disconnect account' => 'Desconectar cuenta',
    'E-Mail is already in use! - Try forgot password.' => '¡Este correo electrónico ya está en uso! - Prueba a restablecer tu contraseña. ',
    'Email' => 'Correo electrónico',
    'General' => 'General',
    'Here you can connect to external service provider for using external services like a single sign on authentication.' => 'Aquí puede conectar a un proveedor de servicios externo para utilizar servicios externos como un solo registro o autenticación.',
    'Modules' => 'Módulos',
    'My Account' => 'Mi Cuenta',
    'New password' => 'Nueva contraseña',
    'No users found.' => 'No se encontraron usuarios.',
    'Notifications' => 'Notificaciones',
    'Password' => 'Contraseña',
    'Profile' => 'Perfil',
    'Security' => 'Seguridad',
    'Settings' => 'Ajustes',
    'Sign in' => 'Iniciar sesión',
    'User' => 'Usuario',
    'User with the same email already exists but isn\'t linked to you. Login using your email first to link it.' => 'Un usuario con el mismo correo ya existe pero está no está conectado con usted. Ingrese con su correo primero para enlazarlo.',
    'You\'re not registered.' => 'Usted no está registrado.',
    'Your new password must not equal your current password!' => 'Su nueva clave no debe ser igual a su clave actual.',
    'or' => 'o',
];
