<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Activities' => '',
  'Adds the activities core module.' => '',
  'Could not create activity for this object type!' => '',
  'Latest activities' => '',
  'See online' => '',
  'There are no activities yet.' => '',
  'Visit space' => '',
  'created a new space' => '',
  'created the new space' => '',
  'created the task:' => '',
  'created this space.' => '',
  'finished task:' => '',
  'go to task' => '',
  'joined space' => '',
  'joined the space' => '',
  'joined this space.' => '',
  'left space' => '',
  'left the space' => '',
  'left this space.' => '',
  'now follows' => '',
  'was assigned to the task:' => '',
  '{user1} now follows {user2}.' => '',
  'Could not create activity for this kind of object!' => '@@@@',
  'created a new workspace' => '@@@@',
  'created this workspace.' => '@@@@',
  'left this workspace.' => '@@@@',
  'left workspace' => '@@@@',
  'see online' => '@@@@',
);
