<?php

return [
    'installed' => true,
    'availableLanguages' => [
        'en' => 'English (US)',
        'en_gb' => 'English (UK)',
        'de' => 'Deutsch',
        'fr' => 'Français',
        'nl' => 'Nederlands',
        'pl' => 'Polski',
        'pt' => 'Português',
        'pt_br' => 'Português do Brasil',
        'es' => 'Español',
        'ca' => 'Català',
        'it' => 'Italiano',
        'th' => 'ไทย',
        'tr' => 'Türkçe',
        'ru' => 'Русский',
        'uk' => 'українська',
        'el' => 'Ελληνικά',
        'ja' => '日本語',
        'hu' => 'Magyar',
        'nb_no' => 'Nnorsk bokmål',
        'zh_cn' => '中文(简体)',
        'zh_tw' => '中文(台灣)',
        'an' => 'Aragonés',
        'vi' => 'Tiếng Việt',
        'sv' => 'Svenska',
        'cs' => 'čeština',
        'da' => 'dansk',
        'uz' => 'Ўзбек',
        'fa_ir' => 'فارسی',
        'bg' => 'български',
        'sk' => 'slovenčina',
        'ro' => 'română',
        'ar' => 'العربية/عربي‎‎',
        'ko' => '한국어',
        'id' => 'Bahasa Indonesia',
        'lt' => 'lietuvių kalba',
    ]
];
