<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Comments' => 'Comentarios',
    'Receive Notifications when someone comments on my own or a following post.' => 'Recibir notificacions quan belún comenta en una publicación de yo u atra que sigo.',
    'View Online' => 'Veyer en linia',
    '{displayNames} commented {contentTitle}' => '{displayNames} ha comentau {contentTitle}',
    '{displayNames} commented {contentTitle} in space {space}' => '{displayNames} ha comentau {contentTitle} en l\'espacio {space}',
    '{displayNames} commented {contentTitle}.' => '{displayNames} ha comentau {contentTitle}.',
    '{displayNames} just commented your {contentTitle}' => '{displayNames} acaba de comentar a tuya {contentTitle}',
    '{displayNames} just commented your {contentTitle} in space {space}' => '{displayNames} acaba de comentar a tuya {contentTitle} en l\'espacio {space}',
    '{displayName} commented {contentTitle}' => '{displayName} ha comentau {contentTitle}',
    '{displayName} commented {contentTitle} in space {space}' => '{displayName} ha comentau {contentTitle} en l\'espacio {space}',
    '{displayName} commented {contentTitle}.' => '{displayName} ha comentau {contentTitle}.',
    '{displayName} just commented your {contentTitle}' => '{displayName} acaba de comentar a tuya {contentTitle}',
    '{displayName} just commented your {contentTitle} in space {space}' => '{displayName} acaba de comentar a tuya {contentTitle} en l\'espacio {space}',
    '[Deleted]' => '',
];
