<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Allow others to create new posts on your profile page' => 'Consenti agli altri utenti di creare post sul tuo profilo',
    'Allows the user to create posts' => 'Permette all\'utente di creare post',
    'Create post' => 'Crea post',
    'Edit your post...' => 'Modifica il tuo articolo...',
    'This space is archived.' => 'Questo spazio è archiviato.',
    'What\'s on your mind?' => 'A cosa stai pensando?',
    'post' => 'Articolo',
];
