<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> Action' => '',
    '<strong>Mail</strong> summary' => '',
    'Add:' => '',
    'An error occurred while handling your last action. (Handler not found).' => '',
    'An unexpected error occurred while loading the search result.' => '',
    'An unexpected error occurred. If this keeps happening, please contact a site administrator.' => '',
    'An unexpected server error occurred. If this keeps happening, please contact a site administrator.' => '',
    'An unknown error occurred while uploading.' => '',
    'An unknown error occurred while uploading. Hint: check your upload_max_filesize and post_max_size php settings.' => '',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => '',
    'Could not find content of addon!' => '',
    'Could not find requested page.' => '',
    'Delete' => '',
    'Do you really want to perform this action?' => '',
    'Edit' => '',
    'Error while running your last action (Invalid request method).' => '',
    'Export' => '',
    'Info:' => '',
    'Invalid request method!' => '',
    'It looks like you may have taken the wrong turn.' => '',
    'Logo of {appName}' => '',
    'Module is not enabled on this content container!' => '',
    'No error information given.' => '',
    'Please type at least {count} characters' => '',
    'Profile dropdown' => '',
    'Profile image of {displayName}' => '',
    'Profile picture of {displayName}' => '',
    'Select Me' => '',
    'Some files could not be uploaded:' => '',
    'Text could not be copied to clipboard' => '',
    'Text has been copied to clipboard' => '',
    'The current main HumHub database name is ' => '',
    'The date has to be in the past.' => '',
    'The requested resource could not be found.' => '',
    'The space has been archived.' => '',
    'The space has been unarchived.' => '',
    'Toggle comment menu' => '',
    'Toggle panel menu' => '',
    'Toggle post menu' => '',
    'Toggle stream entry menu' => '',
    'You are not allowed to run this action.' => '',
    '<strong>Latest</strong> updates' => '<strong>Legújabb</strong> változások',
    'Account settings' => 'Fiók beállítások',
    'Administration' => 'Beállítások',
    'Allow' => 'Engedélyez',
    'Back' => 'Vissza',
    'Back to dashboard' => 'Vissza a kezdőlapomra',
    'Cancel' => 'Mégsem',
    'Choose language:' => 'Válassz nyelvet:',
    'Close' => 'Bezár',
    'Collapse' => 'Összezár',
    'Confirm' => 'Rendben',
    'Copy to clipboard' => 'Másolás vágólapra',
    'Default' => 'Alapértelmezett',
    'Deny' => 'Tilt',
    'Error' => 'Hiba',
    'Error:' => 'Hiba:',
    'Expand' => 'Kinyit',
    'Language' => 'Nyelv:',
    'Loading...' => 'Betöltés...',
    'Login' => 'Belépés',
    'Logout' => 'Kilépés',
    'Menu' => 'Menü',
    'My profile' => 'Profilom',
    'My profile image' => 'Profilképem',
    'New profile image' => 'Új profilkép',
    'Next' => 'Következő',
    'Oooops...' => 'Hoppá...',
    'Open' => 'Megnyitás',
    'Please type at least 3 characters' => 'Gépelj be legalább 3 karaktert',
    'Save' => 'Mentés',
    'Saved' => 'Mentve',
    'Search' => 'Keresés',
    'Show less' => 'Kevesebbet mutat',
    'Show more' => 'Többet mutat',
    'The file has been deleted.' => 'A fájlt törölve lett.',
    'Time Zone' => 'Időzóna',
    'Unsubscribe' => 'Leiratkozás',
    'Upload' => 'Feltöltés',
    'Upload file' => 'Fájl feltöltése',
];
