<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Search</strong>' => '',
    'Back' => '',
    'Choose language:' => '',
    'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => '',
    'Could not determine content container!' => '',
    'Could not find content of addon!' => '',
    'It looks like you may have taken the wrong turn.' => '',
    'Login' => '',
    'Module is not on this content container enabled!' => '',
    'Oooops...' => '',
    'You cannot create public visible content!' => '',
    'Could not find requested module!' => '@@@@',
    'Invalid request.' => '@@Yêu cầu không hợp lệ.@@',
    'Keyword:' => '@@Từ khóa:@@',
    'Nothing found with your input.' => '@@@@',
    'Results' => '@@Kết quả@@',
    'Show more results' => '@@Xem thêm kết quả@@',
    'Sorry, nothing found!' => '@@Không tìm thấy kết quả!@@',
    'Welcome to %appName%' => '@@Chào mừng bạn đến với %appName%@@',
    '<strong>Latest</strong> updates' => 'Cập nhật <strong>mới nhất</strong>',
    'Account settings' => 'Thiết lập tài khoản',
    'Administration' => 'Quản trị',
    'Back to dashboard' => 'Quay về trang chính',
    'Collapse' => 'Thu hẹp',
    'Error' => 'Lỗi',
    'Expand' => 'Mở rộng',
    'Insufficent permissions to create content!' => 'Không đủ quyền để tạo nội dung!',
    'Language' => 'Ngôn ngữ',
    'Latest news' => 'Tin tức mới nhất',
    'Logout' => 'Đăng xuất',
    'Menu' => 'Danh mục',
    'My profile' => 'Hồ sơ của tôi',
    'New profile image' => 'Ảnh đại diện mới',
    'Search' => 'Tìm kiếm',
    'Search for users and spaces' => 'Tìm thành viên và nhóm',
    'Space not found!' => 'Không tìm thấy nhóm!',
    'User Approvals' => 'Chấp thuận người dùng',
    'User not found!' => 'Không tìm thấy thành viên!',
    'Your daily summary' => 'Tóm tắt hàng ngày của bạn',
];
