<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Invites' => 'Запрошення',
  'New user by e-mail (comma separated)' => 'Новий користувач з допомогою e-mail (кома розділювач)',
  'User is already member!' => 'Користувач вже являється учасником!',
  'User not found!' => 'Користувач не знайдений!',
  '{email} is already registered!' => '{email} вже зареєстрований!',
  '{email} is not valid!' => '{email} не є валідною e-mail адресою!',
);
