<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Invite</strong> members' => '<strong>Запросити</strong> учасників',
    'Add an user' => 'Додати користувача',
    'Close' => 'Закрити',
    'Done' => 'Готово',
    'Email addresses' => 'Email адреси',
    'Invite by email' => 'Запросити з допомогою Email',
    'Login' => 'Логін',
    'New user?' => 'Новий користувач?',
    'Pick users' => 'Вибрати користувачів',
    'Send' => 'Надіслати',
    'To invite users to this space, please type their names below to find and pick them.' => 'Для запрошення користувачів до даної спільноти, будьласка, вкажіть їх імена нижче і виберіть їх зі списку.',
    'You can also invite external users, which are not registered now. Just add their e-mail addresses separated by comma.' => 'Ви також можете запросити незареєстрованих користувачів. Просто вкажіть їх адреси через кому.',
];
