<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add purchased module by licence key' => 'افزودن ماژول خريده شده با کلید پروانه',
    'All modules are up to date!' => 'همه‌ی ماژول‌ها به‌روز هستند!',
    'Available updates' => 'به‌روزرسانی‌های موجود',
    'Browse online' => 'دسترسی آنلاین',
    'Buy (%price%)' => '(%price%) خرید',
    'Could not extract module!' => 'ماژول استخراج نشد!',
    'Download of module failed!' => 'دانلود ماژول ناموفق بود!',
    'Install' => 'نصب',
    'Installed' => 'نصب شد',
    'Installed version:' => 'نسخه‌ی نصب‌شده:',
    'Installing module...' => 'درحال نصب ماژول',
    'Latest compatible Version:' => 'آخرین نسخه‌ی سازگار:',
    'Latest compatible version:' => 'آخرین نسخه‌ی سازگار:',
    'Latest version:' => 'آخرین نسخه:',
    'Licence Key:' => 'کد پروانه:',
    'Licence key' => 'کد پروانه',
    'Licenced to:' => 'پروانه داده شده به:',
    'Marketplace' => 'بازار',
    'Max. users:' => 'بیشینه کاربران:',
    'Module directory %modulePath% is not writeable!' => 'پوشه‌ی ماژول %modulePath% نوشتنی نیست!',
    'Module download failed! (%error%)' => 'بارگیری ماژول ناموفق بود! (%error%)',
    'Module not found!
' => 'ماژول پیدا نشد!',
    'More info' => 'اطلاعات بیشتر',
    'No compatible module version found!' => 'هیچ نسخه‌ی ماژول سازگاری یافت نشد!',
    'No modules found!' => 'ماژولی یافت نشد!',
    'No purchased modules found!' => 'هيچ ماژول خريده شده‌ای يافت نشد!',
    'Ok' => 'باشه',
    'Purchases' => 'خریدها',
    'Register' => 'ثبت‌نام',
    'Save and update' => 'ذخیره و به‌روزرسانی',
    'Search' => 'جستجو',
    'Third-party' => 'نفر سوم',
    'Third-party disclaimer' => 'سلب مسئولیت در قبال توسعه‌دهندگان دیگر',
    'Update' => 'به‌روزرسانی',
    'Updating module...' => 'در حال به‌روزرسانی ماژول...',
    'Version:' => 'نسخه:',
    'View Changelog' => 'نمایش سیاهه‌ی تغییر',
    'search for available modules online' => 'به دنبال ماژول‌های آنلاين موجود بگرد',
    '
Module successfully disabled!
' => '',
    '
Module successfully enabled!
' => '',
    '
No active Professional Edition license found!
' => '',
    '
PROFESSIONAL EDITION
' => '',
    '
The license could not be activated:
' => '',
    '
The license was successfully activated!

' => '',
    '
The license was successfully removed!

' => '',
    '--- Disable module: {moduleId} ---

' => '',
    '--- Enable module: {moduleId} ---

' => '',
    '<strong>Activate</strong> your Professional Edition' => '',
    'All {moduleId} module content will be deleted. Continue?' => '',
    'Buy' => '',
    'Could not connect to licence server!' => '',
    'Could not remove old module path!' => '',
    'Could not update licence. Error: ' => '',
    'Edit licence' => '',
    'If this Module is additionally marked as <strong>"Community"</strong> it is neither tested nor monitored by the HumHub project team.' => '',
    'Include Community Modules' => '',
    'Include beta updates' => '',
    'Licenced for max. {number} users.' => '',
    'Module not found or activated!
' => '',
    'No license key? Find out more about the {pro} or contact us.' => '',
    'Professional Edition is activated!' => '',
    'Remove licence key' => '',
    'The HumHub project does not guarantee the functionality, quality or the continuous development of this Module.' => '',
    'Third-party Modules are not covered by Professional Edition agreements.' => '',
    'This Module was developed by a third-party.' => '',
    'Upgrade to Professional Edition' => '',
];
