<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Color' => '',
    'Next' => '',
    'Advanced search settings' => '@@@@',
    'Also non-members can see this<br>space, but have no access' => '@@Tillad ikke-medlemmer til at se denne<br>side, men ikke have adgang@@',
    'Create' => '@@Opret@@',
    'Every user can enter your space<br>without your approval' => '@@Enhver bruger kan tilgå din side<br>uden din accept@@',
    'How you want to name your space?' => '@@Hvad skal navnet på siden være?@@',
    'Please write down a small description for other users.' => '@@Venligst skriv en lille beskrivelse til andre brugere.@@',
    'Private (Invisible)' => '@@Privat (Usynlig)@@',
    'Public (Visible)' => '@@Offentlig (Synlig)@@',
    'This space will be hidden<br>for all non-members' => '@@Denne side vil være usynlig<br>for alle ikke-medlemmer@@',
    'Users can also apply for a<br>membership to this space' => '@@Brugere kan også anmode om<br>medlemskab til denne side@@',
    'Users can be only added<br>by invitation' => '@@Brugere kan kun blive tilføjet<br>ved invitation@@',
    '<strong>Create</strong> new space' => '<strong>Opret</strong> ny side',
    'Advanced access settings' => 'Avancerede adgangsindstillinger',
    'For everyone' => 'For alle',
    'Invite and request' => 'Inviter og anmod',
    'Join Policy' => 'Adgangs politik',
    'Only by invite' => 'Kun ved invitation',
    'Visibility' => 'Synlighed',
    'space description' => 'side beskrivelse',
    'space name' => 'side navn',
];
