<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Most recent</strong> activities' => '<strong>Son</strong> aktiviteler',
    '<strong>Posts</strong>' => '<strong>Gönderiler</strong>',
    '<strong>Profile Guide</strong>' => '<strong>Profil Rehberi</strong>',
    '<strong>Space</strong>' => '<strong>Mekan</strong>',
    '<strong>Space</strong> members' => '<strong>Mekan</strong> üyeleri',
    '<strong>Space</strong> navigation menu' => '<strong>Mekan</strong> navigasyon menü',
    '<strong>Space</strong> preferences' => '<strong>Mekan</strong> tercihleri',
    '<strong>Writing</strong> posts' => 'Gönderi <strong>oluşturma</strong>',
    '<strong>Yay! You\'re done.</strong>' => '<strong>Hey! Herşeyi kaptın.</strong>',
    'All users who are a member of this space will be displayed here.<br /><br />New members can be added by anyone who has been given access rights by the admin.' => 'Mekanın tüm üyeleri burada görünecek.<br /><br />Yeni üyeler yöneticinin yetki verdiği herhangi bir üye tarafından eklenebiMekanın tüm üyeleri burada görünecek.<br /><br />Yeni üyeler yöneticinin yetki verdiği herhangi bir üye tarafından eklenebilir.',
    'New posts can be written and posted here.' => 'Yeni gönderiler burada yazılıp gönderilebiYeni gönderiler burada yazılıp gönderilebilir.',
    'Once you have joined or created a new space you can work on projects, discuss topics or just share information with other users.<br><br>There are various tools to personalize a space, thereby making the work process more productive.' => 'Mekana katıldığında veya yeni oluşturduğunda projeler üzerinde çalışabilirsin, konular üzerinde tartış veya sadece diğerleri ile bilgi paylaş.<br><br> Mekanı kişiselleştirmek için birçok araç mevcut, bu sayede proje sürecini daha üretken hale getirebilirsin.',
    'That\'s it for the space guide.<br><br>To carry on with the user profile guide, click here: ' => 'Bu mekan rehberi için.<br><br>Profil rehberine devam etmek için, buraya tıklBu mekan rehberi için.<br><br>Profil rehberine devam etmek için, buraya tıkla: ',
    'This is where you can navigate the space – where you find which modules are active or available for the particular space you are currently in. These could be polls, tasks or notes for example.<br><br>Only the space admin can manage the space\'s modules.' => 'Buradan mekanını yönetebilirsin - seçtiğin veya bulunduğun mekan için modülleri aktifleştirip inaktifleştirebileceğin araçlar mevcut. Örneğin oylamalar, görevler veya notlar olabilir.<br><br> Sadece mekan yöneticisi modülleri yönetebiBuradan mekanını yönetebilirsin - seçtiğin veya bulunduğun mekan için modülleri aktifleştirip inaktifleştirebileceğin araçlar mevcut. Örneğin oylamalar, görevler veya notlar olabilir.<br><br> Sadece mekan yöneticisi modülleri yönetebilir.',
    'This menu is only visible for space admins. Here you can manage your space settings, add/block members and activate/deactivate tools for this space.' => 'Bu menü sadece mekan yöneticileri için görünür. Buradan mekan ayarlarını yönetebilir, üye ekleme/engelleme ve modül aktifleştirme/deaktifleştirme işlemlerini yapabilirsin.',
    'To keep you up to date, other users\' most recent activities in this space will be displayed here.' => 'Kendini güncel tutman için, diğer kullanıcıların son aktiviteleri burada görünecek.',
    'Yours, and other users\' posts will appear here.<br><br>These can then be liked or commented on.' => 'Senin ve diğer kullanıcıların gönderileri burada görünecek.<br><br>Buradan beğenilebilir veya yorumda bulunulabilir. ',
];
