<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activity' => 'Aktivitás',
    'Add or remove link' => 'Hivatkozás hozzáadása vagy törlése',
    'Animals & Nature' => 'Állatok és természet',
    'Change to code block' => 'Váltás kódra',
    'Change to heading' => 'Váltás címre',
    'Change to paragraph' => 'Váltás szövegre',
    'Code' => 'Kód',
    'Columns' => 'Oszlopok',
    'Create a link' => 'Hivatkozás létrehozása',
    'Create table' => 'Táblázat létrehozása',
    'Delete column' => 'Oszlop törlése',
    'Delete row' => 'Sor törlése',
    'Delete table' => 'Táblázat törlése',
    'Flags' => 'Megjelöltek',
    'Food & Drink' => 'Étel és Ital',
    'Heading' => 'Fejléc',
    'Height' => 'Magasság',
    'Horizontal rule' => 'Horizontális szabály',
    'Image' => 'Kép',
    'Insert' => 'Beillesztés',
    'Insert column after' => 'Sor beillesztése utána',
    'Insert column before' => 'Sor beillesztése előtte',
    'Insert horizontal rule' => 'Horizontális szabály beillesztése',
    'Insert image' => 'Kép beillesztése',
    'Insert row after' => 'Sor beillesztése utána',
    'Insert row before' => 'Sor beillesztése előtte',
    'Insert table' => 'Táblázat beillesztése',
    'Link target' => 'Hivatkozás címe',
    'Location' => 'Elhelyezkedés',
    'Objects' => 'Objektumok',
    'Paragraph' => 'Szövegrész',
    'People' => 'Emberek',
    'Rows' => 'Sorok',
    'Symbols' => 'Szimbólumok',
    'Title' => 'Cím',
    'Toggle code font' => 'Kód betűtípus váltása',
    'Toggle emphasis' => 'Dőlt stílus bekapcsolása',
    'Toggle strikethrough' => 'Áthúzott stílus bekapcsolása',
    'Toggle strong style' => 'Félkövér stílus bekapcsolása',
    'Travel & Places' => 'Utazás és Helyszínek',
    'Type' => 'Típus',
    'Upload File' => 'Fájl feltöltése',
    'Upload and include a File' => 'Fájl feltöltése és belevétele',
    'Width' => 'Szélesség',
    'Wrap in block quote' => 'Idézetblokk használata',
    'Wrap in bullet list' => 'Felsorolás használata',
    'Wrap in ordered list' => 'Számozás használata',
    '[Invalid file]' => '',
];
