<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Define here default settings for new spaces.' => '',
  'Overview' => '',
  'Settings' => '',
  'By Invite' => '@@Par Invitation@@',
  'By invite' => '@@Par invitation@@',
  'Everbody' => '@@Tout le monde et@@',
  'Free' => '@@Libre@@',
  'Invisible' => '@@Invisible@@',
  'Invite & Request' => '@@Invitation et Requête@@',
  'Invite / Request' => '@@Invitation / Requête@@',
  'Registrated only' => '@@Seul les Enregistrés@@',
  'Visible' => '@@Visible@@',
  '<strong>Manage</strong> spaces' => '<strong>Gérer</strong> les Espaces',
  'All' => 'Tous',
  'Delete space' => 'Supprimer l\'Espace',
  'Edit space' => 'Éditer l\'Espace',
  'In this overview you can find every space and manage it.' => 'Dans cette ensemble, vous pouvez trouver n\'importe quel espace et le gérer',
  'Search for space name' => 'Rechercher un Espace (par nom)',
  'Search for space owner' => 'Rechercher un Espace (par Propriétaire)',
  'Space name' => 'Nom de l\'Espace',
  'Space owner' => 'Propriétaire',
  'View space' => 'Voir',
);
