<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{displayNames} commented {contentTitle}' => '{displayNames} 评论了 {contentTitle}',
    '{displayNames} commented {contentTitle} in space {space}' => '{displayNames} 在空间 {space} 评论了 {contentTitle}',
    '{displayNames} just commented your {contentTitle}' => '{displayNames} 刚评论了你的 {contentTitle}',
    '{displayNames} just commented your {contentTitle} in space {space}' => '{displayNames} 刚在空间 {space} 评论了你的 {contentTitle}',
    '{displayName} commented {contentTitle}' => '{displayName} 评论了 {contentTitle}',
    '{displayName} commented {contentTitle} in space {space}' => '{displayName} 在空间 {space} 评论了 {contentTitle}',
    '{displayName} just commented your {contentTitle}' => '{displayName} 刚评论了你的 {contentTitle}',
    '{displayName} just commented your {contentTitle} in space {space}' => '{displayName} 刚在空间 {space} 评论了你的 {contentTitle}',
    '{displayNames} commented {contentTitle}.' => '{displayNames} 评论了 {contentTitle}.',
    '{displayName} commented {contentTitle}.' => '{displayName} 评论了 {contentTitle}.',
];
