<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Space' => 'Přidat prostor',
    'Create new space' => 'Vytvořit nový prostor',
    'My spaces' => 'Mé prostory',
    'No member or following spaces found.' => 'Žádný člen nebo následující prostory nebyly nalezeny.',
    'No result found for the given filter.' => 'Pro daný filtr nebyl nalezen žádný výsledek.',
    'No spaces found for the given query' => 'Pro daný dotaz nebyly nalezeny žádné mezery',
    'Search' => 'Hledat',
    'Search for spaces' => 'Vyhledat prostor',
    'Select {n,plural,=1{space} other{spaces}}' => 'Zvolit {n,plural,=1{space} other{spaces}}',
    'This field only allows a maximum of {n,plural,=1{# space} other{# spaces}}' => 'Toto pole povoluje maximálně {n,plural,=1{# space} other{# spaces}}
',
    'This space is archived' => 'Tento prostor archívován',
    'To search for other spaces, type at least {count} characters.' => 'Chcete-li hledat další prostory, zadejte alespoň {count} znaky.',
    'You are a member of this space' => 'Jste členem tohoto prostoru',
    'You are following this space' => 'Sledujete tento prostor',
    '{n,plural,=1{# new entry} other{# new entries}} since your last visit' => '{n,plural,=1{# new entry} other{# new entries}} od vaší poslední návštěvy',
];
