<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administration</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hurra!</strong> Das wäre es für den Moment.',
  '<strong>Modules</strong>' => '<strong>Module</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Als Admin kannst du die gesamte Plattform von hier aus verwalten. <br><br>Außer den Modulen werden wir nicht jeden Punkt bis ins Detail erläutern, da jeder seine eigene kurze Beschreibung besitzt.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Du befindest dich im Menü <strong>Werkzeuge</strong>. Von hier aus kannst du auf den HumHub Online-Marktplatz zugreifen, wo du eine immer größer werdende Anzahl von Werkzeugen,  on-the- fly installieren kannst. <br> Wie bereits erwähnt, erweitern die Werkzeuge die für Ihren Space verfügbaren Funktionen .',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Du hast nun alle wichtigen Funktionen und Einstellungen kennengelernt und kannst beginnen, die Plattform zu nutzen. <br><br>Wir hoffen, dass du und alle zukünftigen Nutzer die Nutzung dieser Plattform genießen werdet. Wir freuen uns auf Anregungen oder Unterstützung, die du für unser Projekt anbieten möchtest. Kontaktiere uns über www.humhub.org. <br> Stay tuned . :-)',
);
