<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Done' => '',
    'Login' => '',
    '<strong>Invite</strong> members' => '<strong>Invita</strong> membri',
    'Add an user' => 'Aggiungi un utente',
    'Close' => 'Chiudi',
    'Email addresses' => 'Indirizzo email',
    'Invite by email' => 'Invita via email',
    'New user?' => 'Nuovo utente?',
    'Pick users' => 'Scegli gli utenti',
    'Send' => 'Invia',
    'To invite users to this space, please type their names below to find and pick them.' => 'Per invitare utenti a questo space per favore scrivi i loro nomi qui sotto per trovarli e sceglierli.',
    'You can also invite external users, which are not registered now. Just add their e-mail addresses separated by comma.' => 'Puoi anche invitare utenti esterni che non sono ancora registrati. Puoi aggiungere il loro indirizzo e-mail separato da virgola.',
];
