<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => '',
  'Could not determine content container!' => '',
  'Could not find content of addon!' => '',
  'Could not find requested module!' => '',
  'It looks like you may have taken the wrong turn.' => '',
  'Module is not on this content container enabled!' => '',
  'Nothing found with your input.' => '',
  'User Approvals' => '',
  'You cannot create public visible content!' => '',
  'Account settings' => 'Configurações de conta',
  'Administration' => 'Administração',
  'Back to dashboard' => 'Voltar para painel de controle',
  'Collapse' => 'Fechar',
  'Delete' => 'Apagar',
  'Email settings' => 'Configurações de email',
  'Error' => 'Erro',
  'Expand' => 'Expandir',
  'Insufficent permissions to create content!' => 'Permissões insuficientes para criar conteúdo!',
  'Invalid request.' => 'Requisição inválida.',
  'Keyword:' => 'Palavra-chave:',
  'Latest news' => 'Últimas notícias',
  'Logout' => 'Sair',
  'Menu' => 'Menu',
  'My profile' => 'Meu perfil',
  'New profile image' => 'Nova imagem de perfil',
  'Oooops...' => 'Oooops...',
  'Results' => 'Resultados',
  'Search' => 'Busca',
  'Search for users and spaces' => 'Busca por usuários e espaços',
  'Show more results' => 'Mostre mais resultados',
  'Sorry, nothing found!' => 'Desculpe, nada foi encontrado!',
  'Space not found!' => 'Espaço não encontrado!',
  'User not found!' => 'Usuário não encontrado!',
  'Welcome to %appName%' => 'Bem vindo ao %appName%',
  'Your daily summary' => 'Seu resumo diário',
);
