<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Activity' => 'ተግባራት',
    'Add or remove link' => 'ማስፈንጠሪያ ያክሉ፤ ወይም ያስወግዱ',
    'Animals & Nature' => 'እንስሳት እና ተፈጥሮ',
    'Change to code block' => 'ወደሚስጥራዊ ማገጃ ይቀይሩ',
    'Change to heading' => 'ወደርዕስ ይቀይሩ',
    'Change to paragraph' => 'ወደአንቀፅ ቀይር',
    'Code' => 'ኮድ',
    'Columns' => 'አምዶች',
    'Create a link' => 'ማስፈንጠሪያ ፍጠር',
    'Create table' => 'ሳጥን ፍጠር',
    'Delete column' => 'አምዶችን አስወግድ',
    'Delete row' => 'ረድፉን አስወግድ',
    'Delete table' => 'ሳጥኑን አስወግድ',
    'Flags' => 'ሰንደቅ አላማዎች',
    'Food & Drink' => 'ምግብ እና መጠጥ',
    'Heading' => 'ራስጌ',
    'Height' => 'ቁመት',
    'Horizontal rule' => 'አግድሞሻዊ ህግ',
    'Image' => 'ምስል',
    'Insert' => 'አስገባ',
    'Insert column after' => 'አምዱን ቀጥሎ አስገባ',
    'Insert column before' => 'አምዱን አስቀድመህ አስገባ',
    'Insert horizontal rule' => 'አግድሞሻዊ ህጉን አስገባ',
    'Insert image' => 'ምስል አስገባ',
    'Insert row after' => 'ረድፉን ከኋላ አስገባ',
    'Insert row before' => 'ረድፉን ከፊት አስገባ',
    'Insert table' => 'ሳጥን አስገባ',
    'Link target' => 'የማስፈንጠሪያ ማስፈሪያ',
    'Location' => 'አቅጣጫ',
    'Objects' => 'ነገሮች',
    'Paragraph' => 'አንቀፅ',
    'People' => 'ህዝብ',
    'Rows' => 'ረድፎች',
    'Symbols' => 'ምልክቶች',
    'Title' => 'ርዕስ',
    'Toggle code font' => 'የፅሁፍ ቅርፅ ኮዱን ቀይር',
    'Toggle emphasis' => 'አፅንኦት መስጫዎቹን ቀይር',
    'Toggle strikethrough' => 'መሰረዣውን ቀይር',
    'Toggle strong style' => 'ማድመቂያ ዘዴውን ቀይር',
    'Travel & Places' => 'ጉዞ እና ስፍራዎች',
    'Type' => 'አይነት',
    'Upload File' => 'ፋይል ጫን',
    'Upload and include a File' => 'ፋይል ጫን እና አካት',
    'Width' => 'ስፋት',
    'Wrap in block quote' => 'በደማቅ ጥቅስ አጠቃል',
    'Wrap in bullet list' => 'በዝርዝር ነጥብ አጠቃል',
    'Wrap in ordered list' => 'በቅደም ተከተላዊ ዝርዝር አጠቃል',
    '[Code Block]' => '',
    '[Invalid file]' => '',
    '[Table]' => '',
];
