<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Open</strong> file' => '<strong>Abrir</strong> fichero',
    '<strong>Upload</strong> error' => '<strong>Error</strong> al subir',
    'Close' => 'Cerrar',
    'Could not find requested file variant!' => '¡No se pudo encontrar la variante del archivo solicitada!',
    'Could not find requested file!' => '¡No se pudo encontrar el archivo solicitado!',
    'Could not upload File:' => 'No se puede subir el archivo:',
    'Created by:' => 'Crado por:',
    'Double file extensions are not allowed!' => '¡No se permiten dobles extensiones!',
    'Download' => 'Bajar',
    'File {fileName} could not be uploaded!' => '¡No se pudo subir el archivo {fileName}!',
    'Insufficient permissions!' => '¡Permisos insuficientes!',
    'Invalid Mime-Type' => 'Tipo Mime no válido',
    'Invalid file name detected!' => '¡Se ha detectado un fichero inválido!',
    'Last update by:' => 'Última actualización hecha por:',
    'Size:' => 'Tamaño:',
    'Sorry, you can only upload up to {n,plural,=1{# file} other{# files}} at once.' => 'Lo sentimos, pero sólo puedes subir {n,plural,=1{# fichero} other{# ficheros}} de una vez.',
    'This upload field only allows a maximum of {n,plural,=1{# file} other{# files}}.' => 'Este campo permite un máximo de {n,plural,=1{# fichero} other{# fichero}}.',
    'Upload files' => 'Subir archivos',
    'The uploaded image is not a squared.' => '',
];
