<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auth Mode' => '',
    'Last Login' => '',
    'Manager' => '',
    'Show At Directory' => '',
    'Show At Registration' => '',
    'Space ID' => '',
    'Created at' => 'Vytvořeno',
    'Created by' => 'Vytvořil(a)',
    'Default Space' => 'Výchozí prostor',
    'Description' => 'Popis',
    'Email' => 'E-mail',
    'Language' => 'Jazyk',
    'Name' => 'Jméno skupiny',
    'New user needs approval' => 'Nový uživatel potřebuje schválení',
    'Status' => 'Stav',
    'Tags' => 'Štítky',
    'Updated at' => 'Vytvořeno',
    'Updated by' => 'Vytvořil(a)',
    'Username' => 'Uživatelské jméno',
    'Visibility' => 'Viditelnost',
];
