<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Latest</strong> updates' => '',
  'Account settings' => 'Paramètres du compte',
  'Administration' => 'Administration',
  'Back to dashboard' => 'Retour au tableau de bord',
  'Collapse' => 'Réduire',
  'Content Addon source must be instance of HActiveRecordContent or HActiveRecordContentAddon!' => 'Le contenu d\'un add-on doit être une instance de HActiveRecordContent ou HActiveRecordContentAddon!',
  'Could not determine content container!' => 'Le contenu du conteneur ne peut être déterminé',
  'Could not find content of addon!' => 'Le contenu du add-on ne peut être trouvé',
  'Could not find requested module!' => 'Le module requi est introuvable.',
  'Error' => 'Erreur',
  'Expand' => 'Agrandir',
  'Insufficent permissions to create content!' => 'Droits d\'accès insuffisants pour créer du contenu',
  'Invalid request.' => 'Requête invalide',
  'It looks like you may have taken the wrong turn.' => 'Il semblerait que vous n\'êtes pas au bon endroit',
  'Keyword:' => 'Mot-clé:',
  'Latest news' => 'Dernières nouvelles',
  'Logout' => 'Se déconnecter',
  'Menu' => 'Menu',
  'Module is not on this content container enabled!' => 'Le module n\'est pas activé pour ce conteneur',
  'My profile' => 'Mon profil',
  'New profile image' => 'Nouvelle image de profil',
  'Nothing found with your input.' => 'Aucun élément trouvé à partir de votre saisie',
  'Oooops...' => 'Oups....',
  'Results' => 'Résultats',
  'Search' => 'Recherche',
  'Search for users and spaces' => 'Recherche d\'utilisateurs et d\'espaces',
  'Show more results' => 'Plus de résultats',
  'Sorry, nothing found!' => 'Désolé, aucun élément trouvé!',
  'Space not found!' => 'Espace non trouvé!',
  'User Approvals' => 'Approbations utilisateur',
  'User not found!' => 'Utilisateur non trouvé',
  'Welcome to %appName%' => 'Bienvenue sur %appName%',
  'You cannot create public visible content!' => 'Vous ne pouvez créer un contenu public visible!',
  'Your daily summary' => 'Votre rapport quotidien',
);
