<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Space</strong> followers' => '',
    'No spaces found.' => '',
    'Could not delete user who is a space owner! Name of Space: {spaceName}' => 'Nie można usunąć użytkownika który jest właścicielem strefy! Nazwa strefy: {spaceName} ',
    'Default' => 'Domyślna',
    'Everyone can enter' => 'Każdy może dołączyć ',
    'Invite and request' => 'Zaproś i złóż podanie ',
    'Only by invite' => 'Tylko przez zaproszenie ',
    'Private' => 'Prywatna',
    'Private (Invisible)' => 'Prywatna (nie widoczna) ',
    'Public' => 'Publiczna',
    'Public (Members & Guests)' => 'Publiczna (Członkowie i Goście)',
    'Public (Members only)' => 'Publiczna (Tylko członkowie)',
    'Public (Registered users only)' => 'Publiczna (Tylko zarejestrowani)',
    'Public (Visible)' => 'Publiczna (widoczna) ',
    'Visible for all (members and guests)' => 'Widoczne dla wszystkich (użytkownicy i goście)',
];
