<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Drag a photo here or click to browse your files' => 'Arrociega aquí una foto u preta per seleccionar d\'os tuyos fichers',
    'Hide my year of birth' => 'No amostrar a mía calendata de naiximiento',
    'Save and close' => 'Alzar y zarrar',
    'Your firstname' => 'Nombre',
    'Your lastname' => 'Apellido',
    'Your mobile phone number' => 'Numero de mobil',
    'Your phone number at work' => 'Numero de mobil de treballo',
    'Your title or position' => 'Títol u posición',
    'Howdy <strong>%firstname%</strong>, thank you for using %community%.' => '',
    'You are the first user here... Yehaaa! Be a shining example and complete your profile,<br>so that future users know who is the top dog here and to whom they can turn to if they have questions.' => '',
    'Your skills, knowledge and experience (comma seperated)' => '',
];
