// MarketplaceModuleSerializer::module()
export const marketplaceModule = (overrides = {}) => ({
    id: 'calendar-x',
    name: 'Calendar X',
    description: 'Plan events together',
    imageUrl: '/img/calendar.png',
    marketplaceUrl: 'https://marketplace.humhub.com/module/calendar-x',
    categories: [1],
    latestVersion: '2.0.0',
    latestCompatibleVersion: '2.0.0',
    installedVersion: null,
    isEnabled: false,
    updateAvailable: false,
    configUrl: null,
    checkoutUrl: null,
    price: null,
    purchased: false,
    featured: false,
    licenceKey: null,
    badge: 'official',
    isThirdParty: false,
    isCommunity: false,
    availability: 'install',
    ...overrides,
});
