<?php
return array (
  '<strong>Administration</strong>' => '<strong>Adminisztráció</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hurrá!</strong> Egyelőre ennyi.',
  '<strong>Modules</strong>' => '<strong>Modulok</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Adminként az egész platformot kezelheted innen.<br /><br />A modulok kivételével itt nem megyünk bele a részletekbe minden ponttal kapcsolatban, mivel mindegyiknek megvan a saját rövid leírása máshol.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Jelenleg az Eszközök menüben vagy. Innen hozzáférhetsz a HumHub online piacteréhez, ahol egyre több eszközt telepíthetsz, ahogy haladsz előre.<br /><br />Mint már említettük, az eszközök növelik a számodra a közösségeden belül  elérhető funkciók körét.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Most áttekintettük az összes fontosabb funkciót és beállítást, és minden készen áll ahhoz, hogy elkezdd használni a platformot. <br /><br /> Reméljük, hogy Te és minden jövőbeli felhasználó élvezni fogja ezt a webhelyet. Várunk minden olyan javaslatot vagy támogatást, amelyet a projektünkhöz esetleg nyújtani kívánsz. Lépj velünk kapcsolatba a www.humhub.org címen.<br /><br />Folyt köv. :-)',
);
