<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Email</strong> Notifications' => '<strong>Email</strong>-Benachrichtigungen',
  'Activities' => 'Aktivitäten',
  'Always' => 'Sofort',
  'Daily summary' => 'Tägliche Zusammenfassung',
  'Get an email, by every activity from other users you follow or work<br>together in workspaces.' => 'Erhalten Sie eine Email bei jeder Aktivität anderer Benutzer, denen Sie folgen oder mit denen Sie in Räumen zusammenarbeiten.',
  'Get an email, when other users comment or like your posts.' => 'Erhalten Sie eine Email, wenn andere Benutzer Ihre Beiträge kommentieren oder bewerten.',
  'Never' => 'Nie',
  'Notifications' => 'Benachrichtigungen',
  'Save' => 'Speichern',
  'When I´m offline' => 'Wenn ich offline bin',
);
