<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  '<strong>Your account</strong> has been successfully created!' => '<strong>Ihr Konto</strong> wurde erfolgreich erstellt!',
  'After activating your account by the administrator, you will receive a notification by email.' => 'Nach der Aktivierung Ihres Kontos durch einen Administrator werden sie eine Benachrichtigung per Email erhalten.',
  'Go to login page' => 'Zur Loginseite',
  'To log in with your new account, click the button below.' => 'Um sich mit Ihrem neuen Konto einzuloggen, klicken Sie unten auf den Button.',
  'back to home' => 'zurück zur Startseite',
);
