<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Current Password' => '',
    'Sign in' => '',
    'Sign in / up' => '',
    'Basic Settings' => 'Standard instillinger',
    'Change Email' => 'Endre e-mail',
    'Change Password' => 'Bytt passord',
    'Confirm new password' => 'Bekreft nytt passord',
    'Connect account' => 'Koble til konto',
    'Connected Accounts' => 'Tilknyttede Kontoer',
    'Connected accounts' => 'Tilknyttede kontoer',
    'Currently in use' => 'I bruk nå',
    'Delete' => 'Slett',
    'Delete Account' => 'Slett Konto',
    'Disconnect account' => 'Frakoble Konto',
    'E-Mail is already in use! - Try forgot password.' => 'E-mail er allerede i bruk! - Prøv glemt passord.',
    'Email' => 'E-mail',
    'General' => 'Gennerelt',
    'Here you can connect to external service provider for using external services like a single sign on authentication.' => 'Her kan du koble til eksterne tjenesteleverandører for bruk av eksterne tjenester som en single sign-on-godkjenning.',
    'Modules' => 'Moduler',
    'My Account' => 'Min konto',
    'New password' => 'Nytt passord',
    'No users found.' => 'Ingen brukere funnet.',
    'Notifications' => 'Varsler',
    'Password' => 'Passord',
    'Profile' => 'Profil',
    'Security' => 'Sikkerhet',
    'Settings' => 'Instillinger',
    'User' => 'Bruker',
    'User with the same email already exists but isn\'t linked to you. Login using your email first to link it.' => 'En bruker med den samme e-mail eksisterer allerede og er ikke linket til deg. Logg inn med din e-mail og tilknytt konto først',
    'You\'re not registered.' => 'Du er ikke registrert',
    'Your new password must not equal your current password!' => 'Ditt nye passord kan ikke være ditt samme som nåværende!',
    'or' => 'eller',
];
