<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Administration</strong> menu' => 'منوی <strong>مدیریت</strong>',
    'About' => 'درباره‌ی',
    'Admin' => 'مدير كل',
    'Administration' => 'مدیریت',
    'Administrative group' => 'گروه مديريتي',
    'Advanced' => 'پیشرفته',
    'Appearance' => 'ظاهر',
    'Approval' => 'تصويب',
    'Authentication' => 'احراز هويت',
    'Back to overview' => 'برگشت به دید کلی',
    'Basic' => 'پايه',
    'Caching' => 'دخیره در حافظه‌ی موقت',
    'Cronjobs' => 'كرون جاب',
    'Design' => 'طراحي',
    'Files' => 'فایل‌ها',
    'General' => 'کلی',
    'Groups' => 'گروه‌ها',
    'Information' => 'اطلاعات',
    'Invite' => 'دعوت',
    'Logging' => 'ورود',
    'Mailing' => 'ارسال ايميل',
    'Modules' => 'ماژول‌ها',
    'Notifications' => 'اعلان‌ها',
    'OEmbed' => 'OEmbed
',
    'OEmbed providers' => 'ارائه دهدگان OEmbed ',
    'Permissions' => 'مجوز ها',
    'Proxy' => 'پراکسی',
    'Security' => 'امنيت',
    'Self test' => 'تست خود',
    'Settings' => 'تنطیمات',
    'Sign up' => 'عضو شدن',
    'Spaces' => 'انجمن‌ها',
    'Statistics' => 'آمار',
    'User posts' => 'پست هاي كاربر',
    'Userprofiles' => 'پروفايل هاي كاربري',
    'Users' => 'کاربران',
    '<strong>Module </strong> administration' => '',
    '<strong>Warning</strong> incomplete setup!' => '',
    'Back to user overview' => '',
    'Base URL needs to begin with http:// or https://' => '',
    'E-Mail summaries' => '',
    'Groups (Note: The Administrator group of this user can\'t be managed with your permissions)' => '',
    'Invited by' => '',
    'Logs' => '',
    'Open documentation' => '',
    'Pending user registrations' => '',
    'The cron job for the background jobs (queue) does not seem to work properly.' => '',
    'The cron job for the regular tasks (cron) does not seem to work properly.' => '',
];
