<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About HumHub' => 'درباره هام‌هاب',
    'Checking HumHub software prerequisites.' => 'چک کردن پیش‌نیازهای نرم‌افزار هام‌هاب',
    'Database' => 'پایگاه داده',
    'Database migration results:' => 'نتایج مهاجرت پایگاه داده:',
    'Delayed' => 'تاخیر خورده',
    'Displaying {count} entries per page.' => 'نمایش {count} مطالب برای هر صفحه',
    'Done' => 'انجام شد',
    'Driver' => 'راه‌انداز',
    'Flush entries' => 'تخلیه‌ی مطالب',
    'HumHub is currently in debug mode. Disable it when running on production!' => 'هام‌هاب هم اکنون در حالت خطایابی (debug) است.',
    'Last run (daily):' => 'آخرین اجرا (روزانه):',
    'Last run (hourly):' => 'آخرین اجرا (ساعت):',
    'Licences' => 'گواهینامه‌ها',
    'Logging' => 'ثبت رویدادها',
    'Never' => 'هرگز',
    'Prerequisites' => 'پیش‌نیازها',
    'Re-Run tests' => 'اجرای دوباره‌ی تست‌ها',
    'See installation manual for more details.' => 'راهنمای نصب را برای جزئیات بیشتر ببینید',
    'There is a new update available! (Latest version: %version%)' => 'یک به‌روزرسانی تازه موجود است! (آخرین نسخه: %version%)',
    'This HumHub installation is up to date!' => 'هام‌هاب نصب شده به روز است!',
    'Total {count} entries found.' => 'کلا {count} مدخل یافت شد.',
    'Waiting' => 'در انتظار',
    '<strong>CronJob</strong> Status' => '',
    '<strong>Queue</strong> Status' => '',
    'Background Jobs' => '',
    'Error' => '',
    'Info' => '',
    'Other' => '',
    'Please refer to the documentation to setup the cronjobs and queue workers.' => '',
    'Queue successfully cleared.' => '',
    'Reserved' => '',
    'Search index rebuild in progress.' => '',
    'Search term...' => '',
    'Select category..' => '',
    'Select day' => '',
    'Select level...' => '',
    'The current main HumHub database name is ' => '',
    'Trace' => '',
    'Warning' => '',
];
