<?php
return array (
  '<strong>Administration</strong>' => '<strong>Администрирование</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Ура!</strong> Это все на сегодня.',
  '<strong>Modules</strong>' => '<strong>Модули</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'В роли администратора вы можете управлять всей платформой отсюда.<br><br> Кроме модулей мы не будет подробно ни на чем останавливаться, так как у каждого элемента есть свое короткое описание.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Сейчас вы в меню инструментов. Отсюда вы можете получить доступ к каталогу HumHub, откуда можно установить дополнительные модули. <br><br> Как уже упоминалось, инструменты увеличивают работоспосбоность ваших Пространств. ',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Вы уже узнали почти о всех основных возможностях и настройках, и готовы к использованию платформы.<br><br>Надеемся, вы и все будущие пользователя получат удовольствие от использования сайта. Будем рады любым предложениям и замечаниям, которые помогут улучшить проект. Оставайтесь на связи и пишите нам в любое время. :-)',
);
