<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Load more' => '',
    'Back to stream' => 'Yayına dön',
    'Content with attached files' => 'Ekli dosyalarla içerik',
    'Created by me' => 'Benim tarafımdan oluşturuldu',
    'Creation time' => 'Oluşturulma zamanı',
    'Filter' => 'Filtre',
    'Include archived posts' => 'Arşivlenen gönderileri içer',
    'Last update' => 'Son güncelleme',
    'No matches with your selected filters!' => 'Seçili filtreler ile eşleşir.',
    'Nothing here yet!' => 'Burada henüz bir şey yok!',
    'Only private posts' => 'Sadece gizli gönderiler',
    'Only public posts' => 'Sadece açık gönderiler',
    'Posts only' => 'Sadece gönderiler',
    'Posts with links' => 'Linkler gönderilerle birlikte',
    'Sorting' => 'Sıralama',
    'Where I´m involved' => 'Nerede gelişebilirim',
];
