<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' Remove panel' => '移除空间',
  '<strong>Getting</strong> Started' => '<strong>马上</strong>开始',
  '<strong>Guide:</strong> Administration (Modules)' => '<strong>指南：</strong>管理（模块）',
  '<strong>Guide:</strong> Overview' => '<strong>指南：</strong>概述',
  '<strong>Guide:</strong> Spaces' => '<strong>指南：</strong>空间',
  '<strong>Guide:</strong> User profile' => '<strong>指南：</strong> 用户属性',
  'Get to know your way around the site\'s most important features with the following guides:' => '以下指南带你了解网站的主要功能。',
  '<strong>Remove</strong> tour panel' => '<strong>移出</strong> 指南',
  'This action will remove the tour panel from your dashboard. You can reactivate it at<br>Account settings <i class="fa fa-caret-right"></i> Settings.' =>
  '此操作将会从你的主面板上移出用户指南. 你可以在<br>账户设置 <i class="fa fa-caret-right"></i> 设置 里重新打开。',
  'Ok' => '确认',
  'Cancel' => '取消',
);
