<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Administrator:' => '',
    'Moderator:' => '',
    'Owner:' => '',
    '<strong>Space</strong> followers' => '<strong>Sayfa</strong> takipçileri',
    'Could not delete user who is a space owner! Name of Space: {spaceName}' => 'Sayfa sahibi bir kullanıcı silinemedi! Sayfanın adı: {spaceName}',
    'Default' => 'Varsayılan',
    'Everyone can enter' => 'Herkes girebilir',
    'Invite and request' => 'Davet ve İstek talebi',
    'No spaces found.' => 'Sayfa bulunamadı.',
    'Only by invite' => 'Sadece davetliler',
    'Private' => 'Özel',
    'Private (Invisible)' => 'Gizli (Görünmez)',
    'Public' => 'Herkes',
    'Public (Members & Guests)' => 'Genel (Üyeler & Misafirler)',
    'Public (Members only)' => 'Genel (Yalnızca üyeler)',
    'Public (Registered users only)' => 'Genel (Yalnızca kayıtlı kullanıcılar)',
    'Public (Visible)' => 'Genel (Görünür)',
    'Settings' => 'Ayarlar',
    'Space' => 'Sayfa',
    'Visible for all (members and guests)' => 'Tümü görebilir (Üyeler ve Misafirler)',
];
