<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Space</strong> followers' => '',
    'Default' => '',
    'No spaces found.' => '',
    'Private' => '',
    'Public' => '',
    'Could not delete user who is a space owner! Name of Space: {spaceName}' => 'Mekan sahibi bir kullanıcı silinemedi! Mekanın adı: {spaceName}',
    'Everyone can enter' => 'Herkes girebilir',
    'Invite and request' => 'Davet et ve İstek yolla',
    'Only by invite' => 'Sadece davelliler',
    'Private (Invisible)' => 'Özel (Görünmez)',
    'Public (Members & Guests)' => 'Genel (Üyeler & Misafir)',
    'Public (Members only)' => 'Genel (Üyeler için)',
    'Public (Registered users only)' => 'Genel (Sadece kayıtlı kullanıcılar)',
    'Public (Visible)' => 'Genel (Görünür)',
    'Visible for all (members and guests)' => 'Tümü görebilir (Üye ve Misafir)',
];
