<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> post deletion' => '<strong>Patvirtinti</strong> įrašo ištrynimą',
    '<strong>Permalink</strong> to this post' => '<strong>Priskirti</strong> nuorodą šiam įrašui',
    'Add a member to notify' => 'Pridėti narį prie pranešimų',
    'Archived' => 'Archyvuotas',
    'Back to stream' => 'Grįžti į sieną',
    'Cancel' => 'Atšaukti',
    'Content' => 'Turinys',
    'Could not find requested content!' => 'Ieškomas turinys nerastas!',
    'Created by me' => 'Sukurta mano',
    'Creation time' => 'Sukūrimo laikas',
    'Delete' => 'Ištrinti',
    'Do you really want to delete this post? All likes and comments will be lost!' => 'Ar tikrai norite ištrinti šį įrašą? Visi komentarai bus ištrinti!',
    'Edit' => 'Taisyti',
    'Filter' => 'Filtras',
    'Last update' => 'Paskutiniai atnaujinimai',
    'Change to "Private"' => 'Padaryti privačiu',
    'Change to "Public"' => 'Padaryti viešą',
    'Move to archive' => 'Perkelti į archyvą',
    'No matches with your selected filters!' => 'Nerasta atitikimų su pasirinktais filtrais!',
    'Nothing here yet!' => 'Nieko nerasta!',
    'Notify members' => 'Pranešti nariams',
    'Permalink' => 'Nuoroda',
    'Pinned' => 'Prisegtas',
    'Public' => 'Višas',
    'Submit' => 'Pateikti',
    'Turn off notifications' => 'Išjunkti pranešimus',
    'Turn on notifications' => 'Įjungti pranešimus',
    'Unarchive' => 'Išarchyvuoti',
    'in' => 'į',
    '(Also visible to non-members of this space)' => '',
    '<strong>Move</strong> content' => '',
    'Attach Files' => '',
    'Cancel Edit' => '',
    'Content Tag with invalid contentcontainer_id assigned.' => '',
    'Content has been moved to {spacename}' => '',
    'Content visibility' => '',
    'Could not delete content!' => '',
    'Could not delete content: Access denied!' => '',
    'Invalid content id given!' => '',
    'Invalid request method!' => '',
    'Invalid space selection.' => '',
    'Last updated {time}' => '',
    'Load more' => '',
    'Maximum number of pinned items reached!<br>You can only pin up to {count} items at once.' => '',
    'Move content' => '',
    'None' => '',
    'Only private content' => '',
    'Only public content' => '',
    'Pin to top' => '',
    'Specify who can see this content.' => '',
    'Tag' => '',
    'Target Space' => '',
    'The author of this content is not allowed to create private content within the selected space.' => '',
    'The author of this content is not allowed to create public content within the selected space.' => '',
    'The author of this content is not allowed to create this type of content within this space.' => '',
    'The content can\'t be moved to its current space.' => '',
    'The content has been archived.' => '',
    'The content has been deleted.' => '',
    'The content has been unarchived.' => '',
    'The given name is already in use.' => '',
    'The module {moduleName} is not enabled on the selected target space.' => '',
    'This action is disabled!' => '',
    'This content type can\'t be moved due to a missing module-id setting.' => '',
    'This content type can\'t be moved.' => '',
    'This space is archived.' => '',
    'This space is not visible!' => '',
    'Topics' => '',
    'Unpin' => '',
    'Updated' => '',
    'Visible also to unregistered users' => '',
    'Visible only to you' => '',
    'Visible to all Space members' => '',
    'Visible to all signed in users' => '',
    'Visible to friends of {displayName}' => '',
    'Visible to you and {displayName}' => '',
    'Visible to your friends' => '',
    'Where I\'m involved' => '',
    'With file attachments' => '',
    'You do not have the permission to move this content to the given space.' => '',
    'You do not have the permission to move this content.' => '',
    'Your last edit state has been saved!' => '',
];
