<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'No matches with your selected filters!' => '',
    'Nothing here yet!' => '',
    '<b>Nobody wrote something yet.</b><br>Make the beginning and post something...' => '@@<b>Nėra jokio įrašo.</b><br>Parašykite pirmas...@@',
    '<b>This profile stream is still empty</b>' => '@@<b>Šio profilio siena vis dar tuščias</b>@@',
    '<b>This space is still empty!</b><br>Start by posting something here...' => '@@<b>Ši erdvė vis dar tuščia!</b><br>Parašykite pirmą įrašą...@@',
    '<b>Your dashboard is empty!</b><br>Post something on your profile or join some spaces!' => '@@<b>Jūsų puslapis tusčias!</b><br>@@',
    '<b>Your profile stream is still empty</b><br>Get started and post something...' => '@@<b>Yra tusčias!</b><br>@@',
    'Nothing found which matches your current filter(s)!' => '@@Pagal Jūsų filtrus nerasta jokios informacijos!@@',
    'Back to stream' => 'Grįžti į sieną',
    'Content with attached files' => 'Turinys su prisegtais failais',
    'Created by me' => 'Sukurta mano',
    'Creation time' => 'Sukūrimo laikas',
    'Filter' => 'Filtras',
    'Include archived posts' => 'Įtraukti archyvo įrašus',
    'Last update' => 'Paskutiniai atnaujinimai',
    'Only private posts' => 'Tik privatūs įrašai',
    'Only public posts' => 'Tik vieši įrašai',
    'Posts only' => 'Tik įrašai',
    'Posts with links' => 'Įrašai su nuorodomis',
    'Sorting' => 'Rūšiuoti',
    'Where I´m involved' => 'Aš dalyvauju',
];
