name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          close-issue-message: 'This issue was closed because it has been stalled for 30 days with no activity.'
          days-before-stale: -1
          days-before-close: 30
          days-before-pr-close: -1
          debug-only: false
          only-labels: 'Kind: Server/Installation Problem/Question,awaiting-answers'
