<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administração</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hurra!!!</strong> É tudo por agora.',
  '<strong>Modules</strong>' => '<strong>Módulos</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'A Administração pode gerir a plataforma inteira a partir daqui.<br><br>Módulos à parte, não entraremos em pormenores, já que cada ponto tem a sua própria curta descrição noutro local.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Este é   o menu de ferramentas. A partir daqui, podes aceder ao mercado em linha do HumHub, onde podes instalar rapidamente um cada vez maior número de ferramentas <br><br>Como já mencionado, as ferramentas aumentam as funcionalidades disponíveis para o seu espaço.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Já aprendeste acerca das funcionalidades e definições mais importantes e podes começar a usar a plataforma<br><br>Esperamos que aprecies usar este site, bem como todos os futuros utilizadores. Ansiamos por sugestões ou apoio que queiras oferecer ao projecto. Contacta-nos através de www.humhub.org.<br><br>Fica ligado/a. :-)',
);
