<?php
return array (
  '<strong>Administration</strong>' => '<strong>Administrador</strong>',
  '<strong>Hurray!</strong> That\'s all for now.' => '<strong>Hurra!!!</strong> Isto é tudo por agora.',
  '<strong>Modules</strong>' => '<strong>Módulos</strong>',
  'As an admin, you can manage the whole platform from here.<br><br>Apart from the modules, we are not going to go into each point in detail here, as each has its own short description elsewhere.' => 'Como administrador, pode gerir a plataforma inteira a partir daqui.<br><br>Para além dos módulos, não vamos detalhar tudo aqui, já que cada ponto aqui, já que cada um tem uma descrição curta nalgum outro sítio.',
  'You are currently in the tools menu. From here you can access the HumHub online marketplace, where you can install an ever increasing number of tools on-the-fly.<br><br>As already mentioned, the tools increase the features available for your space.' => 'Está actualmente no menu de ferramentas. A partir daqui, pode aceder ao mercado em linha do HumHub, onde pode instalar um cada vez maior número de ferramentas em directo<br><br>Como já foi mencionado, as ferramentas aumentam as funcionalidades disponíveis para o seu espaço.',
  'You have now learned about all the most important features and settings and are all set to start using the platform.<br><br>We hope you and all future users will enjoy using this site. We are looking forward to any suggestions or support you wish to offer for our project. Feel free to contact us via www.humhub.org.<br><br>Stay tuned. :-)' => 'Já aprendeu acerca das funcionalidades e definições mais importantes e pode começar a usar a plataforma<br><br>Esperamos que aprecie usar este site, bem como todos os futuros utilizadores. Ansiamos por sugestões ou apoio que queira oferecer ao projecto. Contacte-nos através de www.humhub.org.<br><br>Fique ligado/a. :-)',
);
