<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add Space' => 'Voeg een ruimte toe',
    'Create new space' => 'Maak een nieuwe ruimte aan',
    'My spaces' => 'Mijn ruimtes',
    'No member or following spaces found.' => 'Geen enkel lid of volgende ruimtes gevonden.',
    'No result found for the given filter.' => 'Geen resultaat gevonden door het opgegeven filter.',
    'No spaces found for the given query' => 'Geen ruimte zijn gevonden voor deze zoekopdracht.',
    'Search' => 'Zoek',
    'Search for spaces' => 'Zoek naar ruimtes',
    'Select {n,plural,=1{space} other{spaces}}' => 'Kies {n,plural,=1{ruimte} other{ruimtes}}',
    'This field only allows a maximum of {n,plural,=1{# space} other{# spaces}}' => 'Dit veld kent een maximum van {n,plural,=1{# ruimte} other{# ruimtes}}',
    'This space is archived' => 'Deze ruimte is gearchiveerd.',
    'To search for other spaces, type at least {count} characters.' => 'Toets tenminste {count} tekens in bij het zoeken naar andere ruimtes.',
    'You are a member of this space' => 'U bent lid van deze ruimte',
    'You are following this space' => 'U volgt deze ruimte.',
    '{n,plural,=1{# new entry} other{# new entries}} since your last visit' => '{n,plural,=1{# nieuw item} other{# nieuw items}} sinds uw laatste bezoek.',
];
