<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Remove from space' => '',
    'Show all' => '',
    'As owner of this space you can transfer this role to another administrator in space.' => 'Als eigenaar van deze ruimte  kunt u deze rol overdragen naar een andere administrator in deze ruimte.',
    'Space owner' => 'Ruimte eigenaar',
    'The url contains illegal characters!' => 'De URL bevat niet toegestane tekens,',
    'Transfer ownership' => 'Eigenaarschap overdragen',
    'e.g. example for {baseUrl}/s/example' => 'Dat is bijvoorbeeld voor {baseUrl}/s/voorbeeld',
    'the default start page of this space for members' => 'De standaard startpagina voor leden van deze ruimte.',
    'the default start page of this space for visitors' => 'De standaard startpagina voor bezoekers van deze ruimte.',
];
